els-ASAP auto commit file/tag pcp-3.10.9-6.el6.src.rpm

diff --git a/src/qa/1019 b/src/qa/1019
--- a/src/qa/1019
+++ b/src/qa/1019
@@ -4,24 +4,26 @@
 #
 seq=`basename $0`
 echo "QA output created by $seq"
-. ./common.qt
 
-[ -x qt/qmc_group/qmc_group ] || _notrun "qmc_group not built or installed"
+status=1	# failure is the default!
+. ./common.qt
 
 _cleanup()
 {
     if [ ! -f $tmp.done ]
     then
 	cd $here/pmdas/dynamic
-	$sudo ./Remove >>$here/src/$seq.full
+	$sudo ./Remove >>$here/$seq.full
 	cd $here
 	touch $tmp.done
     fi
+    _cleanup_qt
 }
 
-status=1	# failure is the default!
+trap "_cleanup; exit \$status" 0 1 2 3 15
+
+[ -x qt/qmc_group/qmc_group ] || _notrun "qmc_group not built or installed"
 rm -f $seq.full
-trap "_cleanup; rm -f $tmp.*; exit \$status" 0 1 2 3 15
 
 _filter1()
 {
@@ -69,9 +71,9 @@ _filter2()
     | uniq -c \
     | sed -e 's/  */ /g'
 
-    echo "*** Transactions ***" >> $seq.full
-    echo >> $seq.full
-    cat $tmp.filtered >> $seq.full
+    echo "*** Transactions ***" >> $here/$seq.full
+    echo >> $here/$seq.full
+    cat $tmp.filtered >> $here/$seq.full
 }
 
 # real QA test starts here
diff --git a/src/qa/1020 b/src/qa/1020
--- a/src/qa/1020
+++ b/src/qa/1020
@@ -4,24 +4,25 @@
 #
 seq=`basename $0`
 echo "QA output created by $seq"
-. ./common.qt
 
-[ -x qt/qmc_dynamic/qmc_dynamic ] || _notrun "qmc_dynamic not built or installed"
+status=1	# failure is the default!
+. ./common.qt
 
 _cleanup()
 {
     if [ ! -f $tmp.done ]
     then
 	cd $here/pmdas/dynamic
-	$sudo ./Remove >>$here/src/$seq.full
+	$sudo ./Remove >>$here/$seq.full
 	cd $here
 	touch $tmp.done
     fi
+    _cleanup_qt
 }
+trap "_cleanup; exit \$status" 0 1 2 3 15
 
-status=1	# failure is the default!
+[ -x qt/qmc_dynamic/qmc_dynamic ] || _notrun "qmc_dynamic not built or installed"
 rm -f $seq.full
-trap "_cleanup; rm -f $tmp.*; exit \$status" 0 1 2 3 15
 
 _filter2()
 {
@@ -51,9 +52,9 @@ _filter2()
     | uniq -c \
     | sed -e 's/  */ /g'
 
-    echo "*** Transactions ***" > $seq.full
-    echo >> $seq.full
-    cat $tmp.filtered >> $seq.full
+    echo "*** Transactions ***" > $here/$seq.full
+    echo >> $here/$seq.full
+    cat $tmp.filtered >> $here/$seq.full
 }
 
 # real QA test starts here
diff --git a/src/qa/338 b/src/qa/338
--- a/src/qa/338
+++ b/src/qa/338
@@ -18,26 +18,51 @@ echo "QA output created by $seq"
 . ./common.filter
 . ./common.check
 
+# This test is not stable in the vicinity of a timezone change, e.g.
+# daylight saving or summer time transitions.
+# Don't run if this happened in the last 2 days.
+#
+now_hr=`pmdate '%H'`
+now_hr_2=`pmdate -2d '%H'`
+if [ "$now_hr" != "$now_hr_2" ]
+then
+    _notrun "timezone change? now = ${now_hr}H:??M, 2 days ago = ${now_hr_2}H:??M"
+    # NOTREACHED
+fi
+
 _filter()
 {
+    if fmt --help 2>&1 | grep '.-w, ' >/dev/null
+    then
+	# GNU-style fmt(1)
+	cmd="fmt -w 76"
+    elif fmt --help 2>&1 | grep '.-m ' >/dev/null
+    then
+	# NetBSD's version of fmt is different (may apply to other variants) ...
+	cmd="fmt -m 76"
+    else
+	echo "Warning: no clue how to set max line length for fmt(1)"
+	cmd="fmt"
+    fi
     tee -a $seq.full \
     | $PCP_AWK_PROG '
-/^Archive files older than/	{ eatlines=1; longone="   "; print; next; }
+BEGIN				{ cmd = "'"`echo $cmd`"'" }
+/^Archive files older than/	{ eatlines=1; longone="   "; print; next }
 eatlines			{ if ( match ($0, "^    ") ) {
 				    for ( i=1; i <=NF; i++ ) {
-					longone = sprintf ("%s %s",longone,$i);
+					longone = sprintf ("%s %s",longone,$i)
 				    }
 				  } else {
-				    print longone | "fmt -76";
-				    close ("fmt -76"); 
-				    longone = ""; eatlines = 0; 
-				    print;  
+				    print longone | cmd
+				    close (cmd)
+				    longone = ""; eatlines = 0 
+				    print  
 				  }
-				  next;
+				  next
 				}
 END				{ if ( eatlines ) {
-				    print longone | "fmt -76";
-				    close ("fmt -76"); 
+				    print longone | cmd
+				    close (cmd)
 				  }
 				}
 				{ print }' \
@@ -56,14 +81,19 @@ END				{ if ( eatlines ) {
     | _filter_cron_scripts
 }
 
-status=1	# failure is the default!
-trap "cd $here; $sudo rm -rf $tmp; $sudo mv $PCP_LOG_DIR/NOTICES.$$ $PCP_LOG_DIR/NOTICES; exit \$status" 0 1 2 3 15
-$sudo rm -rf $tmp
+_cleanup()
+{
+    cd $here
+    $sudo rm -f $tmp.*
+    $sudo rm -rf $tmp
+    $sudo mv $PCP_LOG_DIR/NOTICES.$$ $PCP_LOG_DIR/NOTICES
+}
 
-# real QA test starts here
+status=1	# failure is the default!
+trap "_cleanup; exit \$status" 0 1 2 3 15
+$sudo rm -rf $tmp $tmp.*
 
 # take explicit control of the umask
-#
 umask 022
 
 $sudo mv $PCP_LOG_DIR/NOTICES $PCP_LOG_DIR/NOTICES.$$
@@ -98,9 +128,9 @@ do
 
 	for ext in 0 index meta
 	do
-	    cp src/arch_a.$ext $tmp/$namea.$ext
+	    cp archives/arch_a.$ext $tmp/$namea.$ext
 	    touch -t $stampa $tmp/$namea.$ext
-	    cp src/arch_b.$ext $tmp/$nameb.$ext
+	    cp archives/arch_b.$ext $tmp/$nameb.$ext
 	    touch -t $stampb $tmp/$nameb.$ext
 	done
     done
@@ -118,8 +148,9 @@ LOCALHOSTNAME	n   n	'"$tmp"'	./config'
     echo
     echo "=== [${verbose+verbose}] regular show ==="
     echo "=== [${verbose+verbose}] regular show ===" >>$seq.full
-    $sudo $PCP_BINADM_DIR/pmlogger_daily -o -c $tmp/control -k 3 $verbose 2>&1 \
-    | _filter
+    $sudo $PCP_BINADM_DIR/pmlogger_daily -o -c $tmp/control -k 3 $verbose -l $tmp.log
+
+    $sudo cat $tmp.log | _filter
     ls -lt $tmp >>$seq.full
     ls $tmp | sed -f $tmp/sed | tee -a $seq.full | LC_COLLATE=POSIX sort
 
@@ -130,8 +161,8 @@ LOCALHOSTNAME	n   n	'"$tmp"'	./config'
     do
 	mv $tmp/$yesterday.$ext $tmp/save.$ext
     done
-    $sudo $PCP_BINADM_DIR/pmlogger_daily -o -c $tmp/control -k 2 $verbose 2>&1 \
-    | _filter
+    $sudo $PCP_BINADM_DIR/pmlogger_daily -o -c $tmp/control -k 2 $verbose -l $tmp.log
+    $sudo cat $tmp.log | _filter
     ls -lt $tmp >>$seq.full
     ls $tmp | sed -f $tmp/sed | tee -a $seq.full | LC_COLLATE=POSIX sort
 
@@ -140,11 +171,11 @@ LOCALHOSTNAME	n   n	'"$tmp"'	./config'
     echo "=== [${verbose+verbose}] error, output already exists ===" >>$seq.full
     for ext in 0 index meta
     do
-	cp src/arch_a.$ext $tmp/$yesterday.17.18.$ext
+	cp archives/arch_a.$ext $tmp/$yesterday.17.18.$ext
 	mv $tmp/save.$ext $tmp/$yesterday.$ext
     done
-    $sudo $PCP_BINADM_DIR/pmlogger_daily -o -c $tmp/control -k 2 $verbose 2>&1 \
-    | _filter
+    $sudo $PCP_BINADM_DIR/pmlogger_daily -o -c $tmp/control -k 2 $verbose -l $tmp.log
+    $sudo cat $tmp.log | _filter
     ls -lt $tmp >>$seq.full
     ls $tmp | sed -f $tmp/sed | tee -a $seq.full | LC_COLLATE=POSIX sort
 
diff --git a/src/qa/519 b/src/qa/519
--- a/src/qa/519
+++ b/src/qa/519
@@ -22,7 +22,6 @@ echo "QA output created by $seq"
 . ./common.product
 . ./common.filter
 . ./common.check
-. ./localconfig
 
 rm -f $seq.out
 case $PCP_PLATFORM
@@ -53,6 +52,7 @@ _filter()
 	-e 's/[A-Z][a-z][a-z] *[0-9][0-9]* [0-9][0-9]:[0-9][0-9]:[0-9][0-9]/TIMESTAMP/' \
 	-e 's/20[0-9][0-9]-[01][0-9]-[0-3][0-9]T[0-2][0-9]:[0-5][0-9]:[0-5][0-9]\.[0-9]*/TIMESTAMP/' \
 	-e 's/STAMP[-+][0-1][0-9]:[0-5][0-9]/STAMP/' \
+	-e "s/`hostname`/HOST/" \
 	-e "s/`hostname | sed -e 's/\..*//'`/HOST/" \
 	-e 's/[0-9][A-Z]:HOST/HOST/' \
 	-e 's/\(pmie[([]\)[0-9][0-9]*/\1PID/' \
@@ -76,6 +76,8 @@ then
     _notrun "Cannot find second remote host running pmcd"
     exit
 fi
+echo "other1=$other1" >>$here/$seq.full
+echo "other2=$other2" >>$here/$seq.full
 
 # real QA test starts here
 $sudo rm -f core* $seq.core*
@@ -94,38 +96,74 @@ some_host (
 
 End-of-File
 
+# hostnames $other1 and $other2 may contain domain name components,
+# but pmie may just report the hostname
+#
+o1=`echo $other1 | sed -e 's/\..*//'`
+o2=`echo $other2 | sed -e 's/\..*//'`
 echo "pmie output ..."
 sed <$tmp.out \
     -e "/^$other1:/d" \
-    -e "/^$other2:/d"
-grep "^$other1:" <$tmp.out >/dev/null && echo "... at least one line for other1 host"
-grep "^$other2:" <$tmp.out >/dev/null && echo "... at least one line for other2 host"
+    -e "/^$o1:/d" \
+    -e "/^$other2:/d" \
+    -e "/^$o2:/d" \
+#
+egrep "^($other1|$o1):" <$tmp.out >/dev/null && echo "... at least one line for other1 host"
+egrep "^($other2|$o2)*:" <$tmp.out >/dev/null && echo "... at least one line for other2 host"
 
 echo
 echo "pmie stderr ..."
 _filter <$tmp.err
 
+# may be using journalctl, and so no syslog in the file system
+#
+if `which journalctl >/dev/null 2>&1`
+then
+    echo "Using journalctl ..." >>$seq.full
+    have_journalctl=true
+else
+    have_journalctl=false
+    SYSLOG=''
+    for f in /var/adm/SYSLOG /var/log/daemon.log /var/log/messages /var/log/syslog /var/log/system.log
+    do
+	if [ -f $f ]
+	then
+	    SYSLOG=$f
+	    break
+	fi
+    done
+    if [ -z "$SYSLOG" ]
+    then
+	echo "Arrgh! Cannot find your syslog file"
+	exit 1
+    fi
+fi
+
 echo
 echo "SYSLOG ..."
-SYSLOG=''
-for f in /var/adm/SYSLOG /var/log/daemon.log /var/log/messages /var/log/syslog /var/log/system.log
-do
-    if [ -f $f ]
-    then
-	SYSLOG=$f
-	break
-    fi
-done
-if [ -z "$SYSLOG" ]
+
+if $have_journalctl
 then
-    echo "Arrgh! Cannot find your syslog file"
-    exit 1
+    # be careful ... --boot not supported in all versions, -l not
+    # supported in all versions
+    $sudo journalctl -b --full | tail -100 >$tmp.syslog
+else
+    $sudo tail -100 $SYSLOG >$tmp.syslog
 fi
- 
-$sudo tail -100 $SYSLOG \
-| sed -n '/PCP QA '"$seq"' - please ignore/s/\.\.\..*/.../p' \
+
+sed <$tmp.syslog -n '/PCP QA '"$seq"' - please ignore/s/\.\.\..*/.../p' \
 | _filter \
 | sort -u
+
+echo >>$seq.full
+if $have_journalctl
+then
+    echo "=== tail journalctl -b --full ===" >>$seq.full
+else
+    echo "=== tail SYSLOG ($SYSLOG) ===" >>$seq.full
+fi
+echo "`wc -l <$tmp.syslog | sed -e 's/ //g'` lines ... expect 100" >>$seq.full
+cat $tmp.syslog >>$seq.full
 
 _check_core
 
diff --git a/src/qa/583 b/src/qa/583
--- a/src/qa/583
+++ b/src/qa/583
@@ -25,6 +25,8 @@ then
     echo "Cannot find second remote host running pmcd" >$seq.notrun
     exit
 fi
+echo "other1=$other1" >>$here/$seq.full
+echo "other2=$other2" >>$here/$seq.full
 
 case $PCP_PLATFORM
 in
@@ -50,6 +52,7 @@ _filter()
 	-e 's/[A-Z][a-z][a-z] *[0-9][0-9]* [0-9][0-9]:[0-9][0-9]:[0-9][0-9]/TIMESTAMP/' \
 	-e 's/20[0-9][0-9]-[01][0-9]-[0-3][0-9]T[0-2][0-9]:[0-5][0-9]:[0-5][0-9]\.[0-9]*/TIMESTAMP/' \
 	-e 's/STAMP[-+][0-1][0-9]:[0-5][0-9]/STAMP/' \
+	-e "s/`hostname`/HOST/" \
 	-e "s/`hostname | sed -e 's/\..*//'` /HOST /" \
 	-e 's/[0-9][A-Z]:HOST/HOST/' \
 	-e 's/\(pmie[([]\)[0-9][0-9]*/\1PID/'
@@ -64,19 +67,28 @@ PMCD_REQUEST_TIMEOUT=60
 PMCD_RECONNECT_TIMEOUT=1,2
 export PMCD_CONNECT_TIMEOUT PMCD_REQUEST_TIMEOUT PMCD_RECONNECT_TIMEOUT
 
-SYSLOG=''
-for f in /var/adm/SYSLOG /var/log/daemon.log /var/log/messages /var/log/syslog /var/log/system.log
-do
-    if [ -f $f ]
-    then
-	SYSLOG=$f
-	break
-    fi
-done
-if [ -z "$SYSLOG" ]
+# may be using journalctl, and so no syslog in the file system
+#
+if `which journalctl >/dev/null 2>&1`
 then
-    echo "Arrgh! Cannot find your syslog file"
-    exit 1
+    echo "Using journalctl ..." >>$seq.full
+    have_journalctl=true
+else
+    have_journalctl=false
+    SYSLOG=''
+    for f in /var/adm/SYSLOG /var/log/daemon.log /var/log/messages /var/log/syslog /var/log/system.log
+    do
+	if [ -f $f ]
+	then
+	    SYSLOG=$f
+	    break
+	fi
+    done
+    if [ -z "$SYSLOG" ]
+    then
+	echo "Arrgh! Cannot find your syslog file"
+	exit 1
+    fi
 fi
 
 # real QA test starts here
@@ -117,14 +129,30 @@ sleep 15
 $signal -s TERM $pmie_pid
 wait
 
+# hostnames $other1 and $other2 may contain domain name components,
+# but pmie may just report the hostname
+#
+o1=`echo $other1 | sed -e 's/\..*//'`
+o2=`echo $other2 | sed -e 's/\..*//'`
+local=`hostname`
+l=`echo $local | sed -e 's/\..*//'`
+echo "o1=$o1" >>$here/$seq.full
+echo "o2=$o2" >>$here/$seq.full
+echo "local=$local" >>$here/$seq.full
+echo "l=$l" >>$here/$seq.full
 echo "pmie output ..."
 sed <$tmp.out \
     -e "/ $other1:/d" \
+    -e "/ $o1:/d" \
     -e "/ $other2:/d" \
-    -e '/ localhost:/d'
-grep " $other1:" <$tmp.out >/dev/null && echo "... at least one line for other1 host"
-grep " $other2:" <$tmp.out >/dev/null && echo "... at least one line for other2 host"
-grep ' localhost:' <$tmp.out >/dev/null && echo "... at least one line for localhost"
+    -e "/ $o2:/d" \
+    -e '/ localhost:/d' \
+    -e "/ $local:/d" \
+    -e "/ $l:/d" \
+#
+egrep " ($other1|$o1):" <$tmp.out >/dev/null && echo "... at least one line for other1 host"
+egrep " ($other2|$o2):" <$tmp.out >/dev/null && echo "... at least one line for other2 host"
+egrep " (localhost|$local|$l):" <$tmp.out >/dev/null && echo "... at least one line for localhost"
 
 echo
 echo "pmie stderr ..."
@@ -139,14 +167,26 @@ cat $tmp.err >>$seq.full
 
 echo
 echo "SYSLOG ..."
-$sudo tail -100 $SYSLOG >$tmp.tmp
-sed <$tmp.tmp -n '/PCP QA '"$seq"' - please ignore/s/\.\.\..*/.../p' \
+if $have_journalctl
+then
+    # be careful ... --boot not supported in all versions, -l not
+    # supported in all versions
+    $sudo journalctl -b --full | tail -100 >$tmp.syslog
+else
+    $sudo tail -100 $SYSLOG >$tmp.syslog
+fi
+sed <$tmp.syslog -n '/PCP QA '"$seq"' - please ignore/s/\.\.\..*/.../p' \
 | _filter \
 | LC_COLLATE=POSIX sort -u
 
 echo >>$seq.full
-echo "=== tail SYSLOG ($SYSLOG) ===" >>$seq.full
-cat $tmp.tmp >>$seq.full
+if $have_journalctl
+then
+    echo "=== tail journalctl -b --full ===" >>$seq.full
+else
+    echo "=== tail SYSLOG ($SYSLOG) ===" >>$seq.full
+fi
+cat $tmp.syslog >>$seq.full
 
 _check_core
 
diff --git a/src/qa/admin/pcp-daily b/src/qa/admin/pcp-daily
--- a/src/qa/admin/pcp-daily
+++ b/src/qa/admin/pcp-daily
@@ -393,18 +393,24 @@ _script_qa()
     cat <<End-of-File
 rm -f *.out.bad
 ./changeversion >/dev/null 2>&1
-if ./check -l $check_what >>\$HOME/daily.log 2>&1
-then
-    echo "Info: QA $what" | tee -a \$HOME/daily.log
-else
-    echo "Error: QA $what failed!" | tee -a \$HOME/daily.log
-    sed -e '/^    [0-9 ]*\$/d' <check.log \
-    | awk '
+echo "Info: QA $check_what starting"
+./check -l $check_what >>\$HOME/daily.log 2>&1
+sts=\$?
+# get last block from check.log ... then get the summary on
+# stdout (not needed in the daily.log, already there)
+sed -e '/^    [0-9 ]*\$/d' <check.log \
+| awk '
 NF == 0	{ txt = ""; next }
 	{ if (txt == "") txt = \$0
 	  else txt = txt "\n" \$0
 	}
-END	{ print txt }' | tee -a \$HOME/daily.log
+END	{ print txt }' \
+| egrep '^(Failures:|Failed|Passed)'
+if [ "\$sts" = 0 ]
+then
+    echo "Info: QA $check_what done" | tee -a \$HOME/daily.log
+else
+    echo "Error: QA $what failed!" | tee -a \$HOME/daily.log
 fi
 End-of-File
 }
@@ -457,7 +463,7 @@ list_1="vm03 vm01 vm04 vm07 vm12 vm14 vm16 vm18 vm20 vm22 vm24"
 list_2="fuji grundy vm02 vm00 vm05 vm11 vm15 vm19 vm21 vm23"
 
 args="$*"
-pcp_branch=dev
+pcp_branch=master
 pcp_tree=pcp
 cflag=false
 fflag=false
@@ -610,7 +616,10 @@ in
 	echo "grundy.sgi.com" >>$tmp.domains
 	# and open up the X server
 	#
-	DISPLAY=localhost:0.0 xhost + >/dev/null
+	# Ubuntu up to 15.04
+	#DISPLAY=localhost:0.0 xhost + >/dev/null
+	# Ubuntu 15.10
+	DISPLAY=:0.0 xhost + >/dev/null
 	;;
 esac
 
@@ -776,8 +785,8 @@ End-of-File
 		#
 		[ X"$what" = Xall ] && check_what='$check_what -x remote'
 		;;
-	    vm06|vm10)
-		# Only -g sanity at this stage for FreeBSD
+	    vm06|vm10|vm09)
+		# Only -g sanity at this stage for FreeBSD or NetBSD
 		#
 		[ X"$what" = Xall ] && check_what='-g sanity'
 		;;
@@ -883,8 +892,8 @@ End-of-File
 		    echo "Warning: Already shutdown"
 		fi
 	    else
-		ssh -t -q $host sudo poweroff -f </dev/null >/dev/null 2>&1 &
-		sleep 20
+		ssh -t -q $host "sync; sleep 2; sync; ( sudo poweroff || sudo halt )" -f </dev/null >/dev/null 2>&1 &
+		sleep 60
 		sudo virsh shutdown $domain >/dev/null 2>&1
 		sleep 10
 		# seems a bit harsh, but we've given you two chances to
diff --git a/src/src/pmie/rc_pmie b/src/src/pmie/rc_pmie
--- a/src/src/pmie/rc_pmie
+++ b/src/src/pmie/rc_pmie
@@ -1,6 +1,6 @@
 #!/bin/sh
 #
-# Copyright (c) 2012 Red Hat.
+# Copyright (c) 2012-2015 Red Hat.
 # Copyright (c) 2000 Silicon Graphics, Inc.  All Rights Reserved.
 # 
 # This program is free software; you can redistribute it and/or modify it
@@ -38,18 +38,6 @@ PMIECTRL=$PCP_PMIECONTROL_PATH
 rcprog=$PCP_DIR/etc/init.d/pmie
 pmprog=$PCP_RC_DIR/pmie
 prog=$PCP_RC_DIR/`basename $0`
-
-# search for your mail agent of choice ...
-#
-MAIL=''
-for try in Mail mail email
-do
-    if which $try >/dev/null 2>&1
-    then
-	MAIL=$try
-	break
-    fi
-done
 
 tmp=`mktemp -d /var/tmp/pcp.XXXXXXXXX` || exit 1
 status=1
@@ -102,13 +90,13 @@ _reboot_setup()
     fi
 }
 
-# Note: _start_pmie is running in the background, in parallel with
-# the rest of the script.  It might complete well after the caller
-# so tmpfile handling is especially problematic.  Goal is to speed
-# bootup by starting potentially slow (remote monitoring) processes
-# in the background.
+# Note: _start_pmcheck() runs in the background, in parallel with the rest
+# of the script (except in a container environment). It might complete well
+# after the caller so tmpfile handling is especially problematic.  The goal
+# is to speed bootup by starting potentially slow (remote monitoring) pmie
+# processes in the background.
 #
-_start_pmie()
+_start_pmcheck()
 {
     bgstatus=0
     bgtmp=`mktemp -d /var/tmp/pcp.XXXXXXXXX` || exit 1
@@ -123,27 +111,74 @@ _start_pmie()
 	bgstatus=$?
 	if [ -s $bgtmp/pmie ]
 	then
-	    $PCP_BINADM_DIR/pmpost "pmie_check start failed in $prog, mailing output to root"
-	    if [ ! -z "$MAIL" ]
-	    then
-		$MAIL -s "pmie_check start failed in $prog" root <$bgtmp/pmie >/dev/null 2>&1
-	    else
-		echo "$prog: pmie_check start failed ..."
-		cat $bgtmp/pmie
-	    fi
+	    logfile=$PCP_LOG_DIR/pmie/pmie_check.log
+	    mv -f $bgtmp/pmie $logfile
+
+	    message="pmie_check start failed in $prog, see $logfile"
+	    $PCP_SYSLOG_PROG -p daemon.warning "$message"
+	    $PCP_BINADM_DIR/pmpost "$message"
 	fi
     else
 	bgstatus=$?
-	$PCP_BINADM_DIR/pmpost "pmcd_wait failed in $prog: exit status: $bgstatus" 
-	if [ ! -z "$MAIL" ]
-	then
-	    echo "pmcd_wait: exit status: $bgstatus" | $MAIL -s "pmcd_wait failed in $prog" root
-	else
-	    echo "$prog: pmcd_wait failed ..."
-	    echo "pmcd_wait: exit status: $bgstatus"
-	fi
+	message="pmcd_wait failed in $prog: exit status: $bgstatus" 
+	$PCP_SYSLOG_PROG -p daemon.warning "$message"
+	$PCP_BINADM_DIR/pmpost "$message"
     fi
-    exit $bgstatus	# co-process is now complete
+    exit $bgstatus # co-process is now complete
+}
+
+_start_pmie()
+{
+    if which pmie_check >/dev/null 2>&1
+    then
+	# pmie_check uses $PMIECTRL to start everything that is needed
+	if [ ! -f $PMIECTRL ]
+	then
+	    echo "$prog:"'
+Error: PCP inference engine control file '$PMIECTRL'
+       is missing!  Cannot start any Performance Co-Pilot inference engine(s).'
+	    # failure
+	    false
+	else
+	    $ECHO $PCP_ECHO_N "Starting pmie ..." "$PCP_ECHO_C"
+
+	    # run as a co-process
+	    _start_pmcheck &
+
+	    # Container environment
+	    if [ -n "$PCP_CONTAINER_IMAGE" ]
+	    then
+		# Set up the host crontab for pmie_{check,daily}.
+		# This needs to be robust for when the container isn't running
+		# so that a failing crontab entry doesn't spam the host logs.
+		cronjob=/etc/cron.d/pcp-pmie-docker
+		if [ ! -f $cronjob ]
+		then
+		    cp $PCP_VAR_DIR/config/pmie/crontab.docker $cronjob
+		    $PCP_BINADM_DIR/pmpost "pmie script installed $cronjob"
+		fi
+
+		# In a container, pmie_check cannot run indefinitely -
+		# if it did then the pmpause signal handler would reap the
+		# pmie_check child and exit.
+		wait
+
+		# finally, stop here when running as a container
+		exec $PCP_BINADM_DIR/pmpause
+	    fi
+
+            # success
+            true
+	fi
+    else
+        echo "$prog:"'
+Warning: Performance Co-Pilot installation is incomplete (at least the
+         script "pmie_check" is missing) and the PCP inference engine(s)
+         cannot be started.'
+        # failure
+        false
+    fi
+    $RC_STATUS -v
 }
 
 _shutdown()
@@ -151,7 +186,7 @@ _shutdown()
     _get_pids_by_name pmie >$tmp/pmies 2>&1
     if [ ! -s $tmp/pmies ]
     then
-	[ "$1" = verbose ] && echo "$pmprog: PMIE not running"
+	[ "$1" = verbose ] && echo "$pmprog: pmie not running"
 	return 0
     fi
 
@@ -161,14 +196,12 @@ _shutdown()
     pmie_check -s >$tmp/pmie 2>&1
     if [ -s $tmp/pmie ]
     then
-	$PCP_BINADM_DIR/pmpost "pmie_check stop failed in $prog, mailing output to root"
-	if [ ! -z "$MAIL" ]
-	then
-	    $MAIL -s "pmie_check stop failed in $prog" root <$tmp/pmie
-	else
-	    echo "$prog: pmie_check stop failed ..."
-	    cat $tmp/pmie
-	fi
+	logfile=$PCP_LOG_DIR/pmie/pmie_check.log
+	mv -f $tmp/pmie $logfile
+
+	message="pmie_check stop failed in $prog, see $logfile"
+	$PCP_SYSLOG_PROG -p daemon.warning "$message"
+	$PCP_BINADM_DIR/pmpost "$message"
     fi
 
     if [ "$1" = quietly ]
@@ -222,26 +255,17 @@ case "$1" in
 
 	if which pmie >/dev/null 2>&1
 	then
+	    # issue a warning if there's no chkconfig/crontab support
 	    if is_chkconfig_on pmie
 	    then
-		if which pmie_check >/dev/null 2>&1
-		then
-		    if [ ! -f $PMIECTRL ]
-		    then
-			echo "$prog:"'
-Error: PCP inference engine control file '$PMIECTRL'
-       is missing!  Cannot start any Performance Co-Pilot inference engine(s).'
-		    else
-			$ECHO $PCP_ECHO_N "Starting pmie ..." "$PCP_ECHO_C"
-			_start_pmie &
-			$RC_STATUS -v
-		    fi
-		fi
+		:
 	    elif [ "$0" = "$pmprog" -o "$0" = "$rcprog" ]
 	    then
-		echo "$prog: Warning: Performance Co-Pilot Inference Engine (pmie) is disabled."
+		echo "$prog: Warning: Performance Co-Pilot Inference Engine (pmie) not permanently enabled."
 		chkconfig_on_msg pmie
 	    fi
+
+	    _start_pmie
 	fi
 	status=0
         ;;
@@ -273,6 +297,7 @@ Error: PCP inference engine control file '$PMIECTRL'
         fi
         ;;
   *)
+	[ -n "$PCP_CONTAINER_IMAGE" ] && exec "$@"
 	_usage
         ;;
 esac
diff --git a/src/src/pmlogger/rc_pmlogger b/src/src/pmlogger/rc_pmlogger
--- a/src/src/pmlogger/rc_pmlogger
+++ b/src/src/pmlogger/rc_pmlogger
@@ -1,6 +1,6 @@
 #!/bin/sh
 #
-# Copyright (c) 2012 Red Hat.
+# Copyright (c) 2012-2015 Red Hat.
 # Copyright (c) 2000-2008 Silicon Graphics, Inc.  All Rights Reserved.
 # 
 # This program is free software; you can redistribute it and/or modify it
@@ -42,18 +42,6 @@ rcprog=$PCP_DIR/etc/init.d/pmlogger
 pmprog=$PCP_RC_DIR/pmlogger
 prog=$PCP_RC_DIR/`basename $0`
 
-# search for your mail agent of choice ...
-#
-MAIL=''
-for try in Mail mail email
-do
-    if which $try >/dev/null 2>&1
-    then
-	MAIL=$try
-	break
-    fi
-done
-
 tmp=`mktemp -d /var/tmp/pcp.XXXXXXXXX` || exit 1
 status=1
 trap "rm -rf $tmp; exit \$status" 0 1 2 3 15
@@ -87,10 +75,10 @@ in
 	;;
 esac
 
-# Note: _start_pmcheck() runs in the background, in parallel with
-# the rest of the script.  It might complete well after the caller
-# so tmpfile handling is especially problematic.  Goal is to speed
-# bootup by starting potentially slow (remote monitoring) pmlogger
+# Note: _start_pmcheck() runs in the background, in parallel with the rest
+# of the script (except in a container environment). It might complete well
+# after the caller so tmpfile handling is especially problematic.  Goal is
+# to speed bootup by starting potentially slow (remote monitoring) pmlogger
 # processes in the background.
 #
 _start_pmcheck()
@@ -103,16 +91,14 @@ _start_pmcheck()
     bgstatus=$?
     if [ -s $bgtmp/pmcheck ]
     then
-	$PCP_BINADM_DIR/pmpost "pmlogger_check failed in $prog, mailing output to root"
-	if [ ! -z "$MAIL" ]
-	then
-	    $MAIL -s "pmlogger_check failed in $prog" root <$bgtmp/pmcheck
-	else
-	    echo "$prog: pmlogger_check failed ..."
-	    cat $bgtmp/pmcheck
-	fi
+	logfile="$PCP_LOG_DIR/pmlogger/pmlogger_check.log"
+	mv -f $bgtmp/pmcheck $logfile
+
+	message="pmlogger_check failed in $prog, see $logfile"
+	$PCP_SYSLOG_PROG -p daemon.warning "$message"
+	$PCP_BINADM_DIR/pmpost "$message"
     fi
-    exit $bgstatus	# co-process is now complete
+    exit $bgstatus # co-process is now complete
 }
 
 _start_pmlogger()
@@ -129,12 +115,37 @@ Error: PCP archive logger control file '$PMLOGCTRL'
 	    # failure
 	    false
 	else
-	    # really start the pmlogger instances based on the control file.
-	    # done in the background to avoid delaying the init script,
-	    # failures are notified by mail
+	    # Really start the pmlogger instances based on the control file.
+	    # Done in the background to avoid delaying the init script,
+	    # failure notification is external (syslog, log files).
 	    #
 	    $ECHO $PCP_ECHO_N "Starting pmlogger ..." "$PCP_ECHO_C"
+
+	    # run as a co-process
 	    _start_pmcheck &
+
+	    # Container environment
+	    if [ -n "$PCP_CONTAINER_IMAGE" ]
+	    then
+		# Set up the host crontab for pmlogger_{check,daily}.
+		# This needs to be robust for when the container isn't running
+		# so that a failing crontab entry doesn't spam the host logs.
+		cronjob=/etc/cron.d/pcp-pmlogger-docker
+		if [ ! -f $cronjob ]
+		then
+		    cp $PCP_VAR_DIR/config/pmlogger/crontab.docker $cronjob
+		    $PCP_BINADM_DIR/pmpost "pmlogger script installed $cronjob"
+		fi
+
+		# In a container, pmlogger_check cannot run indefinitely -
+		# if it did then the pmpause signal handler would reap the
+		# pmlogger_check child and exit.
+		wait
+
+		# finally, stop here when running as a container
+		exec $PCP_BINADM_DIR/pmpause
+	    fi
+
 	    # success
 	    true
 	fi
@@ -259,19 +270,21 @@ case "$1" in
 	_shutdown quietly
 
 	# messages should go to stderr, not the GUI notifiers
-	#
 	unset PCP_STDERR
 
 	if [ -x $PMLOGGER ]
 	then
+	    # issue a warning if there's no chkconfig/crontab support
 	    if is_chkconfig_on pmlogger
 	    then
-		_start_pmlogger
+		:
 	    elif [ "$0" = "$pmprog" -o "$0" = "$rcprog" ]
 	    then
-		echo "$prog: Warning: Performance Co-Pilot archive logger(s) are disabled."
+		echo "$prog: Warning: Performance Co-Pilot archive logger(s) not permanently enabled."
 		chkconfig_on_msg pmlogger
 	    fi
+
+	    _start_pmlogger
 	fi
 
 	status=0
@@ -305,6 +318,7 @@ case "$1" in
 	;;
 
   *)
+	[ -n "$PCP_CONTAINER_IMAGE" ] && exec "$@"
 	_usage
         ;;
 esac
