els-ASAP auto commit file/tag pcp-3.12.2-5.el7.src.rpm

diff --git a/src/qa/1100 b/src/qa/1100
--- a/src/qa/1100
+++ b/src/qa/1100
@@ -16,6 +16,23 @@ status=1       # failure is the default!
 $sudo rm -rf $tmp $tmp.* $seq.full
 trap "cd $here; rm -rf $tmp.*; exit \$status" 0 1 2 3 15
 
+# these may not be available if needed modules missing
+#
+skip_pcp2elasticsearch=false
+$python -c "from elasticsearch import Elasticsearch" >/dev/null 2>&1
+[ $? -eq 0 ] || skip_pcp2elasticsearch=true
+skip_pcp2xlsx=false
+$python -c "import xlsxwriter" >/dev/null 2>&1
+[ $? -eq 0 ] || skip_pcp2xlsx=true
+skip_pmrep=false
+$python -c "from collections import OrderedDict" >/dev/null 2>&1
+[ $? -eq 0 ] || skip_pmrep=true
+
+# sources
+share_dir=`dirname $PCP_SHARE_DIR`
+bash_comp=${share_dir}/bash-completion/completions/pcp
+zsh_comp=${share_dir}/zsh/site-functions/_pcp
+
 export PCP_STDERR=$tmp.err
 echo "DISPLAY=$DISPLAY" >>$here/$seq.full
 echo "PCPQA_CLOSE_X_SERVER=$PCPQA_CLOSE_X_SERVER" >>$here/$seq.full
@@ -25,82 +42,15 @@ then
     echo "DISPLAY=$DISPLAY" >>$here/$seq.full
 fi
 
-# these may not be available if needed modules missing
-#
-skip_pcp2elasticsearch=false
-$python -c "import requests" >/dev/null 2>&1
-[ $? -eq 0 ] || skip_pcp2elasticsearch=true
-skip_pcp2xlsx=false
-$python -c "import openpyxl" >/dev/null 2>&1
-[ $? -eq 0 ] || skip_pcp2xlsx=true
-skip_pmrep=false
-$python -c "from collections import OrderedDict" >/dev/null 2>&1
-if [ $? -ne 0 ]; then
-    skip_pcp2elasticsearch=true
-    skip_pcp2graphite=true
-    skip_pcp2influxdb=true
-    skip_pcp2json=true
-    skip_pcp2spark=true
-    skip_pcp2xlsx=true
-    skip_pcp2xml=true
-    skip_pcp2zabbix=true
-    skip_pmrep=true
-fi
-
-# these may not be available if X11 display is missing
-#
-skip_pmchart=false
-which xdpyinfo >/dev/null 2>&1
-if [ $? -eq 0 ]
-then
-    xdpyinfo >/dev/null 2>&1
-    [ $? -eq 0 ] || skip_pmchart=true
-else
-    skip_pmchart=true
-fi
-
-# these may not be installed on all platforms
-skip_pmdumptext=false
-which pmchart > /dev/null 2>&1
-if [ $? -ne 0 ]
-then
-    skip_pmchart=true
-fi
-which pmdumptext > /dev/null 2>&1
-if [ $? -ne 0 ]
-then
-    skip_pmdumptext=true
-fi
-skip_pmseries=false
-which pmseries > /dev/null 2>&1
-if [ $? -ne 0 ]
-then
-    skip_pmseries=true
-fi
-
-# sources
-share_dir=`dirname $PCP_SHARE_DIR`
-bash_comp=${share_dir}/bash-completion/completions/pcp
-zsh_comp=${share_dir}/zsh/site-functions/_pcp
-
 # functions
 _check_completion_bash()
 {
-  cmds="$(grep '  pcp2.*)' $bash_comp | tr -d ')')"
+  cmds="$(grep '  pcp2.*)' $bash_comp | tr -d ')'))"
   cmds="$cmds $(grep '  pm.*)' $bash_comp | tr -d ')')"
   for cmd in $cmds; do
     $skip_pcp2elasticsearch && [ "$cmd" = pcp2elasticsearch ] && continue
-    $skip_pcp2graphite && [ "$cmd" = pcp2graphite ] && continue
-    $skip_pcp2influxdb && [ "$cmd" = pcp2influxdb ] && continue
-    $skip_pcp2json && [ "$cmd" = pcp2json ] && continue
-    $skip_pcp2spark && [ "$cmd" = pcp2spark ] && continue
     $skip_pcp2xlsx && [ "$cmd" = pcp2xlsx ] && continue
-    $skip_pcp2xml && [ "$cmd" = pcp2xml ] && continue
-    $skip_pcp2zabbix && [ "$cmd" = pcp2zabbix ] && continue
-    $skip_pmchart && [ "$cmd" = pmchart ] && continue
-    $skip_pmdumptext && [ "$cmd" = pmdumptext ] && continue
     $skip_pmrep && [ "$cmd" = pmrep ] && continue
-    $skip_pmseries && [ "$cmd" = pmseries ] && continue
     comps=$(grep -A 1 "  $cmd)" $bash_comp | tail -n 1 | sed -e 's,all_args=",,' -e 's,",,')
     # Need $tmp.err and PCP_STDERR for pmchart ...
     #
@@ -137,23 +87,13 @@ _check_completion_zsh()
 {
   for cmd in $(grep '#compdef' $zsh_comp | sed -e 's,#compdef ,,'); do
     $skip_pcp2elasticsearch && [ "$cmd" = pcp2elasticsearch ] && continue
-    $skip_pcp2graphite && [ "$cmd" = pcp2graphite ] && continue
-    $skip_pcp2influxdb && [ "$cmd" = pcp2influxdb ] && continue
-    $skip_pcp2json && [ "$cmd" = pcp2json ] && continue
-    $skip_pcp2spark && [ "$cmd" = pcp2spark ] && continue
     $skip_pcp2xlsx && [ "$cmd" = pcp2xlsx ] && continue
-    $skip_pcp2xml && [ "$cmd" = pcp2xml ] && continue
-    $skip_pcp2zabbix && [ "$cmd" = pcp2zabbix ] && continue
-    $skip_pmchart && [ "$cmd" = pmchart ] && continue
-    $skip_pmdumptext && [ "$cmd" = pmdumptext ] && continue
     $skip_pmrep && [ "$cmd" = pmrep ] && continue
-    $skip_pmseries && [ "$cmd" = pmseries ] && continue
     echo $cmd | grep = > /dev/null 2>&1 && continue
     common=$(awk "/common_most=/,/  \)/" $zsh_comp)
     pytool=$(awk "/common_python=/,/  \)/" $zsh_comp)
-    pmda=$(awk "/common_pmda=/,/  \)/" $zsh_comp)
     version=V
-    comps=$(awk "/  $cmd\)/,/\;\;/" $zsh_comp | sed -e 's,equivalent to .*,,')
+    comps=$(awk "/  $cmd\)/,/\;\;/" $zsh_comp)
     # Need $tmp.err and PCP_STDERR for pmchart ...
     #
     rm -f $tmp.err
@@ -165,36 +105,29 @@ _check_completion_zsh()
     cat $tmp.out >>$here/$seq.full
     echo "--- stderr ---" >>$here/$seq.full
     cat $tmp.err >>$here/$seq.full
-    opts=$(cat $tmp.out $tmp.err | sed -e 's,equivalent to .*,,' | grep -Eo -- ' -[^-].' | tr -d - | tr -d '?' | tr -d , | sort | uniq)
+    opts=$(cat $tmp.out $tmp.err | grep -Eo -- ' -.' | tr -d '-' | tr -d '?' | sort | uniq)
     echo "opts=$opts" >>$here/$seq.full
 
     for opt in $opts; do
-      echo $comps | grep -E -- '({-'$opt'|"-'$opt')' > /dev/null 2>&1
+      echo $comps | grep -- -$opt > /dev/null 2>&1
       not_found=$?
-      if [ $not_found -ne 0 ]; then
-        if [ "$opt" = "V" ]; then
-          echo $comps | grep common_help > /dev/null 2>&1
-          not_found=$?
-        fi
-      fi
       if [ $not_found -ne 0 ]; then
         echo $comps | grep common_most > /dev/null 2>&1
         if [ $? -eq 0 ]; then
-          echo $common | grep -E -- '({-'$opt'|"-'$opt')' > /dev/null 2>&1
-          not_found=$?
-        fi
-      fi
-      if [ $not_found -ne 0 ]; then
-        echo $comps | grep common_pmda > /dev/null 2>&1
-        if [ $? -eq 0 ]; then
-          echo $pmda | grep -E -- '({-'$opt'|"-'$opt')' > /dev/null 2>&1
+          echo $common | grep -- -$opt > /dev/null 2>&1
           not_found=$?
         fi
       fi
       if [ $not_found -ne 0 ]; then
         echo $comps | grep common_python > /dev/null 2>&1
         if [ $? -eq 0 ]; then
-          echo $pytool | grep -E -- '({-'$opt'|"-'$opt')' > /dev/null 2>&1
+          echo $pytool | grep -- -$opt > /dev/null 2>&1
+          not_found=$?
+        fi
+      fi
+      if [ $not_found -ne 0 ]; then
+        if [ "$opt" = "V" ]; then
+          echo $comps | grep common_help > /dev/null 2>&1
           not_found=$?
         fi
       fi
@@ -214,7 +147,7 @@ _check_completion_zsh()
 }
 
 # real QA test starts here
-echo "== only V+u for pmlogger should be missing"
+echo "== only pmlogger/V should be missing"
 _check_completion_bash
 _check_completion_zsh
 
diff --git a/src/qa/115 b/src/qa/115
--- a/src/qa/115
+++ b/src/qa/115
@@ -37,16 +37,6 @@ _cleanup()
 	cat $file >>$here/$seq.full
     done
     $sudo rm -f $tmp.*
-    _restore_auto_restart pmcd
-    if $pmie_was_running
-    then
-	_restore_auto_restart pmie
-	_service pmie start >>$here/$seq.full 2>&1
-    else
-	_service pmie stop >>$here/$seq.full 2>&1
-	$sudo $PCP_BINADM_DIR/pmsignal -a -s TERM pmie >>$here/$seq.full 2>&1
-	_wait_pmie_end
-    fi
 }
 
 status=1	# failure is the default!
@@ -55,14 +45,11 @@ signal=$PCP_BINADM_DIR/pmsignal
 needclean=false
 trap "_cleanup; exit \$status" 0 1 2 3 15
 
-_stop_auto_restart pmcd
-
 lhost=`hostname | sed -e 's/\..*//'`
 host=`_get_fqdn`
 remote=`./getpmcdhosts -n 1 -L 2>$tmp.out`
 rhost=`echo $remote | sed -e 's/\..*//'`
 [ -z "$remote" ] && _notrun `cat $tmp.out`
-echo "remote=$remote" >>$here/$seq.full
 
 # Now that we have pmmgr in the mix, there is more than one pmie
 # potentially running, so lines like this
@@ -73,23 +60,9 @@ echo "remote=$remote" >>$here/$seq.full
 # mkdir: error lines ... not consistency in format, so cull 'em
 # ditto for cd errors reported from pmie_check
 #
-# and these ones (w/out systemctl) ...
-# $PCP_RC_DIR/pmie:
-# Error: PCP inference engine control file $PCP_PMIECONTROL_PATH
-# is missing!  Cannot start any Performance Co-Pilot inference engine(s).
-# failed (status=1)
-#
-# and if systemctl in the mix, then the error cases produce chatter
-# like:
-# Job for pmie.service failed because the service did not take the steps required by its unit configuration.
-# See "systemctl status pmie.service" and "journalctl -xe" for details.
-# or
-# Job for pmie.service failed because of unavailable resources or another system error.
-#
 _filter()
 {
-    tee -a $here/$seq.full \
-    | sed \
+    sed \
 	-e "s/$seq-$$/SEQ-PID/g" \
 	-e "s;$PCP_BIN_DIR/pmie;\$PCP_BIN_DIR/pmie;" \
 	-e 's/line [0-9][0-9]*:/line N:/' \
@@ -106,12 +79,7 @@ _filter()
 	-e '/\/pmie_check:.*cd:/d' \
 	-e 's/[ 	]*$//' \
 	-e 's/^[ 	]*//' \
-	-e '/\$PCP_RC_DIR\/pmie:/d' \
-	-e '/^Error: PCP inference engine control file/d' \
-	-e '/^is missing! /d' \
-	-e '/^failed /d' \
-	-e '/^Job for pmie.service failed because /d' \
-	-e '/^See "systemctl  *status pmie.service" and/d' \
+	-e 's/\.\.failed/failed (status=1)/' \
     # end
 }
 
@@ -130,13 +98,13 @@ _count_pmies()
 
     for process in $plist
     do
-	$PCP_PS_PROG $PCP_PS_ALL_FLAGS -p $process >/dev/null 2>&1
+	ps -p $process >/dev/null 2>&1
 	if [ $? = 1 ]
 	then
 	    echo "urk, $PCP_TMP_DIR/pmie/$process has no running pmie instance"
 	else
 	    count=`expr $count + 1`
-	    $PCP_PS_PROG $PCP_PS_ALL_FLAGS -p $process >>$here/$seq.full
+	    ps -f -p $process >>$here/$seq.full
 	    if `which pstree >/dev/null 2>&1`
 	    then
 		pstree $process >>$here/$seq.full
@@ -149,7 +117,7 @@ _count_pmies()
 
 # create a basic pmcd config file
 cat >$tmp.pmcd.conf << EOF
-# Installed by PCP QA test $seq on `date`
+# from QA $seq
 pmcd	2	dso	pmcd_init	pmda_pmcd.so
 EOF
 
@@ -173,15 +141,6 @@ $remote         n n $tmp.log2 -c $tmp.conf
 LOCALHOSTNAME   y n $tmp.log0 -c $tmp.conf
 EOF
 
-pmie_was_running=false
-if [ -f $PCP_RUN_DIR/pmie.pid ]
-then
-    pmie_was_running=true
-    echo "Found pmie PID `cat $PCP_RUN_DIR/pmie.pid` running @ start" >>$here/$seq.full
-    _stop_auto_restart pmie
-    _service pmie stop >>$here/$seq.full 2>&1
-fi
-
 # real QA test starts here
 _save_config $PCP_PMIECONTROL_PATH
 _save_config $PCP_PMCDCONF_PATH
@@ -189,24 +148,23 @@ needclean=true
 $sudo cp $tmp.pmcd.conf $PCP_PMCDCONF_PATH 
 
 $sudo $signal -a -s TERM pmie >/dev/null 2>&1
-_wait_pmie_end
+sleep 1
 _change_config pmcd on
 _change_config pmie off
 $sudo rm -f $PCP_TMP_DIR/pmie/*
 
 _count_pmies
-echo "pmie count at start of QA testing: $?" | tee -a $here/$seq.full
+echo "pmie count at start of QA testing: $?"
 echo
 
-echo === check default install operation === | tee -a $here/$seq.full
+echo === check default install operation ===
 _service pmie restart 2>&1 | _filter_pmie_start
-_wait_for_pmie
 _count_pmies
 # chkconfig no longer controls start-ability, expect non-zero
 echo "pmie count after chkconfig pmie off: $?"
 echo
 
-echo === check for missing control file === | tee -a $here/$seq.full
+echo === check for missing control file ===
 _change_config pmie off
 $sudo rm -f $PCP_PMIECONTROL_PATH
 _change_config pmie on
@@ -215,24 +173,22 @@ _count_pmies
 echo "pmie count after attempt without control file: $?"
 echo
 
-echo === check pmie_check and custom configs === | tee -a $here/$seq.full
-echo "--- v1.0 ---" | tee -a $here/$seq.full
-pmie_check -V -V -N -c $tmp.control.v1.0 >$tmp.log
+echo === check pmie_check and custom configs ===
+echo "--- v1.0 ---"
+pmie_check -V -V -N -c $tmp.control.v1.0 -l $tmp.log
 cat $tmp.log | _filter
-rm -f $tmp.log
 # don't bother counting pmie processes, as -N is used above!
 #
 echo
-echo "--- v1.1 ---" | tee -a $here/$seq.full
-pmie_check -V -V -N -c $tmp.control.v1.1 >$tmp.log
+echo "--- v1.1 ---"
+pmie_check -V -V -N -c $tmp.control.v1.1 -l $tmp.log
 cat $tmp.log | _filter
-rm -f $tmp.log
 # don't bother counting pmie processes, as -N is used above!
 #
 echo
 
-echo "=== warnings ... ===" | tee -a $here/$seq.full
-echo "--- stale lock file ---" | tee -a $here/$seq.full
+echo "=== warnings ... ==="
+echo "--- stale lock file ---"
 case=1
 cat >$tmp.warning.$case << EOF
 \$version=1.1
@@ -240,11 +196,10 @@ LOCALHOSTNAME   n n $tmp.locker/ok.$case -c $tmp.conf
 EOF
 mkdir $tmp.locker
 touch -t `pmdate -35M %Y%m%d%H%M` $tmp.locker/ok.$case.lock
-pmie_check -V -V -N -c $tmp.warning.$case >$tmp.warning.$case.log
+pmie_check -V -V -N -c $tmp.warning.$case -l $tmp.warning.$case.log
 cat $tmp.warning.$case.log | _filter
-rm -f $tmp.warning.$case.log
 echo
-echo "--- existing lock file ---" | tee -a $here/$seq.full
+echo "--- existing lock file ---"
 case=`expr $case + 1`
 cat >$tmp.warning.$case << EOF
 \$version=1.1
@@ -252,25 +207,21 @@ LOCALHOSTNAME   n n $tmp.locker/ok.$case -c $tmp.conf
 EOF
 rm -f $tmp.locker/ok.$case.lock
 touch $tmp.locker/ok.$case.lock
-$PCP_PS_PROG $PCP_PS_ALL_ARGS | grep '([P]ID)|([p]mie)' >>$here/$seq.full
-pmie_check -V -V -N -c $tmp.warning.$case >$tmp.warning.$case.log
-$PCP_PS_PROG $PCP_PS_ALL_ARGS | grep '([P]ID)|([p]mie)' >>$here/$seq.full
+pmie_check -V -V -N -c $tmp.warning.$case -l $tmp.warning.$case.log
 cat $tmp.warning.$case.log | _filter
-rm -f $tmp.warning.$case.log
 echo
-echo "--- can't create lock file ---" | tee -a $here/$seq.full
+echo "--- can't create lock file ---"
 case=`expr $case + 1`
 cat >$tmp.warning.$case << EOF
 \$version=1.1
 LOCALHOSTNAME   n n $tmp.locker/ok.$case -c $tmp.conf
 EOF
 chmod 555 $tmp.locker
-pmie_check -V -V -N -c $tmp.warning.$case >$tmp.warning.$case.log
+pmie_check -V -V -N -c $tmp.warning.$case -l $tmp.warning.$case.log
 cat $tmp.warning.$case.log | _filter
-rm -f $tmp.warning.$case.log
 $sudo rm -rf $tmp.locker
 echo
-echo "--- bad in-line shell commands ---" | tee -a $here/$seq.full
+echo "--- bad in-line shell commands ---"
 case=`expr $case + 1`
 cat >$tmp.warning.$case << EOF
 \$version=1.1
@@ -279,106 +230,101 @@ cat >$tmp.warning.$case << EOF
 \$IFS=a
 LOCALHOSTNAME   n n $tmp.ok.$case -c $tmp.conf
 EOF
-pmie_check -V -V -N -c $tmp.warning.$case >$tmp.warning.$case.log
+pmie_check -V -V -N -c $tmp.warning.$case -l $tmp.warning.$case.log
 cat $tmp.warning.$case.log | _filter
-rm -f $tmp.warning.$case.log
 echo
-echo "--- missing \$version but really v1.1 ... original control.local issue ---" | tee -a $here/$seq.full
+echo "--- missing \$version but really v1.1 ... original control.local issue ---"
 case=`expr $case + 1`
 cat >$tmp.warning.$case << EOF
 LOCALHOSTNAME   n n $tmp.ok.$case -c $tmp.conf
 EOF
-pmie_check -V -V -N -c $tmp.warning.$case >$tmp.warning.$case.log
+pmie_check -V -V -N -c $tmp.warning.$case -l $tmp.warning.$case.log
 cat $tmp.warning.$case.log | _filter
-rm -f $tmp.warning.$case.log
 echo
 
-echo "=== errors ... ===" | tee -a $here/$seq.full
-echo "--- bad version ---" | tee -a $here/$seq.full
+echo "=== errors ... ==="
+echo "--- bad version ---"
 case=1
 cat >$tmp.error.$case << EOF
 \$version=0.0
 LOCALHOSTNAME   n $tmp.bad.$case -c $tmp.conf
 EOF
-pmie_check -V -V -N -c $tmp.error.$case >$tmp.bad.$case.log
+pmie_check -V -V -N -c $tmp.error.$case -l $tmp.bad.$case.log
 cat $tmp.bad.$case.log | _filter
-rm -f $tmp.bad.$case.log
 echo
 case=`expr $case + 1`
-echo "--- v1.0 socks != y|n ---" | tee -a $here/$seq.full
+echo "--- v1.0 socks != y|n ---"
 cat >$tmp.error.$case << EOF
 \$version=1.0
 LOCALHOSTNAME   x $tmp.bad.$case -c $tmp.conf
 EOF
-pmie_check -V -V -N -c $tmp.error.$case >$tmp.bad.$case.log
+pmie_check -V -V -N -c $tmp.error.$case -l $tmp.bad.$case.log
 cat $tmp.bad.$case.log | _filter
-rm -f $tmp.bad.$case.log
 echo
 case=`expr $case + 1`
-echo "--- v1.1 socks != y|n ---" | tee -a $here/$seq.full
+echo "--- v1.1 socks != y|n ---"
 cat >$tmp.error.$case << EOF
 \$version=1.1
 LOCALHOSTNAME   n x $tmp.bad.$case -c $tmp.conf
 EOF
-pmie_check -V -V -N -c $tmp.error.$case >$tmp.bad.$case.log
+pmie_check -V -V -N -c $tmp.error.$case -l $tmp.bad.$case.log
 cat $tmp.bad.$case.log | _filter
-rm -f $tmp.bad.$case.log
 echo
 case=`expr $case + 1`
-echo "--- v1.1 primary != y|n ---" | tee -a $here/$seq.full
+echo "--- v1.1 primary != y|n ---"
 cat >$tmp.error.$case << EOF
 \$version=1.1
 LOCALHOSTNAME   x n $tmp.bad.$case -c $tmp.conf
 EOF
-pmie_check -V -V -N -c $tmp.error.$case >$tmp.bad.$case.log
+pmie_check -V -V -N -c $tmp.error.$case -l $tmp.bad.$case.log
 cat $tmp.bad.$case.log | _filter
-rm -f $tmp.bad.$case.log
 echo
 case=`expr $case + 1`
-echo "--- v1.0 insufficient fields ---" | tee -a $here/$seq.full
+echo "--- v1.0 insufficient fields ---"
 cat >$tmp.error.$case << EOF
 \$version=1.0
 LOCALHOSTNAME   n $tmp.bad.$case
 EOF
-pmie_check -V -V -N -c $tmp.error.$case >$tmp.bad.$case.log
+pmie_check -V -V -N -c $tmp.error.$case -l $tmp.bad.$case.log
 cat $tmp.bad.$case.log | _filter
-rm -f $tmp.bad.$case.log
 echo
 case=`expr $case + 1`
-echo "--- v1.1 insufficient fields ---" | tee -a $here/$seq.full
+echo "--- v1.1 insufficient fields ---"
 cat >$tmp.error.$case << EOF
 \$version=1.1
 LOCALHOSTNAME   n n $tmp.bad.$case
 EOF
-pmie_check -V -V -N -c $tmp.error.$case >$tmp.bad.$case.log
+pmie_check -V -V -N -c $tmp.error.$case -l $tmp.bad.$case.log
 cat $tmp.bad.$case.log | _filter
-rm -f $tmp.bad.$case.log
 echo
 mkdir $tmp.nogo
 chmod 000 $tmp.nogo
 case=`expr $case + 1`
-echo "--- can't create dir for logfile ---" | tee -a $here/$seq.full
+echo "--- can't create dir for logfile ---"
 cat >$tmp.error.$case << EOF
 \$version=1.1
 LOCALHOSTNAME   n n $tmp.nogo/subdir/bad.$case -c $tmp.conf
 EOF
-pmie_check -V -V -N -c $tmp.error.$case >$tmp.bad.$case.log
+pmie_check -V -V -N -c $tmp.error.$case -l $tmp.bad.$case.log
 cat $tmp.bad.$case.log | _filter
-rm -f $tmp.bad.$case.log
 echo
 case=`expr $case + 1`
-echo "--- can't chdir to dir for logfile ---" | tee -a $here/$seq.full
+echo "--- can't chdir to dir for logfile ---"
 cat >$tmp.error.$case << EOF
 \$version=1.1
 LOCALHOSTNAME   n n $tmp.nogo/bad.$case -c $tmp.conf
 EOF
-pmie_check -V -V -N -c $tmp.error.$case >$tmp.bad.$case.log
+pmie_check -V -V -N -c $tmp.error.$case -l $tmp.bad.$case.log
 cat $tmp.bad.$case.log | _filter
-rm -f $tmp.bad.$case.log
 echo
 $sudo rm -rf $tmp.nogo
 
-$sudo $signal -a -s TERM pmie >/dev/null 2>&1
+_service pmie stop 2>&1 \
+| _filter_pmie_start \
+| sed \
+    -e '/PMIE not running/d' \
+    -e '/pmie not running/d' \
+# end
 _change_config pmie off
 
 status=0
diff --git a/src/qa/1191 b/src/qa/1191
--- a/src/qa/1191
+++ b/src/qa/1191
@@ -1,55 +1,59 @@
 #!/bin/sh
 # PCP QA Test No. 1191
-# pmdaprometheus sample exporter snapshot ingestion
+# Exercise the prometheus PMDA
 #
-# Copyright (c) 2017 Red Hat.  All Rights Reserved.
+# Copyright (c) 2017 Ronak Jain.  All Rights Reserved.
 #
-# Note: if anything gets added or changed in qa/prometheus/samples directory,
-# then this test (and all tests in group pmda.prometheus) will need to be remade.
 
 seq=`basename $0`
 echo "QA output created by $seq"
 
 # get standard environment, filters and checks
-. ./common.prometheus
+. ./common.product
+. ./common.filter
+. ./common.check
+. ./common.python
 
-_pmdaprometheus_check || _notrun "prometheus pmda and/or load generator not installed"
-_have_python266 && _notrun "python load generator does not currently work with python 2.6.6"
+[ -f $PCP_PMDAS_DIR/prometheus/pmdaprometheus.python ] || _notrun "prometheus pmda not installed"
 
-status=1	# failure is the default!
+$python -c "import requests"
+[ $? -eq 0 ] || _notrun "python requests module not installed"
+
+status=1    # failure is the default!
 $sudo rm -rf $tmp $tmp.* $seq.full
 
-_cleanup()
+pmdaprometheus_remove()
 {
-    _pmdaprometheus_restore_config >>$here/$seq.full
-    cd $here
-    $sudo rm -rf $tmp $tmp.*
+    echo
+    echo "=== remove prometheus agent ==="
+    $sudo ./Remove >$tmp.out 2>&1
+    _filter_pmda_remove <$tmp.out
 }
 
-trap "_cleanup; exit \$status" 0 1 2 3 15
+pmdaprometheus_install()
+{
+    # start from known starting points
+    cd $PCP_PMDAS_DIR/prometheus
+    $sudo ./Remove >/dev/null 2>&1
+    _service pmcd stop 2>&1 | _filter_pcp_stop
 
-_pmdaprometheus_save_config
+    echo
+    echo "=== prometheus agent installation ==="
+    $sudo ./Install </dev/null >$tmp.out 2>&1
+    cat $tmp.out >>$here/$seq.full
+}
 
-# add all the sample text files as urls.
-ls -1 $here/prometheus/samples/*.txt | sort | while read file
-do
-    urlbase=`basename $file .txt | tr .- _`
-    echo 'file://'$file > $PCP_PMDAS_DIR/prometheus/config.d/$urlbase.url
-done
+_prepare_pmda prometheus
+# note: _restore_auto_restart pmcd done in _cleanup_pmda()
+trap "_cleanup_pmda prometheus; exit \$status" 0 1 2 3 15
 
-# add all the sample scripts
-cp -a $here/prometheus/scripts/* $PCP_PMDAS_DIR/prometheus/config.d
-find $PCP_PMDAS_DIR/prometheus/config.d -name GNU\* -exec rm -f {} ";"
+_save_config $PCP_PMDAS_DIR/prometheus/metadata
+$sudo rm -f $PCP_PMDAS_DIR/prometheus/metadata/*
 
-_pmdaprometheus_install
+# real QA test starts here
+pmdaprometheus_install
 
-if ! _pmdaprometheus_wait_for_metric prometheus.thermostat
-then
-    status=1
-    exit
-fi
-
-if pminfo -dtTf `pminfo prometheus | fgrep -v prometheus.control | LC_COLLATE=POSIX sort` > $tmp.info 2> $tmp.err
+if pminfo -v prometheus > $tmp.info 2> $tmp.err
 then
     :
 else
@@ -58,8 +62,9 @@ else
 fi
 cat $tmp.info $tmp.err
 
-_pmdaprometheus_remove
+pmdaprometheus_remove
 
-# success, all done
+_restore_config $PCP_PMDAS_DIR/prometheus/metadata
+
 status=0
 exit
diff --git a/src/qa/1192 b/src/qa/1192
--- a/src/qa/1192
+++ b/src/qa/1192
@@ -1,96 +1,111 @@
 #!/bin/sh
 # PCP QA Test No. 1192
-# Exercise podman container detection and metrics.
+# Exercise the Prometheus PMDA with docker.
 #
-# Copyright (c) 2018 Red Hat.  All Rights Reserved.
+# Copyright (c) 2017 Ronak Jain.  All Rights Reserved.
 #
 
 seq=`basename $0`
 echo "QA output created by $seq"
 
-. ./common.containers
+. ./common.product
+. ./common.filter
+. ./common.check
+. ./common.python
 
-_check_containers
-_check_podman_binary
-_check_podman_images busybox
+[ -f $PCP_PMDAS_DIR/prometheus/pmdaprometheus.python ] || _notrun "prometheus pmda not installed"
+
+$python -c "import requests"
+[ $? -eq 0 ] || _notrun "python requests module not installed"
+
+$python -c "import prometheus_client"
+[ $? -eq 0 ] || _notrun "python prometheus_client module not installed"
 
 _cleanup()
 {
-    if [ -n "$container" ]
+    if [ -n "$pid" ]
     then
-        echo "== removing container" | tee -a $seq.full
-        _remove_podman_containers $container
-        container=""
-    fi 
-    rm -rf $tmp.*
+        kill $pid >/dev/null 2>&1
+    fi
+    $sudo rm -rf $tmp.* $tmp.*
+    _restore_config $PCP_PMDAS_DIR/prometheus/metadata
+    _restore_config $PCP_VAR_DIR/config/pmda
+    _cleanup_pmda prometheus
+}
+
+pmdaprometheus_remove()
+{
+    echo
+    echo "=== remove prometheus agent ==="
+    $sudo ./Remove >$tmp.out 2>&1
+    _filter_pmda_remove <$tmp.out
+}
+
+pmdaprometheus_install()
+{
+    # start from known starting points
+    cd $PCP_PMDAS_DIR/prometheus
+    $sudo ./Remove >/dev/null 2>&1
+    _service pmcd stop 2>&1 | _filter_pcp_stop
+
+    echo
+    echo "=== prometheus agent installation ==="
+    $sudo ./Install </dev/null >$tmp.out 2>&1
+    cat $tmp.out >>$here/$seq.full
+}
+
+generate_config()
+{
+	cd $PCP_PMDAS_DIR/prometheus
+	$sudo ./pmdaprometheus.python -g -n "test" -u "http://127.0.0.1:9090"
 }
 
 status=1	# failure is the default!
-$sudo rm -rf $tmp.* $seq.full
-trap "_cleanup; exit \$status" 0 1 2 3 15
+$sudo rm -rf $tmp $tmp.* $seq.full
+_prepare_pmda prometheus
+trap "_cleanup; _cleanup_pmda prometheus; exit \$status" 0 1 2 3 15
 
-_filter_pminfo()
-{
-    # filter ip_vti tunnel type connections that may exist on (some) machines
-    tee -a $here/$seq.full >$tmp.tmp
-    sed <$tmp.tmp \
-	-e '/ip_vti/d' \
-	-e '2q' \
-    # end
-    sed <$tmp.tmp \
-	-e '1,2d' \
-	-e 's/\[[0-9][0-9]* or ".*"\]/[INST or NAME]/' \
-	-e 's/value [-?0-9.e+][-?0-9.e+]*/value NUMBER/' \
-	-e 's/value ".*"$/value STRING/' \
-    | LC_COLLATE=POSIX sort \
-    | uniq
-}
+_stop_auto_restart pmcd
+_save_config $PCP_PMDAS_DIR/prometheus/metadata
+_save_config $PCP_VAR_DIR/config/pmda
+$sudo rm -f $PCP_PMDAS_DIR/prometheus/metadata/*
+$sudo rm -f $PCP_VAR_DIR/config/pmda/*
 
 # real QA test starts here
-container=`$sudo $podman run -d busybox sleep 15`
-echo "== container: $container" >> $seq.full
 
-echo "== kernel PMDA" | tee -a $seq.full
-# expect 2 interfaces (lo/eth0) # mounts different.
-metrics="network.interface.in.bytes" # filesys.used
-for m in $metrics
-do
-    pminfo --fetch --container=$container $m | _filter_pminfo
-done
-echo
+$python $here/prometheus/prometheus_client_server.python &
+pid=$!
+sleep 3 #avoid racing
+generate_config
 
-echo "== procfs PMDA" | tee -a $seq.full
-# expect values for a single process (sleep) and one cgroup
-metrics="proc.memory.rss cgroup.memory.stat.rss"
-for m in $metrics
-do
-    pminfo --fetch --container=$container $m | _filter_pminfo
-done
-echo
+pmdaprometheus_install
 
-echo "== pmcd PMDA" | tee -a $seq.full
-# expect a different hostname to local hostname
-pmprobe --values --container=$container pmcd.hostname > $tmp.chost
-pmprobe --values pmcd.hostname > $tmp.host
-container_hostname=`awk '{ print $3 }' $tmp.chost`
-localhost_hostname=`awk '{ print $3 }' $tmp.host`
-
-cat $tmp.chost $tmp.host >> $seq.full
-echo container hostname: $container_hostname >> $seq.full
-echo localhost hostname: $localhost_hostname >> $seq.full
-
-if [ $container_hostname != $localhost_hostname ]
+if pminfo -v prometheus > $tmp.info 2> $tmp.err
 then
-    echo
-    echo "OK: host and container names are different"
-    echo
+	echo "Installation ok"
 else
-    echo "FAIL: hostnames match when they should not"
-    echo "localhost: $localhost_hostname"
-    echo "container: $container_hostname"
-    status=1
-    exit
+	echo "Installation failed"
+	cat $tmp.out
 fi
+
+if pminfo -f prometheus.test.queue_size > $tmp.info 2> $tmp.err
+then
+	echo "Fetch prometheus.test.queue_size: success"
+	pminfo -f prometheus.test.queue_size
+else
+	echo "Fetch prometheus.test.queue_size: failed"
+	cat $tmp.err
+fi
+
+if pminfo -f prometheus.test.requests_total > $tmp.info 2> $tmp.err
+then
+    echo "Fetch prometheus.test.requests_total: success"
+else
+    echo "Fetch prometheus.test.requests_total: failed"
+    cat $tmp.err
+fi
+
+pmdaprometheus_remove
 
 # success, all done
 status=0
diff --git a/src/src/pmdas/logger/Install b/src/src/pmdas/logger/Install
--- a/src/src/pmdas/logger/Install
+++ b/src/src/pmdas/logger/Install
@@ -20,6 +20,7 @@
 . $PCP_SHARE_DIR/lib/pmdaproc.sh
 
 iam=logger
+pmda_interface=5
 
 pmdaSetup
 
@@ -49,114 +50,117 @@ _parsedefaults()
 }
 
 # Get logfile(s) to monitor
-# set options from $PCP_PMCDCONF_PATH, if possible
-#
-ans=`$PCP_AWK_PROG <$PCP_PMCDCONF_PATH '
+if $do_pmda
+then
+    # set options from $PCP_PMCDCONF_PATH, if possible
+    #
+    ans=`$PCP_AWK_PROG <$PCP_PMCDCONF_PATH '
 $1 == "'$iam'"	{ printf "%s",$6
-	      for (i=7;i<=NF;i++) printf " %s",$i
-	      print ""
-	    }'`
-if [ ! -z "$ans" ]
-then
-    _parsedefaults $ans
-fi
-
-# go figure out which configuration file to use ...
-#
-#default_configfile=./sample.conf
-default_configfile=''
-pmdaChooseConfigFile
-if [ ! -f "$configfile" ]
-then
-    $PCP_ECHO_PROG $PCP_ECHO_N "Do you wish to enter logfile names and paths manually? [y] ""$PCP_ECHO_C"
-    read ans
-    if [ "X$ans" = "Xy" -o "X$ans" = "XY" -o -z "$ans" ]
+		  for (i=7;i<=NF;i++) printf " %s",$i
+		  print ""
+	        }'`
+    if [ ! -z "$ans" ]
     then
-	configfile="$configdir/$iam.conf"
-	if [ -f "$configfile" ]
-	then
-		echo "Removing old configuration file \"$configfile\""
-		rm -f "$configfile"
-		if [ -f "$configfile" ]
-		then
-			echo "Cannot remove \"$configfile\""
-			status=1
-			exit
-		fi
-	fi
+	_parsedefaults $ans
+    fi
 
-	echo
-	echo \
+    # go figure out which configuration file to use ...
+    #
+    #default_configfile=./sample.conf
+    default_configfile=''
+    pmdaChooseConfigFile
+    if [ ! -f "$configfile" ]
+    then
+	$PCP_ECHO_PROG $PCP_ECHO_N "Do you wish to enter logfile names and paths manually? [y] ""$PCP_ECHO_C"
+	read ans
+	if [ "X$ans" = "Xy" -o "X$ans" = "XY" -o -z "$ans" ]
+	then
+	    configfile="$configdir/$iam.conf"
+	    if [ -f "$configfile" ]
+	    then
+		    echo "Removing old configuration file \"$configfile\""
+		    rm -f "$configfile"
+		    if [ -f "$configfile" ]
+		    then
+			    echo "Cannot remove \"$configfile\""
+			    status=1
+			    exit
+		    fi
+	    fi
+
+	    echo
+	    echo \
 'Enter the PMNS name and logfile path.  If the  path ends in "|", the
 filename is interpreted as a command which will output data.
 
 An empty line terminates the logfile selection process and there must
 be at least one logfile specified.  '
 
-	args=""
-	touch "$configfile"
-	if [ ! -f "$configfile" ]
-	then
-	    echo "Installation aborted."
-	    status=1
-	    exit
-	fi
+	    args=""
+	    touch "$configfile"
+	    if [ ! -f "$configfile" ]
+	    then
+		echo "Installation aborted."
+		status=1
+		exit
+	    fi
 
-	while [ ! -s "$configfile" ]
-	do
-	    while true
+	    while [ ! -s "$configfile" ]
 	    do
-		$PCP_ECHO_PROG $PCP_ECHO_N "Logfile PMNS name: ""$PCP_ECHO_C"
-		read name
-		[ -z "$name" ] && break
+		while true
+		do
+		    $PCP_ECHO_PROG $PCP_ECHO_N "Logfile PMNS name: ""$PCP_ECHO_C"
+		    read name
+		    [ -z "$name" ] && break
 
-		# Check name for invalid chars.
-		if ! echo $name | grep "^[A-Za-z][_A-Za-z0-9]*$" > /dev/null
-		then
-		    echo \
+		    # Check name for invalid chars.
+		    if ! echo $name | grep "^[A-Za-z][_A-Za-z0-9]*$" > /dev/null
+		    then
+			echo \
 "Invalid characters in PMNS name: \"$name\".
 Names must start with an alphabetic character ([a-zA-Z]).  The rest of
 the characters in the name must be alphanumeric ([a-zA-Z0-9]) or an
 underscore ('_')."
-		    continue
-		fi
+			continue
+		    fi
 
-		# Make sure name isn't already in the logfile.
-		if grep "^${name}[ \t]" "$configfile" >/dev/null
-		then
-		    echo "Sorry, logfile PMNS name \"$name\" already specified.  Please try again."
-		    continue
-		fi
+		    # Make sure name isn't already in the logfile.
+		    if grep "^${name}[ \t]" "$configfile" >/dev/null
+		    then
+			echo "Sorry, logfile PMNS name \"$name\" already specified.  Please try again."
+			continue
+		    fi
 
-		$PCP_ECHO_PROG $PCP_ECHO_N "Logfile pathname: ""$PCP_ECHO_C"
-		read pathname
-		[ -z "$pathname" ] && break
-		if grep "[ \t]${pathname}$" "$configfile" >/dev/null
-		then
-		    echo "Sorry, pathname \"$pathname\" already specified.  Please try again."
-		    continue
-		fi
+		    $PCP_ECHO_PROG $PCP_ECHO_N "Logfile pathname: ""$PCP_ECHO_C"
+		    read pathname
+		    [ -z "$pathname" ] && break
+		    if grep "[ \t]${pathname}$" "$configfile" >/dev/null
+		    then
+			echo "Sorry, pathname \"$pathname\" already specified.  Please try again."
+			continue
+		    fi
 
-		$PCP_ECHO_PROG $PCP_ECHO_N "Restricted access [n]: ""$PCP_ECHO_C"
-		read restrict
-		if [ "$restrict" = "y" -o "$restrict" = "yes" ]; then
-		    restrict="y"
-		else
-		    restrict="n"
-		fi
+		    $PCP_ECHO_PROG $PCP_ECHO_N "Restricted access [n]: ""$PCP_ECHO_C"
+		    read restrict
+		    if [ "$restrict" = "y" -o "$restrict" = "yes" ]; then
+			restrict="y"
+		    else
+			restrict="n"
+		    fi
 
-		echo "$name $restrict $pathname" >>"$configfile"
+		    echo "$name $restrict $pathname" >>"$configfile"
+		done
 	    done
-	done
-    else
-	echo ""
-	echo "Error: Abandoning installation as no configuration file was specified."
-	status=1
-	exit
+	else
+	    echo ""
+	    echo "Error: Abandoning installation as no configuration file was specified."
+	    status=1
+	    exit
+	fi
     fi
-fi
 
-args="$configfile"
+    args="$configfile"
+fi
 
 pmdaInstall
 exit
