els-ASAP auto commit file/tag pcp-4.1.0-4.el7.src.rpm

diff --git a/src/qa/1193 b/src/qa/1193
--- a/src/qa/1193
+++ b/src/qa/1193
@@ -1,8 +1,8 @@
 #!/bin/sh
 # PCP QA Test No. 1193
-# Exercise the prometheus PMDA with metrics injection
+# Test that pmlogrewrite(1) updates help text records when PMIDs change
 #
-# Copyright (c) 2017 Ronak Jain.  All Rights Reserved.
+# Copyright (c) 2018 Red Hat.  All Rights Reserved.
 #
 
 seq=`basename $0`
@@ -12,130 +12,120 @@ echo "QA output created by $seq"
 . ./common.product
 . ./common.filter
 . ./common.check
-. ./common.python
 
-[ -f $PCP_PMDAS_DIR/prometheus/pmdaprometheus.python ] || _notrun "prometheus pmda not installed"
+# test for-some-thing || _notrun No support for some-thing
 
-$python -c "import requests"
-[ $? -eq 0 ] || _notrun "python requests module not installed"
+_cleanup()
+{
+    cd $here
+    $sudo rm -rf $tmp $tmp.*
+}
 
-status=1    # failure is the default!
+status=1	# failure is the default!
 $sudo rm -rf $tmp $tmp.* $seq.full
+trap "_cleanup; exit \$status" 0 1 2 3 15
 
-pmdaprometheus_remove()
+_filter()
 {
-    echo
-    echo "=== remove prometheus agent ==="
-    $sudo ./Remove >$tmp.out 2>&1
-    _filter_pmda_remove <$tmp.out
+    tmpx=`echo $tmp`
+    sed -e 's/^Archive:.* Host:/ARCHIVE: Host:/' \
+	-e "s|$tmpx|TMP|g" \
+	-e 's|PID for pmlogger: [0-9]*|PID for pmlogger: PID|'
 }
-
-pmdaprometheus_install()
-{
-    # start from known starting points
-    cd $PCP_PMDAS_DIR/prometheus
-    $sudo ./Remove >/dev/null 2>&1
-    _service pmcd stop 2>&1 | _filter_pcp_stop
-
-    echo
-    echo "=== prometheus agent installation ==="
-    $sudo ./Install </dev/null >$tmp.out 2>&1
-    cat $tmp.out >>$here/$seq.full
-}
-
-generate_config()
-{
-    cd $PCP_PMDAS_DIR/prometheus
-    $sudo ./pmdaprometheus.python -g -n "test" -f $tmp.json
-}
-
-
-_prepare_pmda prometheus
-# note: _restore_auto_restart pmcd done in _cleanup_pmda()
-trap "_cleanup_pmda prometheus; exit \$status" 0 1 2 3 15
-
-_save_config $PCP_PMDAS_DIR/prometheus/metadata
-_save_config $PCP_VAR_DIR/config/pmda
-$sudo rm -f $PCP_PMDAS_DIR/prometheus/metadata/*
-$sudo rm -f $PCP_VAR_DIR/config/pmda/*
-
-cat > $tmp.json <<EOF
-# HELP sample_gauge Sample gauge metric.
-# TYPE sample_gauge gauge
-sample_gauge 12.1
-# HELP sample_counter Sample counter metric.
-# TYPE sample_counter counter
-sample_counter 1.70205394e+08
-# HELP sample_summary Sample summary metric has instances.
-# TYPE sample_summary summary
-sample_summary{quantile="0"} 0.000159623
-sample_summary{quantile="0.25"} 0.000291993
-sample_summary_sum 1.3912067700000001
-sample_summary_count 1818
-# HELP sample_histogram Sample histogram metric has intances.
-# TYPE sample_histogram histogram
-sample_histogram{le="1"} 5945
-sample_histogram{le="2"} 10862
-sample_histogram{le="4"} 15813
-sample_histogram_sum 45157
-sample_histogram_count 18135
-EOF
 
 # real QA test starts here
+DIR=archives
 
-generate_config
+# First, run pmlogrewrite against the archive, changing PMID 70.0.2 to 200.0.2.
+CONFIG=$tmp.config
+cat > $CONFIG << EOF
+METRIC 70.0.2 { PMID -> 200.0.2 }
+EOF
+echo contents of $CONFIG >> $seq.full
+echo ........................ >> $seq.full
+cat $CONFIG >> $seq.full
+echo ........................ >> $seq.full
+IN=$DIR/20180127.08.40
+OUT=$tmp.pmlogrewrite
+rm -f $OUT.*
+echo "Running pmlogrewrite -c $CONFIG $IN $OUT" | _filter | tee -a $seq.full
+pmlogrewrite -c $CONFIG $IN $OUT 2>&1 >> $seq.full
+[ $? -eq 0 ] || echo "Error running pmlogrewrite -c $CONFIG $IN $OUT -- see $seq.full"
 
-pmdaprometheus_install
+# Now run pmdumplog against the original and extracted archives.
+DUMP1=$tmp.original.txt
+echo "Running pmdumplog -zhid $IN" | _filter | tee -a $seq.full
+pmdumplog -zhid $IN 2>&1 > $DUMP1
 
-if pminfo -v prometheus > $tmp.info 2> $tmp.err
-then
-    :
-else
-    echo "... failed! ... here is the Install log ..."
-    cat $tmp.out
-fi
-cat $tmp.info $tmp.err
+DUMP2=$tmp.extracted.txt
+IN=$OUT
+echo "Running pmdumplog -zhid $IN" | _filter | tee -a $seq.full
+pmdumplog -zhid $IN 2>&1 > $DUMP2
 
-if pminfo -fd prometheus.test.sample_gauge > $tmp.info 2> $tmp.err
-then
-    echo "Fetch and desc prometheus.test.sample_gauge: success"
-    cat $tmp.info
-else
-    echo "Fetch and desc prometheus.test.sample_gauge: failed"
-    cat $tmp.err
-fi
+# Make sure the PMID has been updated in the help text records
+echo "Running diff $DUMP1 $DUMP2" | _filter | tee -a $seq.full
+diff $DUMP1 $DUMP2 2>&1 | _filter | tee -a $seq.full
 
-if pminfo -fd prometheus.test.sample_counter > $tmp.info 2> $tmp.err
-then
-    echo "Fetch and desc prometheus.test.sample_counter: success"
-    cat $tmp.info
-else
-    echo "Fetch and desc prometheus.test.sample_counter: failed"
-    cat $tmp.err
-fi
+# Now, run pmlogrewrite against the archive, changing PMID 70.0.2 to 70.100.2.
+CONFIG=$tmp.config
+cat > $CONFIG << EOF
+METRIC 70.0.2 { PMID -> 70.100.2 }
+EOF
+echo contents of $CONFIG >> $seq.full
+echo ........................ >> $seq.full
+cat $CONFIG >> $seq.full
+echo ........................ >> $seq.full
+IN=$DIR/20180127.08.40
+OUT=$tmp.pmlogrewrite
+rm -f $OUT.*
+echo "Running pmlogrewrite -c $CONFIG $IN $OUT" | _filter | tee -a $seq.full
+pmlogrewrite -c $CONFIG $IN $OUT 2>&1 >> $seq.full
+[ $? -eq 0 ] || echo "Error running pmlogrewrite -c $CONFIG $IN $OUT -- see $seq.full"
+pmlogextract $OUT $tmp.xxxx
+# Now run pmdumplog against the original and extracted archives.
+DUMP1=$tmp.original.txt
+echo "Running pmdumplog -zhid $IN" | _filter | tee -a $seq.full
+pmdumplog -zhid $IN 2>&1 > $DUMP1
 
-if pminfo -f prometheus.test.sample_summary > $tmp.info 2> $tmp.err
-then
-    echo "Fetch prometheus.test.sample_summary: success"
-    cat $tmp.info
-else
-    echo "Fetch prometheus.test.sample_summary: failed"
-    cat $tmp.err
-fi
+DUMP2=$tmp.extracted.txt
+IN=$OUT
+echo "Running pmdumplog -zhid $IN" | _filter | tee -a $seq.full
+pmdumplog -zhid $IN 2>&1 > $DUMP2
 
-if pminfo -f prometheus.test.sample_histogram > $tmp.info 2> $tmp.err
-then
-    echo "Fetch prometheus.test.sample_histogram: success"
-    cat $tmp.info
-else
-    echo "Fetch prometheus.test.sample_histogram: failed"
-    cat $tmp.err
-fi
+# Make sure the PMID has been updated in the help text records
+echo "Running diff $DUMP1 $DUMP2" | _filter | tee -a $seq.full
+diff $DUMP1 $DUMP2 2>&1 | _filter | tee -a $seq.full
 
-pmdaprometheus_remove
+# Now, run pmlogrewrite against the archive, changing PMID 70.0.2 to 70.0.400.
+CONFIG=$tmp.config
+cat > $CONFIG << EOF
+METRIC 70.0.2 { PMID -> 70.0.400 }
+EOF
+echo contents of $CONFIG >> $seq.full
+echo ........................ >> $seq.full
+cat $CONFIG >> $seq.full
+echo ........................ >> $seq.full
+IN=$DIR/20180127.08.40
+OUT=$tmp.pmlogrewrite
+rm -f $OUT.*
+echo "Running pmlogrewrite -c $CONFIG $IN $OUT" | _filter | tee -a $seq.full
+pmlogrewrite -c $CONFIG $IN $OUT 2>&1 >> $seq.full
+[ $? -eq 0 ] || echo "Error running pmlogrewrite -c $CONFIG $IN $OUT -- see $seq.full"
 
-_restore_config $PCP_PMDAS_DIR/prometheus/metadata
-_restore_config $PCP_VAR_DIR/config/pmda
+# Now run pmdumplog against the original and extracted archives.
+DUMP1=$tmp.original.txt
+echo "Running pmdumplog -zhid $IN" | _filter | tee -a $seq.full
+pmdumplog -zhid $IN 2>&1 > $DUMP1
 
+DUMP2=$tmp.extracted.txt
+IN=$OUT
+echo "Running pmdumplog -zhid $IN" | _filter | tee -a $seq.full
+pmdumplog -zhid $IN 2>&1 > $DUMP2
+
+# Make sure the PMID has been updated in the help text records
+echo "Running diff $DUMP1 $DUMP2" | _filter | tee -a $seq.full
+diff $DUMP1 $DUMP2 2>&1 | _filter | tee -a $seq.full
+
+# success, all done
 status=0
 exit
diff --git a/src/src/pmchart/views/BusyCPU b/src/src/pmchart/views/BusyCPU
--- a/src/src/pmchart/views/BusyCPU
+++ b/src/src/pmchart/views/BusyCPU
@@ -25,13 +25,18 @@ _err()
     done
     echo >>$tmp/msg
     echo "Sorry, there is nothing to display." >>$tmp/msg
-    pmconfirm >/dev/null \
-	-header "pmchart view construction failure" \
-	-file $tmp/msg \
-	-icon error \
-	-B "OK"
+    if $dialog
+    then
+	pmconfirm >/dev/null \
+	    -header "pmchart view construction failure" \
+	    -file $tmp/msg \
+	    -icon error \
+	    -B "OK"
+    else
+	cat >&2 $tmp/msg
+    fi
     exit
-}
+    }
 
 # find top 10 consumers of user mode CPU cycles and generate a plot for each
 #
@@ -64,7 +69,7 @@ then
     #
     pmquery >/dev/null 2>&1 \
 	-timeout 5 \
-	-header "kmchart view construction" \
+	-header "pmchart view construction" \
 	-t "Finding top CPU burners, please wait 5 seconds ..." &
     query=$!
     echo "/\[0*$query /d" >>$tmp/sed
@@ -76,10 +81,10 @@ i=0
 fail=true
 for metric in proc.psinfo.utime proc.psusage.utime
 do
-    nval=`pmprobe -if $* $metric 2>&1 \
+    nval=`pmprobe -ifF $* $metric 2>&1 \
           | tee $tmp/err.$i \
-	  | $PCP_AWK_PROG '{print $2}'`
-    if [ "$nval" -gt 0 ]
+	  | $PCP_AWK_PROG '$1 == "'$metric'" && $2 > 0 {print $2}'`
+    if [ -n "$nval" ] && [ "$nval" -gt 0 ]
     then
 	fail=false
 	break
@@ -148,11 +153,16 @@ if [ ! -s $tmp/found ]
 then
     # no processes qualify
     #
-    pmconfirm >/dev/null \
-	-header "pmchart view construction failure" \
-	-t "No qualifying processes were found!" \
-	-icon warning \
-	-B "OK"
+    if $dialog
+    then
+	pmconfirm >/dev/null \
+	    -header "pmchart view construction failure" \
+	    -t "No qualifying processes were found!" \
+	    -icon warning \
+	    -B "OK"
+    else
+	echo "pmchart view construction failure: No qualifying processes were found!"
+    fi
     exit
 fi
 
