els-ASAP auto commit file/tag pcp-4.3.2-2.el7.src.rpm

diff --git a/src/Makepkgs b/src/Makepkgs
--- a/src/Makepkgs
+++ b/src/Makepkgs
@@ -25,6 +25,7 @@ dorpm=unknown
 dodeb=unknown
 webapps=false
 docker=false
+check=false
 
 if [ ! -d .git ]
 then
@@ -52,7 +53,7 @@ target=`uname -s | tr 'A-Z' 'a-z'`
 # Apple $gnutool
 # or these lines:
 # *This* tar defaults to:
-# --format=gnu ...
+# --format=gnu ... or --format=posix
 #
 gnu_tool()
 {
@@ -82,7 +83,7 @@ gnu_tool()
 BEGIN				{ want = 0 }
 /This\** tar defaults to:/	{ want=1; next }
 want == 1			{ print; exit }'
-		if grep '[-][-]format=gnu' <$tmp.check >/dev/null
+		if egrep '[-][-]format=(gnu)|(posix)' <$tmp.check >/dev/null
 		then
 		    echo $exec
 		    return 0
@@ -136,6 +137,10 @@ do
 	;;
     -verbose|--verbose)
 	verbose=true
+	shift
+	;;
+    --check)
+	check=true
 	shift
 	;;
     --nonrpm)
@@ -250,13 +255,20 @@ then
 elif [ $target = freebsd ]
 then
     # Python build does not work on FreeBSD 9.3, so skip it
+    # For FreeBSD 10.4 it seems to fail when trying to build Python and
+    # Python3 at the same time ... so skip Python(2)
     #
     case `uname -r`
     in
 	9.3*)
-		# Bog-standard, just without python
+		# Bog-standard, just without python and without python3
 		#
 		configopts="--prefix=/usr --sysconfdir=/etc --localstatedir=/var --with-python=no --with-python3=no"
+		;;
+	10.4*)
+		# Bog-standard, just without python2
+		#
+		configopts="--prefix=/usr --sysconfdir=/etc --localstatedir=/var --with-python=no"
 		;;
 	*)
 		# Bog-standard, as below ...
@@ -589,6 +601,7 @@ debian_build()
     prepare_debian_control
     sanity_check_settings
     debian_buildpackage
+    check_pcp
 
     # success!
     if ! $verbose ; then
@@ -616,25 +629,6 @@ configure_pcp()
     echo
     echo "== Configuring pcp, log is in $LOGDIR/pcp ($configopts)"
 
-    # If we have qtchooser, then force a Qt5 build if Qt5 is installed
-    # ... setting QT_SELECT is only for the configure below, logic similar
-    # to this has to be done again:
-    # (a) in the real build if it does not inherit $QT_SELECT from
-    #     here before running configure again, and
-    # (b) from builddefs so that builds in the source tree also
-    #     work correctly
-    #
-    unset QT_SELECT
-    if which qtchooser >/dev/null 2>&1
-    then
-	if qtchooser -list-versions | grep '^5$' >/dev/null
-	then
-	    export QT_SELECT=5
-	else
-	    export QT_SELECT=4
-	fi
-    fi
-
     rm -f $tmp/failed
     if $verbose
     then
@@ -644,6 +638,22 @@ configure_pcp()
     fi
     [ -f $tmp/failed ] && build_failure Configure
     $cfgonly && exit 0
+}
+
+check_pcp()
+{
+    $check || return 0
+
+    echo
+    echo "== Checking pcp, log is in $LOGDIR/pcp" | tee -a "$LOGDIR/pcp"
+
+    rm -f $tmp/failed
+    if $verbose ; then
+	($MAKE check 2>&1 || touch $tmp/failed) 2>&1 | tee -a "$LOGDIR/pcp"
+    else
+	($MAKE check 2>&1 || touch $tmp/failed) >>"$LOGDIR/pcp" 2>&1
+    fi
+    [ -f $tmp/failed ] && build_failure Checking
 }
 
 default_build()
@@ -762,6 +772,8 @@ if $docker
 then
     packaging_docker
 fi
+
+check_pcp		# static checking (should be last).
 
 # success!
 if ! $verbose ; then
diff --git a/src/qa/1141 b/src/qa/1141
--- a/src/qa/1141
+++ b/src/qa/1141
@@ -17,6 +17,8 @@ policy_name="pcpqaqaqaqa"
 policy_file="$PCP_VAR_DIR/selinux/pcpupstream.pp"
 which sedismod >/dev/null 2>&1 || _notrun "sedismod tool not installed (module disassembly)"
 which semodule >/dev/null 2>&1 || _notrun "semodule tool not installed"
+$sudo semodule -l >/dev/null 2>&1
+[ $? -eq 0 ] || _notrun "semodule -l fails"
 which seinfo >/dev/null 2>&1 || _notrun "seinfo tool not installed"
 [ -f "$policy_file" ] || _notrun "upstream policy package not installed"
 #if a matching module is already installed
@@ -77,17 +79,42 @@ if [ "x$error_line" = "x" ]
 then
     _semodule_remove
     status=0
-    exit
 else
     if [ "x$semodule_x_option" = "x" ]
     then
 	echo "Error from type: $error_line"
     else
-	/usr/libexec/selinux/hll/pp 2>/dev/null $tmp/selinux/$policy_name.pp $tmp/selinux/$policy_name.cil
 	echo "Error on line: $error_line from $policy_name.cil"
-	awk -v error_line="$error_line" \
-	    'FNR==error_line' $tmp/selinux/$policy_name.cil
+	# places where hll/pp is hiding
+	#
+	SEARCH="/usr/libexec/selinux /usr/lib/selinux"
+	pp_path=''
+	for dir in $SEARCH
+	do
+	    if [ -f $dir/hll/pp ]
+	    then
+		pp_path=$dir/hll/pp
+		break
+	    fi
+	done
+	if [ -z "$pp_path" ]
+	then
+	    # no pretty printing for us ...
+	    #
+	    echo "Arrgh: cannot find hll/pp in SEARCH paths \"$SEARCH\""
+	else
+	    $pp_path >$tmp.out 2>&1 $tmp/selinux/$policy_name.pp $tmp/selinux/$policy_name.cil
+	    if [ ! -f $tmp/selinux/$policy_name.cil ]
+	    then
+		cat $tmp.out
+		echo "Arrgh: failed to create $tmp/selinux/$policy_name.cil"
+	    else
+		awk -v error_line="$error_line" \
+			'FNR==error_line' $tmp/selinux/$policy_name.cil
+	    fi
+	fi
     fi
-    exit
 fi
+
+exit
 
diff --git a/src/qa/1211 b/src/qa/1211
--- a/src/qa/1211
+++ b/src/qa/1211
@@ -2,29 +2,24 @@
 # PCP QA Test No. 1211
 # Exercise basic pmseries loading and querying.
 #
-# Copyright (c) 2018 Red Hat.
+# Copyright (c) 2018-2019 Red Hat.
 #
 
 seq=`basename $0`
 echo "QA output created by $seq"
+path=""
 
 # get standard environment, filters and checks
 . ./common.product
 . ./common.filter
 . ./common.check
 
-which pmseries >/dev/null 2>&1 || \
-	_notrun "pmseries command line utility not installed"
-which redis-cli >/dev/null 2>&1 || \
-	_notrun "Redis command line utility not installed"
-redis-cli ping >/dev/null 2>$here/$seq.err
-sts=$?
-msg=`cat $here/$seq.err`
-rm -f $here/$seq.err
-[ $sts -eq 0 ] || _notrun $msg
+_check_series
 
 _cleanup()
 {
+    [ -n "$options" ] && redis-cli $options shutdown
+    _restore_config $PCP_SYSCONF_DIR/pmseries
     cd $here
     $sudo rm -rf $tmp $tmp.*
 }
@@ -32,6 +27,8 @@ _cleanup()
 status=1	# failure is the default!
 series=unknown
 hostname=`hostname`
+redisport=`_find_free_port`
+
 $sudo rm -rf $tmp $tmp.* $seq.full
 trap "_cleanup; exit \$status" 0 1 2 3 15
 
@@ -43,136 +40,193 @@ _filter_source()
     #end
 }
 
+_sort_context()
+{
+    sed -e 's/    Context: //g' -e 's/, /\n/g' | \
+    LC_COLLATE=POSIX sort | \
+    $PCP_AWK_PROG 'BEGIN { printf "    Context: " } {
+	if (count == 0) {printf("%s", $0)} else {printf(", %s", $0)};
+	count++
+    } END { print out }'
+}
+
 # real QA test starts here
-echo "Clearing local cache ..."
-redis-cli flushall
+_save_config $PCP_SYSCONF_DIR/pmseries
+$sudo rm -f $PCP_SYSCONF_DIR/pmseries/*
+
+echo "Start test Redis server ..."
+redis-server --port $redisport > $tmp.redis 2>&1 &
+echo "PING"
+pmsleep 0.125
+options="-p $redisport"
+redis-cli $options ping
 echo
 
 echo "Verify basic load from proc archive"
-pmseries --load "{source.path: \"$here/archives/proc\"}" | _filter_source
+pmseries $options --load "{source.path: \"$here/archives/proc\"}" | _filter_source
+echo
+
+echo "Error handling - load from bad path"
+pmseries $options --load "{source.path: \"/no/such/archive\"}"
+echo
+
+echo "Verify pminfo and pmseries source and series match"
+echo "=> pminfo"
+pminfo -smd --archive $here/archives/proc kernel.all.load
+echo "=> pmseries"
+loaded=`pmseries $options "kernel.all.load{source.name:\"$here/archives/proc\"}"`
+series=fecd5a4b4c6e1273eaa001287a6dd57b7bbd19f7
+source=2cd6a38f9339f2dd1f0b4775bda89a9e7244def6
+if [ "$loaded" != "$series" ]
+then
+    echo "Series identifier mismatch - loaded $loaded, expected $series"
+    exit 1
+fi
+pmseries $options -smd $series
 echo
 
 echo "List all metric names ..."
-pmseries -m | LC_COLLATE=POSIX sort
+pmseries $options -m | LC_COLLATE=POSIX sort
+echo
+
+echo "List some metric names ..."
+pmseries $options -m -g 'hinv*' | LC_COLLATE=POSIX sort
 echo
 
 echo "List all label names ..."
-pmseries -l | LC_COLLATE=POSIX sort
+pmseries $options -l | LC_COLLATE=POSIX sort
+echo
+
+echo "List some label names ..."
+pmseries $options -l -g 'h*' | LC_COLLATE=POSIX sort
 echo
 
 echo "List all context names ..."
-pmseries -c | _filter_source | LC_COLLATE=POSIX sort
+pmseries $options -S | _filter_source | LC_COLLATE=POSIX sort
+echo
+
+echo "List some context names ..."
+pmseries $options -S -g 'bozo*' | _filter_source | LC_COLLATE=POSIX sort
 echo
 
 echo "List all instance names ..."
-pmseries -i | LC_COLLATE=POSIX sort
+pmseries $options -i | LC_COLLATE=POSIX sort
+echo
+
+echo "List some instance names ..."
+pmseries $options -i -g 'sda*' | LC_COLLATE=POSIX sort
 echo
 
 echo "Perform simple name-based query ..."
-pmseries kernel.all.pswitch | LC_COLLATE=POSIX sort
+pmseries $options kernel.all.pswitch | LC_COLLATE=POSIX sort
 echo
 
 echo "Perform simple label-based query ..."
-#pmseries 'kernel.all.load{hostname:"bozo-laptop"}' | LC_COLLATE=POSIX sort
-pmseries 'kernel.all.load{hostname=="bozo-laptop"}' | LC_COLLATE=POSIX sort
+pmseries $options 'kernel.all.load{hostname:"bozo-laptop"}' | LC_COLLATE=POSIX sort
 echo
 
 echo "Perform simple instance-based query ..."
-pmseries 'kernel.all.load{instance.name:"1 minute"}'
+pmseries $options 'kernel.all.load{instance.name:"1 minute"}'
 echo
 
 echo "Perform globbing name-based query (1) ..."
-pmseries 'kernel.all.ps*' | LC_COLLATE=POSIX sort
+pmseries $options 'kernel.all.ps*' | LC_COLLATE=POSIX sort
 echo
 
 echo "Perform globbing name-based query (2) ..."
-pmseries 'kernel*pswitch' | LC_COLLATE=POSIX sort
+pmseries $options 'kernel*pswitch' | LC_COLLATE=POSIX sort
 echo
 
 echo "Perform globbing name-based query (3) ..."
-pmseries 'kernel.all.l*d' | LC_COLLATE=POSIX sort
+pmseries $options 'kernel.all.l*d' | LC_COLLATE=POSIX sort
 echo
 
 echo "Perform globbing instance-based query (1) ..."
-pmseries 'kernel.all.load{instance.name:"1*"}'
+pmseries $options 'kernel.all.load{instance.name:"1*"}'
 echo
 
 echo "Perform globbing instance-based query (2) ... no result"
-pmseries 'kernel.all.load{instance.name:"1\*"}'
+pmseries $options 'kernel.all.load{instance.name:"1\*"}'
 echo "(expect no result)"
 echo
 
 echo "Perform globbing instance-based query (3) ..."
-pmseries 'kernel.all.load{instance.name:"*1*"}'
+pmseries $options 'kernel.all.load{instance.name:"*1*"}'
+echo
+
+echo "Perform globbing instance-based query (4) ..."
+pmseries $options 'disk.partitions.blk*' | LC_COLLATE=POSIX sort
 echo
 
 # kernel.all.load from proc archive (host:bozo-laptop)
-series=3d372f871a4dd73028a7a4f0b05cb927c462b7b8
 echo "Descriptor lookup for a given SeriesID ..."
-pmseries --desc $series
+pmseries $options --desc $series
 echo
 
 echo "Full InDom only for a given SeriesID ..."
-pmseries --fullindom $series
+pmseries $options --fullindom $series
 echo
 
 echo "Full PMID only for a given SeriesID ..."
-pmseries --fullpmid $series
+pmseries $options --fullpmid $series
 echo
 
 echo "All three lookups for a given SeriesID ..."
-pmseries -dIM $series
+pmseries $options -dIM $series
 echo
 
 echo "SourceID lookup for a given SeriesID ..."
-pmseries --source $series
+pmseries $options --sources $source | _filter_source | _sort_context
 echo
 
 echo "Instances lookup for a given SeriesID ..."
-pmseries --instances $series
+pmseries $options --instances $series
 echo
 
 echo "Labels lookup for a given SeriesID ..."
-pmseries --labels $series
+pmseries $options --labels $series
 echo
 
 echo "All lookups for a given SeriesID ..."
-pmseries --all $series
+pmseries $options --all $series
 echo
 
 echo "Values fetch for a single-valued query ..."
-pmseries 'kernel.all.pswitch[count: 30]'
+pmseries $options 'kernel.all.pswitch[count: 30]'
 echo
 
 echo "Values fetch for a multi-valued query ..."
-pmseries 'kernel.all.load[count: 30]'
+pmseries $options 'kernel.all.load[count: 30]'
 echo
 
-exit  # TODO: pmseries frontend is WIP from here
-# TODO: verify pminfo and pmseries source and series match
+echo "Multi-series lookups from a multi-series query ..."
+pmseries $options 'disk.partitions.blk*' | \
+	LC_COLLATE=POSIX sort | \
+	tee -a $tmp.series
+pmseries $options -a `cat $tmp.series`
 
 echo "Perform simple source-based query ..."
-pmseries 'kernel.all.pswitch{source.name:"bozo-laptop"}'
+pmseries $options 'kernel.all.pswitch{source.name:"bozo-laptop"}'
 echo
 
 echo "Error handling - descriptor for bad series identifier"
-pmseries -d no.such.identifier
+pmseries $options -d no.such.identifier
 echo
 
 echo "Error handling - metric name for bad series identifier"
-pmseries -m no.such.identifier
+pmseries $options -m no.such.identifier
 echo
 
 echo "Error handling - instance names for bad series identifier"
-pmseries -i no.such.identifier
+pmseries $options -i no.such.identifier
 echo
 
 echo "Error handling - label names for bad series identifier"
-pmseries -l no.such.identifier
+pmseries $options -l no.such.identifier
 echo
 
 echo "Error handling - query with no matching instance name"
-pmseries 'kernel.all.load{instance.name == "5 mi*"}'
+pmseries $options 'kernel.all.load{instance.name == "5 mi*"}'
 
 # TODO: verify all the time-related keywords
 
diff --git a/src/qa/1362 b/src/qa/1362
--- a/src/qa/1362
+++ b/src/qa/1362
@@ -14,13 +14,18 @@ echo "QA output created by $seq"
 . ./common.check
 
 [ -d $PCP_PMDAS_DIR/postgresql ] || _notrun "postgresql PMDA directory is not installed"
+[ -f $PCP_PMDAS_DIR/postgresql/pmdapostgresql.python ] || _notrun "postgresql PMDA is not installed"
 
 echo '\q' | $sudo -u postgres psql >/dev/null 2>&1
 [ $? -eq 0 ] || _notrun "Cannot run psql as the postgres user, postgresql not installed or running?"
+$sudo -u postgres psql -c "select VERSION();" | grep -s "PostgreSQL 8" > /dev/null
+[ $? -eq 0 ] && _notrun "not testing postgres v8.x, too old"
+
+CONF=$PCP_PMDAS_DIR/postgresql/pmdapostgresql.conf
 
 status=1	# failure is the default!
 $sudo rm -rf $tmp.* $seq.full
-trap "cd $here; rm -rf $tmp.*; exit \$status" 0 1 2 3 15
+trap "cd $here; $sudo mv $CONF.$seq $CONF; _cleanup_pmda postgresql; rm -rf $tmp.*; exit \$status" 0 1 2 3 15
 
 pmdapostgresql_remove()
 {
@@ -35,6 +40,18 @@ pmdapostgresql_install()
 {
     # start from known starting points
     cd $PCP_PMDAS_DIR/postgresql
+    $sudo mv $CONF $CONF.$seq
+    cat <<EOF>$tmp.conf
+[authentication]
+host=local
+port=5432
+dbname=postgres
+user=postgres
+password=password
+osuser=postgres
+EOF
+
+    $sudo mv $tmp.conf $CONF
     $sudo ./Remove >/dev/null 2>&1
     _service pmcd stop 2>&1 | _filter_pcp_stop
 
@@ -42,49 +59,40 @@ pmdapostgresql_install()
     echo "=== postgresql agent installation ===" | tee -a $here/$seq.full
     $sudo ./Install </dev/null >$tmp.out 2>&1
     cat $tmp.out >>$here/$seq.full
-    # filter lines like ...
-    # Check postgresql metrics have appeared ... 4 warnings, 208 metrics and 6839 values
-    # into
-    # Check postgresql metrics have appeared ... X metrics and Y values
-    _filter_pmda_install <$tmp.out \
-    | sed \
-        -e '/^Waiting for pmcd/s/\.\.\.[. ]*$/DOTS/' \
-        -e 's/[0-9][0-9]* warnings, //' \
+    _filter_pmda_install < $tmp.out | sed -e '1,/Updating the PMCD control file/d' \
     | $PCP_AWK_PROG '
-/Check postgresql metrics have appeared/   { if ($7 >= 200) $7 = "X"
-                                          if ($10 >= 5000) $10 = "Y"
+/Check postgresql metrics have appeared/   { if ($7 < 20) $7 = "X"
+                                          if ($9 >= 200) $9 = "Y"
+                                          if ($12 >= 7000) $12 = "Z"
                                         }
                                         { print }'
 }
 
 _prepare_pmda postgresql
-# note: _restore_auto_restart pmcd done in _cleanup_pmda()
-trap "_cleanup_pmda postgresql; exit \$status" 0 1 2 3 15
 
+# note: _restore_auto_restart pmcd done in _cleanup_pmda()
 _stop_auto_restart pmcd
 
 # real QA test starts here
 pmdapostgresql_install
 
 echo;echo == check initial fetch
-pminfo -f postgresql.recovery.is_in_recovery >/dev/null 2>&1 || exit
+pminfo -f postgresql.stat.activity.usename >/dev/null 2>&1 || exit
 echo OK
 
-echo === signaling pmdapostgresql to disconnect
-pid=`$PCP_PS_PROG $PCP_PS_ALL_FLAGS | grep "perl $PCP_PMDAS_DIR.*pmdapostgresql" | fgrep -v grep | awk '{print $2}'`
-# echo pid is $pid
-$sudo kill -USR1 $pid
+echo === restart postgresql service
+$sudo service postgresql restart >>$here/$seq.full 2>&1
 
 sleep 1
 
 echo === checking log for disconnect messages
-pminfo -f postgresql.recovery.is_in_recovery >/dev/null 2>&1
-grep -i disconnect $PCP_LOG_DIR/pmcd/postgresql.log | sed -e 's/^.*WARN/WARN/'
+pminfo -f postgresql.stat.activity.usename >/dev/null 2>&1
+grep -i "Warning: connection lost" $PCP_LOG_DIR/pmcd/postgresql.log | sed -e 's/^.*Warning/Warning/'
 
 sleep 2
 
 echo;echo == fetch again .. should have reconnected
-pminfo -f postgresql.recovery.is_in_recovery >/dev/null 2>&1 || exit
+pminfo -f postgresql.stat.activity.usename >/dev/null 2>&1 | exit
 echo OK
 
 echo "PMDA log file ..." >>$here/$seq.full
diff --git a/src/src/pmdas/postgresql/Install b/src/src/pmdas/postgresql/Install
--- a/src/src/pmdas/postgresql/Install
+++ b/src/src/pmdas/postgresql/Install
@@ -1,5 +1,6 @@
 #! /bin/sh
 #
+# Copyright (c) 2018 Red Hat.  All Rights Reserved.
 # Copyright (c) 2011 Aconex.  All Rights Reserved.
 # 
 # This program is free software; you can redistribute it and/or modify it
@@ -19,21 +20,48 @@
 . $PCP_SHARE_DIR/lib/pmdaproc.sh
 
 iam=postgresql
-perl_opt=true
+domain=110
+python_opt=true
 daemon_opt=false
 
-perl -e "use DBI" 2>/dev/null
-if test $? -ne 0; then
-    echo "Perl database interface (DBI) is not installed"
+conf=$PCP_PMDAS_DIR/$iam/pmdapostgresql.conf
+if [ ! -f "$conf" ]; then
+    echo "Error: missing config file \"$conf\""
     status=1
     exit
 fi
 
-perl -e "use DBD::Pg" 2>/dev/null
-if test $? -ne 0; then
-    echo "Postgres database driver (DBD::Pg) is not installed"
-    status=1
-    exit
+eval `grep "^osuser=" $conf`
+if [ -n "$osuser" ]; then
+    echo "OS user defined in $conf is \"$osuser\""
+    if ! id $osuser >/dev/null 2>&1; then
+        echo "Error: no such user \"$osuser\" on this system"
+        status=1
+        exit
+    fi
+
+    gid=`id $osuser | sed -e 's/^.*gid=//' -e 's/(.*$//'`
+    echo "group id for user \"$osuser\" is \"$gid\""
+
+    mkdir -p "$PCP_VAR_DIR/config/pmda" 2>/dev/null
+    indoms="0 1 2 3 4 5 6 7 8 9 10 11 12"
+    for indom in $indoms
+    do
+        failed=false
+        c="$PCP_VAR_DIR/config/pmda/$domain.$indom"
+        if [ ! -f "$c" ]; then
+            if touch $c >/dev/null 2>&1; then
+                # TODO need a pmda cache init function
+                echo "2 0 2147483647" >> $c # standard v2 header
+                chmod 664 "$c"
+                chgrp $gid "$c"
+            else
+                echo "Error: failed to create indom persistance file \"$c\""
+                status=1
+                exit
+            fi
+        fi
+    done
 fi
 
 pmdaSetup
