els-ASAP auto commit file/tag pcp-3.10.3-3.el6.src.rpm

diff --git a/src/Makepkgs b/src/Makepkgs
--- a/src/Makepkgs
+++ b/src/Makepkgs
@@ -35,7 +35,9 @@ fi
 
 # Find where a GNU tool is hiding, look for this line:
 # "Report bugs to <bug-$gnutool@gnu.org>"
-# at the end of the $gnutool --help output
+# or this line:
+# "FreeBSD $gnutool YYYYMMDD"
+# in the $gnutool --help output
 #
 gnu_tool()
 {
@@ -52,13 +54,17 @@ gnu_tool()
     then
 	for command in $oldcmd $@
 	do
-	    if $command --help 2>&1 | grep -q bug-$oldcmd@gnu.org
+	    exec=`which $command 2>/dev/null`
+	    if [ -n "$exec" ]
 	    then
-		which $command 2>/dev/null
-		return 0
+		if $command --help 2>&1 | egrep -q "(bug-$oldcmd@gnu.org)|(FreeBSD $gnutool)|(NetBSD $gnutool)"
+		then
+		    echo $exec
+		    return 0
+		fi
 	    fi
 	done
-	echo "$prefix: can't find GNU $oldcmd in the commands $oldcmd or $@"
+	echo >&2 "$prefix: can't find GNU $oldcmd in the commands $oldcmd or $@"
 	[ $prefix = Error ] && exit 1
 	return 1
     fi
@@ -70,7 +76,7 @@ gnu_tool()
     command=`which $envvar 2>/dev/null`
     if [ -z "$command" ]
     then
-	echo "$prefix: $oldcmd (from the environment) does not exist!" >&2
+	echo >&2 "$prefix: $oldcmd (from the environment) does not exist!"
 	[ $prefix = Error ] && exit 1
 	return 1
     fi
@@ -80,24 +86,35 @@ gnu_tool()
 
 export MAKE=`gnu_tool Error "$MAKE" make gmake`
 export TAR=`gnu_tool Warning "$TAR" tar gtar gnutar`
-[ -z "$TAR" ] && export ZIP=`gnu_tool Error "$ZIP" gzip gnuzip`
+export ZIP=`gnu_tool Error "$ZIP" gzip gnuzip`
+
+# check if tar supports --transform else we must use git-archive later on (e.g. RHEL5)
+[ ! -z "$TAR" ] && $TAR --help | 2>&1 grep -q transform || USE_GIT_ARCHIVE=1
 
 tmp=`mktemp -d /tmp/pcp.XXXXXXXXX` || exit 1
 trap "rm -rf $tmp" 0 1 2 3 15
 
-# Bog-standard options suitable for a package on any platform.
-# Command line can be used to extend this set, and any whacko
-# platform-specific requirements are also appended later on.
-#
 configure=./configure
-configopts="--prefix=/usr --sysconfdir=/etc --localstatedir=/var --with-rcdir=/etc/init.d"
 target=`uname -s | cut -c-5 | tr 'A-Z' 'a-z'`
+
+if [ ! -x /usr/bin/rpmbuild ]
+then
+    # Bog-standard options suitable for a package on any platform.
+    # Command line can be used to extend this set, and any unusual
+    # platform-specific requirements are also appended later on.
+    configopts="--prefix=/usr --sysconfdir=/etc --localstatedir=/var"
+else
+    # On RPM-based platforms, rpm macros provide an excellent set of defaults.
+    # This set is based on Fedora 22 %configure macro from /usr/lib/rpm/macros,
+    # and is known to work as far back as RHEL5.
+    configopts=`rpmbuild --eval '--prefix=%{_prefix} --exec-prefix=%{_exec_prefix} --bindir=%{_bindir} --sbindir=%{_sbindir} --sysconfdir=%{_sysconfdir} --datadir=%{_datadir} --includedir=%{_includedir} --libdir=%{_libdir} --libexecdir=%{_libexecdir} --localstatedir=%{_localstatedir} --sharedstatedir=%{_sharedstatedir} --mandir=%{_mandir}' 2>/dev/null`
+fi
 
 for opt in $*
 do
     case "$opt" in
     -clean|--clean)
-	# we always clean nowadays
+	# we always clean nowadays, so silently ignore
 	shift
 	;;
     -verbose|--verbose)
@@ -128,29 +145,29 @@ done
 if [ "$nonrpm" = "unknown" ]
 then
     nonrpm=true
-    test -f /usr/bin/rpmbuild && nonrpm=false
+    test -x /usr/bin/rpmbuild && nonrpm=false
 fi
 if [ "$nondeb" = "unknown" ]
 then
     nondeb=true
-    test -f /usr/bin/dpkg-buildpackage && nondeb=false
+    test -x /usr/bin/dpkg-buildpackage && nondeb=false
 fi
 
 case "$target"
 in
     mingw)
+	nonrpm=true
 	configure="mingw64-configure"
-	configopts="$configopts --disable-ssp"
+	configopts="$configopts --disable-ssp --without-threads"
+	MAKE="mingw64-make"
 	;;
     linux)
 	ARCH=`uname -m`
-	[ -f /etc/slackware-version -a "$ARCH" = x86_64 ] && \
-	configopts="$configopts --libdir=/usr/lib64"
+	[ -f /etc/slackware-version -a "$ARCH" = x86_64 ] && configopts="$configopts --libdir=/usr/lib64"
 	;;
     sunos)
 	ARCH=`isainfo -k`
-	[ "$ARCH" = amd64 -o "$ARCH" = sparcv9 ] && \
-	configopts="$configopts --libdir=/usr/lib/64"
+	[ "$ARCH" = amd64 -o "$ARCH" = sparcv9 ] && configopts="$configopts --disable-ssp --libdir=/usr/lib/64"
 	;;
 esac
 
@@ -182,15 +199,43 @@ clean_packaging()
     rm -rf "$SRCDIR" "$SRCTAR" .gitcensus
 }
 
+fix_version()
+{
+    if [ -f "$1" -a -f "$2" ]
+    then
+	# as expected, both present
+	if diff "$1" "$2" >/dev/null 2>&1
+	then
+	    :
+	else
+	    # must be using git-archive(1) and VERSION.pcp has been
+	    # modified, e.g. by pcp-daily script ... use the modified
+	    # one to bump the build number in the packages
+	    #
+	    cp "$1" "$2"
+	fi
+    else
+	echo "Arrgh ... expect both these to exist ..."
+	ls -l "$1" "$2"
+	exit 1
+    fi
+}
+
 # Generate a list of all the files git knows about, create the
 # source tarball and then unpack it.  We'll then do the package
 # build in a guaranteed pristine environment.
 #
 src_tar_build()
 {
-    if [ -z "$TAR" ]
+    if [ -z "$TAR" -o ! -z "$USE_GIT_ARCHIVE" ]
     then
-	# no GNU tar is available, use git-archive(1) - no local changes
+	# no suitable GNU tar is available, use git-archive(1) - no local changes
+	if git status -s src man | grep '^.M'
+	then
+	    echo "Arrgh, modified src files and either no tar ($TAR) or no --transform"
+	    echo "support in tar, so local changes would not be included in the build."
+	    exit 1
+	fi
 	git archive --format=tar --prefix=$source/ HEAD | $ZIP > $SRCTAR
     else
 	# build git file list and make tarball by hand to pick up any changes
@@ -278,11 +323,16 @@ debian_buildpackage()
     echo "== Building deb packages using dpkg-buildpackage"
 
     SUDO=${SUDO:-fakeroot}
+    # Don't try to sign packages unless you're Nathan Scott!
+    # Otherwise we risk Makepkgs exiting with a non-zero status.
+    #
+    sign=''
+    [ "`id -un`" != "nathans" ] && sign='-us -uc'
     rm -f $tmp/failed
     if $verbose ; then
-	(dpkg-buildpackage -r$SUDO || touch $tmp/failed) | tee -a $LOGDIR/pcp
+	(dpkg-buildpackage $sign -r$SUDO || touch $tmp/failed) 2>&1 | tee -a $LOGDIR/pcp
     else
-	(dpkg-buildpackage -r$SUDO || touch $tmp/failed) >> $LOGDIR/pcp
+	(dpkg-buildpackage $sign -r$SUDO || touch $tmp/failed) >>$LOGDIR/pcp 2>&1
     fi
     [ -f $tmp/failed ] && build_failure debian buildpackage
 }
@@ -291,10 +341,12 @@ prepare_debian_sources()
 {
     # shortcut for dpkg-buildpackage which does everything itself from here
     SRCDIR="${topdir}/build/deb"
+    rm -rf "${SRCDIR}"
     mkdir -p "$SRCDIR" 2>/dev/null
     cd "$SRCDIR" || exit 1
     $TAR -zxf "$SRCTAR" || exit 1
     cd "$SRCDIR/$source" || exit 1
+    fix_version ${topdir}/VERSION.pcp VERSION.pcp
 }
 
 prepare_debian_control()
@@ -303,9 +355,9 @@ prepare_debian_control()
     echo "== Preparing source tree for dpkg-buildpackage"
     rm -f $tmp/failed debian/control
     if $verbose ; then
-	($MAKE -C debian control 2>&1 || touch $tmp/failed) | tee -a $LOGDIR/pcp
+	($MAKE -C debian control 2>&1 || touch $tmp/failed) 2>&1 | tee -a $LOGDIR/pcp
     else
-	($MAKE -C debian control 2>&1 || touch $tmp/failed) >> $LOGDIR/pcp
+	($MAKE -C debian control 2>&1 || touch $tmp/failed) >>$LOGDIR/pcp 2>&1
     fi
     [ -f $tmp/failed ] && build_failure debian control
 }
@@ -328,6 +380,7 @@ prepare_build()
     if [ ! -d "$SRCDIR" ]; then
 	# extract gzipped tar archive
 	$TAR -xz --file="$SRCTAR" || exit 1
+	fix_version VERSION.pcp $SRCDIR/VERSION.pcp
     fi
 }
 
@@ -339,9 +392,9 @@ configure_pcp()
     rm -f $tmp/failed
     if $verbose
     then
-	($configure $configopts 2>&1 || touch $tmp/failed) | tee -a $LOGDIR/pcp
+	($configure $configopts 2>&1 || touch $tmp/failed) 2>&1 | tee -a $LOGDIR/pcp
     else
-	($configure $configopts 2>&1 || touch $tmp/failed) >> $LOGDIR/pcp
+	($configure $configopts 2>&1 || touch $tmp/failed) >>$LOGDIR/pcp 2>&1
     fi
     [ -f $tmp/failed ] && build_failure Configure
 }
@@ -353,9 +406,9 @@ default_build()
 
     rm -f $tmp/failed
     if $verbose ; then
-	($MAKE default_pcp 2>&1 || touch $tmp/failed) | tee -a $LOGDIR/pcp
+	($MAKE default_pcp 2>&1 || touch $tmp/failed) 2>&1 | tee -a $LOGDIR/pcp
     else
-	($MAKE default_pcp 2>&1 || touch $tmp/failed) >> $LOGDIR/pcp
+	($MAKE default_pcp 2>&1 || touch $tmp/failed) >>$LOGDIR/pcp 2>&1
     fi
     [ -f $tmp/failed ] && build_failure Make default_pcp
 }
@@ -367,9 +420,9 @@ packaging_pcp()
 
     rm -f $tmp/failed
     if $verbose ; then
-	($MAKE -C build pack_pcp 2>&1 || touch $tmp/failed) | tee -a $LOGDIR/pcp
+	($MAKE -C build pack_pcp 2>&1 || touch $tmp/failed) 2>&1 | tee -a $LOGDIR/pcp
     else
-	($MAKE -C build pack_pcp 2>&1 || touch $tmp/failed) >> $LOGDIR/pcp
+	($MAKE -C build pack_pcp 2>&1 || touch $tmp/failed) >>$LOGDIR/pcp 2>&1
     fi
     [ -f $tmp/failed ] && build_failure Packaging via pack_pcp
 }
@@ -382,9 +435,9 @@ packaging_rpm()
     rm -f $tmp/failed
     export DIST_ROOT=${topdir}/build/rpm/${source}
     if $verbose ; then
-	($MAKE -C build/rpm pack_pcp 2>&1 || touch $tmp/failed) | tee -a $LOGDIR/pcp
+	($MAKE -C build/rpm pack_pcp 2>&1 || touch $tmp/failed) 2>&1 | tee -a $LOGDIR/pcp
     else
-	($MAKE -C build/rpm pack_pcp 2>&1 || touch $tmp/failed) >> $LOGDIR/pcp
+	($MAKE -C build/rpm pack_pcp 2>&1 || touch $tmp/failed) >>$LOGDIR/pcp 2>&1
     fi
     [ -f $tmp/failed ] && build_failure Packaging RPMs via pack_pcp
 }
diff --git a/src/qa/555 b/src/qa/555
--- a/src/qa/555
+++ b/src/qa/555
@@ -29,10 +29,14 @@ in
 	;;
 esac
 
-rm -f $seq.full
+$sudo rm -f $seq.full /tmp/syslog.full /tmp/syslog.out
 
 signal=$PCP_BINADM_DIR/pmsignal
 status=1	# failure is the default!
+
+# sometimes don't want the -E variant of sudo, as this fails to run
+# service rsyslog correctly (at least on bozo)
+sudo_no_E=`which sudo`
 
 update_config=true
 systemctl=false
@@ -41,7 +45,7 @@ if [ -f /etc/rsyslog.conf -a -f /var/run/*syslogd.pid ]
 then
     # smells like rsyslogd
     #
-    ( echo "smells like rsyslogd"; ls -l /etc/rsyslog.conf /var/run/*syslogd.pid ) >>$seq.full
+    ( echo "smells like rsyslogd"; ls -l /etc/rsyslog.conf /var/run/*syslogd.pid ) >>/tmp/syslog.full 2>&1
     daemon=rsyslogd
     config=/etc/rsyslog.d/pcpqa.conf
     update_config=false
@@ -69,19 +73,22 @@ then
 	    exit 1
 	fi
     fi
-    echo "upstart=$upstart" >>$seq.full
-    echo "systemctl=$systemctl" >>$seq.full
-    echo "init=$init" >>$seq.full
 elif [ -f /etc/syslog.conf ]
 then
     # regular old syslogd
     #
-    ( echo "smells like old syslogd"; ls -l /etc/rsyslog.conf )  >>$seq.full
+    ( echo "smells like old syslogd"; ls -l /etc/rsyslog.conf ) >>/tmp/syslog.full 2>&1
     daemon=syslogd
     config=/etc/syslog.conf
 else
     _notrun "No /etc/*syslog.conf -- probably using a different syslog package"
 fi
+
+echo "upstart=$upstart" >>/tmp/syslog.full
+echo "systemctl=$systemctl" >>/tmp/syslog.full
+echo "init=$init" >>/tmp/syslog.full
+echo "update_config=$update_config" >>/tmp/syslog.full
+echo "daemon=$daemon" >>/tmp/syslog.full
 
 # avoid systemd/systemctl wrapper
 #
@@ -90,18 +97,18 @@ fi
 
 cleanup()
 {
-    if [ -f $config.$seq ]; then
+    if [ -f $tmp.setup ]; then
 	if $update_config
 	then
-	    $sudo mv $config.$seq $config
+	    [ -f $config.$seq ] && $sudo mv $config.$seq $config
 	else
-	    $sudo rm $config.$seq $config
+	    $sudo rm -f $config
 	fi
 	if [ $daemon = rsyslogd ]
 	then
 	    if $upstart
 	    then
-		$sudo service rsyslog restart >>$seq.full 2>&1
+		$sudo_no_E service rsyslog restart >>/tmp/syslog.full 2>&1
 	    elif $systemctl
 	    then
 		$sudo systemctl restart rsyslog
@@ -109,14 +116,16 @@ cleanup()
 		# kill should be enough, but restart to be sure
 		#
 		# $sudo kill -HUP `cat /var/run/rsyslogd.pid` || exit
-		$sudo $init restart >>$seq.full 2>&1
+		$sudo $init restart >>/tmp/syslog.full 2>&1
 	    fi
 	else
 	    $sudo $signal -a -s HUP $daemon || exit
 	fi
+	rm $tmp.setup
     fi
+    [ -f /tmp/syslog.full ] && cp /tmp/syslog.full $seq.full
+    $sudo rm -f /tmp/syslog.out
     rm -f $tmp.*
-    $sudo rm -f /tmp/syslog
 }
 trap "cleanup; exit \$status" 0 1 2 3 15
 
@@ -128,32 +137,31 @@ setup()
     # let rsyslog create it, to ensure any security labels setup
     if [ $daemon != rsyslogd ]
     then
-	$sudo cp /dev/null /tmp/syslog || exit
-	$sudo chmod 666 /tmp/syslog || exit
+	$sudo cp /dev/null /tmp/syslog.out || exit
+	$sudo chmod 666 /tmp/syslog.out || exit
     fi
+    touch $tmp.setup
     if $update_config
     then
 	$sudo mv $config $config.$seq || exit
-    else
-	$sudo touch $config.$seq
     fi
-    echo '*.*  /tmp/syslog' >$tmp.syslog.conf
+    echo '*.*  /tmp/syslog.out' >$tmp.syslog.conf
     $sudo cp $tmp.syslog.conf $config || exit
-    echo "config=$config" >>$seq.full
-    $sudo cat $config >>$seq.full
+    echo "config=$config" >>/tmp/syslog.full
+    $sudo cat $config >>/tmp/syslog.full
     if [ $daemon = rsyslogd ]
     then
 	if $upstart
 	then
-	    $sudo service rsyslog restart >>$seq.full 2>&1
+	    $sudo_no_E service rsyslog restart >>/tmp/syslog.full 2>&1
 	elif $systemctl
 	then
-	    $sudo systemctl restart rsyslog >>$seq.full 2>&1
+	    $sudo systemctl restart rsyslog >>/tmp/syslog.full 2>&1
 	else
 	    # kill should be enough, but restart to be sure
 	    #
 	    # $sudo kill -HUP `cat /var/run/rsyslogd.pid` || exit
-	    $sudo $init restart >>$seq.full 2>&1
+	    $sudo $init restart >>/tmp/syslog.full 2>&1
 	fi
     else
 	$sudo $signal -a -s HUP $daemon || exit
@@ -161,11 +169,11 @@ setup()
 }
 
 # real QA test starts here
-echo "ps before setup ..." >>$seq.full
-$PCP_PS_PROG $PCP_PS_ALL_FLAGS | egrep '([P]ID)|([s]yslog)' >>$seq.full
+echo "ps before setup ..." >>/tmp/syslog.full
+$PCP_PS_PROG $PCP_PS_ALL_FLAGS | egrep '([P]ID)|([s]yslog)' >>/tmp/syslog.full
 setup
-echo "ps after setup ..." >>$seq.full
-$PCP_PS_PROG $PCP_PS_ALL_FLAGS | egrep '([P]ID)|([s]yslog)' >>$seq.full
+echo "ps after setup ..." >>/tmp/syslog.full
+$PCP_PS_PROG $PCP_PS_ALL_FLAGS | egrep '([P]ID)|([s]yslog)' >>/tmp/syslog.full
 
 # syslog	logger -p
 # 5D		daemon.notice		<--- default
@@ -180,45 +188,49 @@ $PCP_PS_PROG $PCP_PS_ALL_FLAGS | egrep '([P]ID)|([s]yslog)' >>$seq.full
 
 cat <<'End-of-File' >$tmp.conf
 // errors
-hinv.ncpu > 0 -> syslog "-t";
-hinv.ncpu > 0 -> syslog "-ttag extra";
-hinv.ncpu > 0 -> syslog "-t" "tag extra";
-hinv.ncpu > 0 -> syslog "-p";
-hinv.ncpu > 0 -> syslog "-pinfo extra" "-pinfo [6D]" "{1}";
-hinv.ncpu > 0 -> syslog "-p" "info extra" "-pinfo [6D]" "{2}";
-hinv.ncpu > 0 -> syslog "-p" "evil" "-t" "bogus" "bad -p evil and -t" "{3}";
-hinv.ncpu > 0 -> syslog "-p" "evil.info" "bad facil for -p evil.info [6D]" "{4}";
-hinv.ncpu > 0 -> syslog "-p" "user.evil" "bad pri for -p user.evil [5B]" "{5}";
+e1 = hinv.ncpu > 0 -> syslog "-t";
+e2 = hinv.ncpu > 0 -> syslog "-ttag extra";
+e3 = hinv.ncpu > 0 -> syslog "-t" "tag extra";
+e4 = hinv.ncpu > 0 -> syslog "-p";
+e5 = hinv.ncpu > 0 -> syslog "-pinfo extra" "-pinfo [6D]" "{1}";
+e6 = hinv.ncpu > 0 -> syslog "-p" "info extra" "-pinfo [6D]" "{2}";
+e7 = hinv.ncpu > 0 -> syslog "-p" "evil" "-t" "bogus" "bad -p evil and -t" "{3}";
+e8 = hinv.ncpu > 0 -> syslog "-p" "evil.info" "bad facil for -p evil.info [6D]" "{4}";
+e9 = hinv.ncpu > 0 -> syslog "-p" "user.evil" "bad pri for -p user.evil [5B]" "{5}";
 
 // OK
-hinv.ncpu > 0 -> syslog "-t" "foo" "-p" "user.notice" "-t & -pinfo, 4 args [5B]" "{6}";
-hinv.ncpu > 0 -> syslog "-t" "foo" "-puser.notice" "-t & -pinfo, 3 args [5B]" "{7}";
-hinv.ncpu > 0 -> syslog "-tfoo" "-pinfo" "-t & -pinfo, 2 args [6D]" "{8}";
-hinv.ncpu > 0 -> syslog "-p" "user.info" "-p user.info, 2 args [6B]" "{9}";
-hinv.ncpu > 0 -> syslog "-pdaemon.info" "-pdaemon.info, 1 arg [6D]" "{10}";
-hinv.ncpu > 0 -> syslog "-t" "foo" "-t 2 args" "{11}";
-hinv.ncpu > 0 -> syslog "-tfoo" "-t 1 arg" "{12}";
-hinv.ncpu > 0 -> syslog "no -t or -p args" "{13}";
+o1 = hinv.ncpu > 0 -> syslog "-t" "foo" "-p" "user.notice" "-t & -pinfo, 4 args [5B]" "{6}";
+o2 = hinv.ncpu > 0 -> syslog "-t" "foo" "-puser.notice" "-t & -pinfo, 3 args [5B]" "{7}";
+o3 = hinv.ncpu > 0 -> syslog "-tfoo" "-pinfo" "-t & -pinfo, 2 args [6D]" "{8}";
+o4 = hinv.ncpu > 0 -> syslog "-p" "user.info" "-p user.info, 2 args [6B]" "{9}";
+o5 = hinv.ncpu > 0 -> syslog "-pdaemon.info" "-pdaemon.info, 1 arg [6D]" "{10}";
+o6 = hinv.ncpu > 0 -> syslog "-t" "foo" "-t 2 args" "{11}";
+o7 = hinv.ncpu > 0 -> syslog "-tfoo" "-t 1 arg" "{12}";
+o8 = hinv.ncpu > 0 -> syslog "no -t or -p args" "{13}";
 
 
 // OK + holdoff
-hinv.ncpu > 0 -> syslog 1 min "-t" "foo" "-p" "local0.notice" "-t & -pinfo, 4 args [5Q] + holdoff" "{14}";
-hinv.ncpu > 0 -> syslog 1 min "-t" "foo" "-plocal0.notice" "-t & -pinfo, 3 args [5Q] + holdoff" "{14}";
-hinv.ncpu > 0 -> syslog 1 min "-tfoo" "-pinfo" "-t & -pinfo, 2 args [6D] + holdoff" "{15}";
-hinv.ncpu > 0 -> syslog 1 min "-p" "local0.info" "-p user.info, 2 args [6Q] + holdoff" "{16}";
-hinv.ncpu > 0 -> syslog 1 min "-pdaemon.info" "-pdaemon.info, 1 arg [6D] + holdoff" "{17}";
-hinv.ncpu > 0 -> syslog 1 min "-t" "foo" "-t 2 args + holdoff" "{18}";
-hinv.ncpu > 0 -> syslog 1 min "-tfoo" "-t 1 arg + holdoff" "{19}";
-hinv.ncpu > 0 -> syslog 1 min "no -t or -p args + holdoff" "{20}";
+h1 = hinv.ncpu > 0 -> syslog 1 min "-t" "foo" "-p" "local0.notice" "-t & -pinfo, 4 args [5Q] + holdoff" "{14}";
+h2 = hinv.ncpu > 0 -> syslog 1 min "-t" "foo" "-plocal0.notice" "-t & -pinfo, 3 args [5Q] + holdoff" "{14}";
+h3 = hinv.ncpu > 0 -> syslog 1 min "-tfoo" "-pinfo" "-t & -pinfo, 2 args [6D] + holdoff" "{15}";
+h4 = hinv.ncpu > 0 -> syslog 1 min "-p" "local0.info" "-p user.info, 2 args [6Q] + holdoff" "{16}";
+h5 = hinv.ncpu > 0 -> syslog 1 min "-pdaemon.info" "-pdaemon.info, 1 arg [6D] + holdoff" "{17}";
+h6 = hinv.ncpu > 0 -> syslog 1 min "-t" "foo" "-t 2 args + holdoff" "{18}";
+h7 = hinv.ncpu > 0 -> syslog 1 min "-tfoo" "-t 1 arg + holdoff" "{19}";
+h8 = hinv.ncpu > 0 -> syslog 1 min "no -t or -p args + holdoff" "{20}";
 
 End-of-File
 
-pmie -t 2sec -T 5sec >$tmp.log 2>&1 -c $tmp.conf &
+pmie -v -t 2sec -T 5sec >$tmp.log 2>&1 -c $tmp.conf &
 wait
 
 sed <$tmp.log \
+    -e '/^$/d' \
+    -e '/^[a-z][0-9][0-9]*: /d' \
     -e "/Info: evaluator exiting/d" \
     -e "s;$tmp;TMP;;"
+echo "=== pmie output ===" >>/tmp/syslog.full
+cat $tmp.log >>/tmp/syslog.full
 
 sleep 5
 echo
@@ -227,23 +239,24 @@ echo
 # note - agetty lines noticed on canary with SLES9 SP1 beta2
 # note - DHCPDISCOVER lines noticed on kenj-laptop with Ubuntu 8.10
 #
-echo "=== all of syslog ===" >>$seq.full
-$sudo cat /tmp/syslog >>$seq.full
-echo >>$seq.full
-echo "=== syslog for pid $! ===" >>$seq.full
+echo "=== all of syslog ===" >>/tmp/syslog.full
+ls -l /tmp/syslog.full >>/tmp/syslog.full
+$sudo cat /tmp/syslog.out >>/tmp/syslog.full
+echo >>/tmp/syslog.full
+echo "=== syslog for pid $! ===" >>/tmp/syslog.full
 # More recent syslog format seen on Ubuntu 11.04
 # (high-precision rsyslog timestamps, traditional-mode no longer enabled)
 # 2011-07-09T10:38:40+10:00 HOST pcp-pmie[PID]: 
 #
-$sudo grep '\['$!']:' /tmp/syslog \
-| tee -a $seq.full \
+$sudo grep '\['$!']:' /tmp/syslog.out \
+| tee -a /tmp/syslog.full \
 | sed \
     -e 's/^[A-Z][a-z][a-z]  *[0-9][0-9]* [0-9][0-9]:[0-9][0-9]:[0-9][0-9]/DATE/' \
     -e 's/^[0-9][0-9][0-9][0-9]-[0-9][0-9]*-[0-9][0-9]*T[0-9][0-9]:[0-9][0-9]:[0-9][0-9][^ ]* /DATE /' \
     -e "s/\\[$!]/[PID]/" \
     -e "s/`hostname | sed -e 's/\..*//'` /HOST /" \
     -e 's/[0-9][A-Z]:HOST/HOST/' \
-    -e '/ sudo: .*syslog$/d' \
+    -e '/ sudo: .*syslog.out$/d' \
     | LC_COLLATE=POSIX sort \
     | uniq
 
diff --git a/src/qa/660 b/src/qa/660
--- a/src/qa/660
+++ b/src/qa/660
@@ -2,26 +2,19 @@
 # PCP QA Test No. 660
 # checks basic pmwebd functionality
 #
-# Copyright (c) 2013 Red Hat, Inc.  All Rights Reserved.
+# Copyright (c) 2013-2014 Red Hat, Inc.  All Rights Reserved.
 #
 seq=`basename $0`
 echo "QA output created by $seq"
 
-# get standard environment, filters and checks
-. ./common.product
-. ./common.filter
-. ./common.check
+. ./common.webapi
 
-
-which pmproxy >/dev/null 2>&1 || _notrun "No pmwebd binary installed"
 which curl >/dev/null 2>&1 || _notrun "No curl binary installed"
-echo curl ok
 # nb: wget dispreferred because of its processing of .. relative links,
-# so it's harder to stress pmwebd's base-directory-escapig logic
+# so it's harder to stress pmwebd's base-directory-escaping logic
 
-pyscript=src/test_webapi.python
+pyscript=src/test_webapi.py
 python $pyscript --version 2>/dev/null || _notrun "python/modules missing"
-echo python ok
 
 $sudo rm -fr $tmp.dir
 $sudo rm -f $tmp.*
@@ -30,7 +23,6 @@ rm -f $seq.full
 signal=$PCP_BINADM_DIR/pmsignal
 status=1	# failure is the default!
 username=`id -u -n`
-trap "_cleanup" 0 1 2 3 15
 
 _cleanup()
 {
@@ -38,113 +30,143 @@ _cleanup()
     $sudo rm -f $tmp.*
     $sudo $signal -a pmwebd >/dev/null 2>&1
     $sudo $PCP_RC_DIR/pmwebd restart >/dev/null 2>&1
-    exit $status
 }
+trap "_cleanup; exit \$status" 0 1 2 3 15
 
+#
+# on one QA host (bozo) where bind is running (may or not be related)
+# the test emits
+# * Hostname was NOT found in DNS cache
+# instead of
+# * About to connect() to LOCALHOST port 44323 (####)
+# but otherwise works.
+# This error message apparently comes from deep inside the non-PCP code.
+# So filter to remove both variants to ensure the test is deemed to
+# have passed.
+#
+# Also there is some other noise from a similar source but different
+# causes, e.g.
+#
+# * HTTP 1.1 or later with persistent connection, pipelining supported
+# * additional stuff not fine transfer.c:1037: 0 0
+# WARNING: gnome-keyring:: couldn't connect to: ...
+# * [othewise blank line]
+# [blank line]
+#
 _filter()
 {
-    tee -a $seq.full \
-    | sed -e 's,#[0-9]*,####,g' -e 's/PMWEBAPI error,.*/PMWEBAPI error, XXX/g'
+    sed \
+	-e '/Hostname was NOT found in DNS cache/d' \
+	-e '/About to connect() to LOCALHOST port 44323 (####)/d' \
+	-e '/^\* HTTP 1.1 or later with persistent connection/d' \
+	-e '/^\* additional stuff not fine/d' \
+	-e '/WARNING: gnome-keyring::/d' \
+	-e '/^\*$/d' \
+	-e '/^[ 	]*$/d'
 }
 
-
-unset http_proxy
-unset HTTP_PROXY
+ipv6local=`_ipv6_localhost`
+echo "ipv6local=$ipv6local" >>$seq.full
 
 $sudo $PCP_RC_DIR/pmwebd stop >/dev/null 2>&1
 $sudo $signal -a pmwebd >/dev/null 2>&1
 
-webargs="-U $username -f"
+webargs="-U $username"
 
 echo | tee -a $seq.full
-echo "=== 1. pmwebd default startup  ===" | tee -a $seq.full
-echo "$PCP_BINADM_DIR/pmwebd $webargs -l $tmp.out" >>$seq.full
-$PCP_BINADM_DIR/pmwebd $webargs -l $tmp.out 2>&1 &
-echo "pid=$!" >>$seq.full
-sleep 2		# let it start up
+echo "=== pmwebd default startup  ===" | tee -a $seq.full
+$PCP_BINADM_DIR/pmwebd $webargs -l $tmp.out -v -t10 &
 
-if [ -f $tmp.out ]
-then
-    cat $tmp.out >>$seq.full
+echo "pid=$!" >>$seq.full
+_wait_for_pmwebd_logfile $tmp.out
+
+# prepare the expected output file based on detected mode
+rm -f $seq.out
+if grep -q IPv6 $tmp.out; then
+    grep -q IPv4 $tmp.out || _notrun "QA host running in IPv6 mode only"
+    ln $seq.out.46 $seq.out	# ipv6 + ipv4
 else
-    echo "Arrgh ... pmwebd failed to start, $tmp.out not created"
-    $PCP_PS_PROG $PCP_PS_ALL_FLAGS | egrep '[P]ID|[p]mwebd'
-    exit
+    ln $seq.out.4 $seq.out	# ipv4 only
 fi
+
 curl -s -S "http://localhost:44323/pmapi/context?local=ANYTHING" \
 | tee -a $seq.full \
 | awk '{print $2}'
 echo >>$seq.full
-
-if [ ! -f /etc/hosts ]
-then
-    echo "Arrgh ... cannot find /etc/hosts to determine IPv6 localhost name"
-    exit
-fi
-ipv6local=''
-for sniff in localhost6 ip6-localhost
-do
-    if sed -e '/^#/d' -e 's/$/ /' /etc/hosts | grep -q "[ 	]$sniff "
-    then
-	ipv6local=$sniff
-	break
-    fi
-done
-if [ -z "$ipv6local" ]
-then
-    echo "Arrgh ... cannot determine IPv6 localhost name from /etc/hosts"
-    exit
-fi
-echo "ipv6local=$ipv6local" >>$seq.full
-
-rm -f $seq.out
 if grep -q IPv6 $tmp.out; then
     curl -s -S "http://$ipv6local:44323/pmapi/context?local=ANYTHING" \
     | tee -a $seq.full \
     | awk '{print $2}'
-    echo >>$seq.full
-    # ipv6 + ipv4
-    ln $seq.out.46 $seq.out
-else
-    # ipv4 only
-    ln $seq.out.4 $seq.out
-fi
-# NB: we don't anticipate an ipv6-only host
-
-echo | tee -a $seq.full
-echo "=== 2. pmwebd exercise via python ===" | tee -a $seq.full
-# pmwebd still running in default mode
-if grep -q IPv4 $tmp.out; then
-    python $pyscript --host localhost | _filter
-fi
-if grep -q IPv6 $tmp.out; then
-    python $pyscript --host "$ipv6local" | _filter
 fi
 
 echo | tee -a $seq.full
-echo "=== 3. pmwebd security constraints, file service ===" | tee -a $seq.full
+echo "=== pmwebd security constraints, file service ===" | tee -a $seq.full
 $sudo $signal -a pmwebd >/dev/null 2>&1
 sleep 2		# let it shutdown
 
-$PCP_BINADM_DIR/pmwebd $webargs -R `pwd` -c 2222 -L -N 2>/dev/null &
+cat $tmp.out >> $seq.full
+$PCP_BINADM_DIR/pmwebd $webargs -R `pwd` -c 2222 -L -h localhost -N -vv -l $tmp.out >$tmp.err 2>&1 &
 sleep 2		# let it start up
+cat $tmp.err >> $seq.full
 
-# should fail due to -N
-curl -s -S "http://localhost:44323/pmapi/context?local=anything" | _filter
-echo
-# should fail due to nonexistent context#
-curl -s -S "http://localhost:44323/pmapi/2223/_fetch" | _filter
-echo
-# should fail with a different error (insufficient elements; ie pmFetch failed) 
-curl -s -S "http://localhost:44323/pmapi/2222/_fetch" | _filter
-echo
-# should fail due to suspicious pmresapi path name
-curl -s -S "http://localhost:44323/../../etc/passwd" | _filter
-echo
-# should pass, feed this very script
-curl -s -S "http://localhost:44323/$seq" > $tmp.out
-diff $tmp.out $0 && echo file service ok
+echo "+++ should fail due to -N" | tee -a $seq.full
+curl -s -S "http://localhost:44323/pmapi/context?local=anything" \
+| tee -a $seq.full \
+| _webapi_response_filter
+echo | tee -a $seq.full
+
+echo "+++ should fail due to nonexistent context#" | tee -a $seq.full
+curl -s -S "http://localhost:44323/pmapi/2225/_fetch" \
+| tee -a $seq.full \
+| _webapi_response_filter
+echo | tee -a $seq.full
+
+echo "+++ should fail with a different error (insufficient elements; ie pmFetch failed)" | tee -a $seq.full
+# NB: the curl -v part reports http headers too, for ACAO presence assertion
+curl -s -v -S "http://localhost:44323/pmapi/2222/_fetch?names=" 2>&1 \
+| tee -a $seq.full \
+| _webapi_response_filter \
+| _filter
+echo | tee -a $seq.full
+
+echo "+++ should fail with a different error (insufficient elements; ie pmFetch failed)" | tee -a $seq.full
+curl -s -S "http://localhost:44323/pmapi/2223/_fetch?pmids=" \
+| tee -a $seq.full \
+| _webapi_response_filter
+echo | tee -a $seq.full
+
+# filter for responses from newer microhttpd libraries, where
+# symlink paths are rewritten (with verbose diagnostics that
+# indicate this, also).
+# Note: the request below must still generate a 400 response.
+_symlink_response_filter()
+{
+    sed \
+	-e 's,/../../etc/passwd,/etc/passwd,g' \
+	-e '/Rebuilt URL to:.*\/etc\/passwd/d' \
+    #end
+}
+
+echo "+++ should fail due to suspicious pmresapi path name" | tee -a $seq.full
+curl -s -v -S "http://localhost:44323/../../etc/passwd" 2>&1 \
+| tee -a $seq.full \
+| _webapi_response_filter \
+| _symlink_response_filter \
+| _filter
+echo | tee -a $seq.full
+
+echo "+++ should fail due to non-enablement of graphite" | tee -a $seq.full
+curl -s -v -S "http://localhost:44323/graphite/render?target=*" 2>&1 \
+| tee -a $seq.full \
+| _webapi_response_filter \
+| _filter
+
+echo | tee -a $seq.full
+echo "+++ should pass, feed this very script" | tee -a $seq.full
+curl -s -S "http://localhost:44323/$seq" > $tmp.out2
+diff $tmp.out2 $0 && echo file service ok
+
+cat $tmp.out >> $seq.full
 
 status=0
-sleep 2
 exit
diff --git a/src/qa/709 b/src/qa/709
--- a/src/qa/709
+++ b/src/qa/709
@@ -8,16 +8,10 @@
 seq=`basename $0`
 echo "QA output created by $seq"
 
-# get standard environment, filters and checks
-. ./common.product
-. ./common.filter
-. ./common.check
-
-[ $PCP_PLATFORM = linux ] || _notrun "test uses Linux-specific commands"
-
+. ./common.python
 status=0	# success is the default!
 $sudo rm -fr $tmp.* $seq.full
-trap "rm -fr $tmp.*; exit \$status" 0 1 2 3 15
+trap "cd $here; rm -fr $tmp.*; exit \$status" 0 1 2 3 15
 
 remove_extra_whitespace()
 {
@@ -32,10 +26,9 @@ remove_extra_whitespace()
 	-e 's/RECORD.*$/RECORD/' \
 	-e 's/<-*Int/<-Int/' \
 	-e 's/Int-*>/Int->/' \
-
+    # end
 }
 
-# sed -e 's/ [a-zA-Z0-9]* *$//'
 remove_extra_columns()
 {
     sed \
@@ -43,69 +36,84 @@ remove_extra_columns()
 	-e 's/ [a-zA-Z0-9 ]* *$//' \
 	-e 's/^#<-*-/#<--/g' \
 	-e 's/-*->/--->/g' \
+    # end
+}
 
+# using a given metric (arg1), check that each of its instances
+# exists in output file (arg2).
+#
+check_instances()
+{
+    metric=$1
+    file=$2
+    eval set -- `pmprobe -I $metric`
+    [ $? -eq 0 ] || exit 1
+    shift  # skip metric name
+    shift  # skip instance count
+    while [ $# -gt 0 ]
+    do
+	instance="$1"
+	shift
+	grep -q "$instance" $file && continue
+	echo "Instance $instance of $metric is missing from $file!"
+    done
 }
 
 # real QA test starts here
 mkdir $tmp.$seq
 cd $tmp.$seq
 
-#PYCOLLECTL=pmcollectl.py	# developer version
-PYCOLLECTL=pmcollectl		# installed version
-$PYCOLLECTL -sc -c2 | remove_extra_whitespace | tee -a $tmp.out 2>&1
-$PYCOLLECTL -sd -c2 | remove_extra_whitespace | tee -a $tmp.out 2>&1
-$PYCOLLECTL -sn -c2 | remove_extra_whitespace | tee -a $tmp.out 2>&1
-$PYCOLLECTL -sj -c2 | remove_extra_whitespace | remove_extra_columns | tee -a $tmp.out 2>&1
-$PYCOLLECTL -sm -c2 | remove_extra_whitespace | tee -a $tmp.out 2>&1
-$PYCOLLECTL -sc -c2 --verbose | remove_extra_whitespace | tee -a $tmp.out 2>&1
-$PYCOLLECTL -sd -c2 --verbose | remove_extra_whitespace | tee -a $tmp.out 2>&1
-$PYCOLLECTL -sn -c2 --verbose | remove_extra_whitespace | tee -a $tmp.out 2>&1
-$PYCOLLECTL -sm -c2 --verbose | remove_extra_whitespace | tee -a $tmp.out 2>&1
+PYCOLLECTL=pmcollectl.py	# developer version
+which $PYCOLLECTL >/dev/null 2>&1
+if [ $? -ne 0 ]; then
+    PYCOLLECTL=pmcollectl	# installed version
+    which $PYCOLLECTL >$tmp.cmd 2>&1 || _notrun "pmcollectl not installed"
+    PYCOLLECTL=`cat $tmp.cmd`
+    PYCOLLECTL="$python $PYCOLLECTL"
+fi
 
-$PYCOLLECTL -sN -c2 >| /tmp/,$$ 2>&1 
-for i in $(netstat -i | sed -e '/^[A-Z]/d' -e 's/ .*$//') ; do
-    if grep -q $i /tmp/,$$ ; then true ; else NOMATCH=1 ; fi
-done
-if [ ! -z "$NOMATCH" ] ; then
-    echo "No match for -sN";cat /tmp/,$$ >> $tmp.out
-    unset NOMATCH
-else
-    echo "-sN network interface names are okay"
-fi
-$PYCOLLECTL -sD -c2 >| /tmp/,$$ 2>&1 
-for i in $(lsblk -n -io KNAME,TYPE | grep disk | sed 's/ .*$//') ; do
-    if grep -q $i /tmp/,$$ ; then true ; else NOMATCH=1 ; fi
-done
-if [ ! -z "$NOMATCH" ] ; then
-    echo "No match for -sD";cat /tmp/,$$ >> $tmp.out
-else
-    echo "-sD disk names are okay"
-fi
+args="-c 2 -i 0.1"
+$PYCOLLECTL $args -sc | remove_extra_whitespace | tee -a $tmp.out 2>&1
+$PYCOLLECTL $args -sd | remove_extra_whitespace | tee -a $tmp.out 2>&1
+$PYCOLLECTL $args -sn | remove_extra_whitespace | tee -a $tmp.out 2>&1
+$PYCOLLECTL $args -sj | remove_extra_whitespace | remove_extra_columns | tee -a $tmp.out 2>&1
+$PYCOLLECTL $args -sm | remove_extra_whitespace | tee -a $tmp.out 2>&1
+$PYCOLLECTL $args -sc --verbose | remove_extra_whitespace | tee -a $tmp.out 2>&1
+$PYCOLLECTL $args -sd --verbose | remove_extra_whitespace | tee -a $tmp.out 2>&1
+$PYCOLLECTL $args -sn --verbose | remove_extra_whitespace | tee -a $tmp.out 2>&1
+$PYCOLLECTL $args -sm --verbose | remove_extra_whitespace | tee -a $tmp.out 2>&1
+
+$PYCOLLECTL $args -sN > $tmp.net 2>&1 
+check_instances network.interface.total.bytes $tmp.net
+
+$PYCOLLECTL $args -sD > $tmp.disk 2>&1 
+check_instances disk.dev.total_bytes $tmp.disk
+
 # need a generic way to test these on any system
-# $PYCOLLECTL -sC -c2 | remove_extra_whitespace | tee -a $tmp.out 2>&1
-# $PYCOLLECTL -sJ -c2 | remove_extra_whitespace | tee -a $tmp.out 2>&1
-# $PYCOLLECTL -sCD -c2 | remove_extra_whitespace | tee -a $tmp.out 2>&1
-$PYCOLLECTL -c2 | remove_extra_whitespace | tee -a $tmp.out 2>&1
-$PYCOLLECTL -c2 --verbose | remove_extra_whitespace | tee -a $tmp.out 2>&1
-$PYCOLLECTL -scd -c2 | remove_extra_whitespace | tee -a $tmp.out 2>&1
-$PYCOLLECTL -scd -c2 --verbose | remove_extra_whitespace | tee -a $tmp.out 2>&1
+# $PYCOLLECTL $args -sC | remove_extra_whitespace | tee -a $tmp.out 2>&1
+# $PYCOLLECTL $args -sJ | remove_extra_whitespace | tee -a $tmp.out 2>&1
+# $PYCOLLECTL $args -sCD | remove_extra_whitespace | tee -a $tmp.out 2>&1
+$PYCOLLECTL $args | remove_extra_whitespace | tee -a $tmp.out 2>&1
+$PYCOLLECTL $args --verbose | remove_extra_whitespace | tee -a $tmp.out 2>&1
+$PYCOLLECTL $args -scd | remove_extra_whitespace | tee -a $tmp.out 2>&1
+$PYCOLLECTL $args -scd --verbose | remove_extra_whitespace | tee -a $tmp.out 2>&1
+
 # test playback
-$PYCOLLECTL -sdDcCnNjJm -f test.pmcollectl -c10
-$PYCOLLECTL -sd -c2 -p test.pmcollectl | remove_extra_whitespace | tee -a $tmp.out 2>&1
-$PYCOLLECTL -sc -c2 -p test.pmcollectl | remove_extra_whitespace | tee -a $tmp.out 2>&1
-$PYCOLLECTL -sn -c2 -p test.pmcollectl | remove_extra_whitespace | tee -a $tmp.out 2>&1
-$PYCOLLECTL -sm -c2 -p test.pmcollectl | remove_extra_whitespace | tee -a $tmp.out 2>&1
-$PYCOLLECTL -sd -c2 -p test.pmcollectl --verbose | remove_extra_whitespace | tee -a $tmp.out 2>&1
-$PYCOLLECTL -sc -c2 -p test.pmcollectl --verbose | remove_extra_whitespace | tee -a $tmp.out 2>&1
-$PYCOLLECTL -sn -c2 -p test.pmcollectl --verbose | remove_extra_whitespace | tee -a $tmp.out 2>&1
-$PYCOLLECTL -sm -c2 -p test.pmcollectl --verbose | remove_extra_whitespace | tee -a $tmp.out 2>&1
-
-
+interval=0.1
+$PYCOLLECTL -sdDcCnNjJm -f test.pmcollectl -c10 -i $interval
+logargs="-c 2 -i $interval -p test.pmcollectl"
+$PYCOLLECTL $logargs -sd | remove_extra_whitespace | tee -a $tmp.out 2>&1
+$PYCOLLECTL $logargs -sc | remove_extra_whitespace | tee -a $tmp.out 2>&1
+$PYCOLLECTL $logargs -sn | remove_extra_whitespace | tee -a $tmp.out 2>&1
+$PYCOLLECTL $logargs -sm | remove_extra_whitespace | tee -a $tmp.out 2>&1
+$PYCOLLECTL $logargs -sd --verbose | remove_extra_whitespace | tee -a $tmp.out 2>&1
+$PYCOLLECTL $logargs -sc --verbose | remove_extra_whitespace | tee -a $tmp.out 2>&1
+$PYCOLLECTL $logargs -sn --verbose | remove_extra_whitespace | tee -a $tmp.out 2>&1
+$PYCOLLECTL $logargs -sm --verbose | remove_extra_whitespace | tee -a $tmp.out 2>&1
 cat $tmp.out >>$here/$seq.full
 
-# success, all done
-rm -rf test.pmcollectl
-cd $here
+eval `pmafm test.pmcollectl remove`
 
+# success, all done
 status=0
 exit
diff --git a/src/qa/admin/check-vm b/src/qa/admin/check-vm
--- a/src/qa/admin/check-vm
+++ b/src/qa/admin/check-vm
@@ -28,6 +28,118 @@ shift `expr $OPTIND - 1`
 tmp=/var/tmp/$$
 trap "rm -f $tmp.*; exit 0" 0 1 2 3 15
 
+# same function is in allow-pmlc-access ... need to track changes
+#
+_getnetworkaddr()
+{
+    if `which ifconfig >/dev/null 2>&1`
+    then
+	# expecting ifconfig lines like ...
+        # inet 192.168.1.222  netmask 255.255.255.0  broadcast 192.168.1.255
+	# inet addr:192.168.1.100  Bcast:192.168.1.255  Mask:255.255.255.0
+	#
+	# skip ip tunnels/vpns like
+	# inet addr:10.8.3.138  P-t-P:10.8.3.137  Mask:255.255.255.255
+	#
+	ifconfig \
+	| grep -v '[ :]127\.0\.0' \
+	| sed -n >$tmp.addr \
+	    -e '/^[ 	]*inet .*cast[ :]/{
+s/^[ 	]*inet[ 	]//
+s/^addr://
+s/[ 	][ 	]*broadcast[ 	][^ 	]*//
+s/:Bcast:[^ ]*//
+s/[ 	][ 	]*netmask[ 	]/ /
+s/[ 	][ 	]*Mask:/ /
+p
+}'
+	#debug# cat $tmp.addr >&2
+	num=`wc -l <$tmp.addr | sed -e 's/ //g'`
+	case "$num"
+	in
+	    1)	# good
+		addr=`cat $tmp.addr | sed -e 's/ .*//'`
+		mask=`cat $tmp.addr | sed -e 's/.* //'`
+		case "$mask"
+		in
+		    255.255.255.0|0xffffff00)	# /24 network
+			echo "$addr" | sed -e 's/\.[0-9]*$/.*/'
+			;;
+		    # pmcd's [access] is not smart enough to handle other
+		    # than /24 networks, so map the other likely options
+		    # to the broader /24 network
+		    #
+		    255.255.255.128|255.255.255.192|255.255.255.224|255.255.255.240|255.255.255.248|255.255.255.252|255.255.255.254)
+			echo "$addr" | sed -e 's/\.[0-9]*$/.*/'
+			;;
+		    *)
+			echo >&2 "_getnetworkaddr: cannot handle network mask: $mask"
+			;;
+		esac
+		;;
+	    0)	# none?
+		echo >&2 "_getnetworkaddr: cannot get network address"
+		;;
+	    *)	# multiple?
+		echo >&2 "_getnetworkaddr: cannot handle multiple network addresses:"
+		cat >&2 $tmp.addr
+		;;
+	esac
+    else
+	echo >&2 '_getnetworkaddr: no ifconfig?'
+    fi
+}
+
+# version1 is on line 1
+# version2 is on line 2
+# relop is "<", "<=", "=", ">=" or ">"
+# return value is 0 (true) if version1 relop version2 is true
+# else return value is 1
+#
+_compare()
+{
+    relop="$1"
+    awk -F. >$tmp.compare '
+NR == 1	{ for (i = 1; i <= NF; i++)
+	    v[i] = $i
+	  nv = NF
+	  next
+	}
+NR == 2	{ nf = NF
+	  if (nv > nf) nf = nv
+	  for (i = 1; i <= nf; i++) {
+	    if (v[i]+0 == $i+0) continue
+	    if (v[i]+0 < $i+0) {
+		print "<"
+		exit
+	    }
+	    if (v[i]+0 > $i+0) {
+		print ">"
+		exit
+	    }
+	  }
+	  print "="
+	}'
+    ret=1
+    case `cat $tmp.compare`
+    in
+	"<")
+	    [ "$relop" = "<" -o "$relop" = "<=" ] && ret=0
+	    ;;
+	"=")
+	    [ "$relop" = "=" -o "$relop" = "<=" -o "$relop" = ">=" ] && ret=0
+	    ;;
+	">")
+	    [ "$relop" = ">" -o "$relop" = ">=" ] && ret=0
+	    ;;
+	*)
+	    echo "Arrgh ... installed version $version, want $relop $specversion,"
+	    echo "but failed to extract relop (`cat $tmp.compare`)"
+	    ;;
+    esac
+    return $ret
+}
+
 # add additional and optional directories
 for dir in /sbin /usr/sbin
 do
@@ -45,7 +157,7 @@ done
 
 # perl ? apt-get install -qqy --force-yes libxml-tokeparser-perl
 # perl ? apt-get install -qqy --force-yes libspreadsheet-read-perl
-cat <<End-of-File | sed -e 's/#.*//' -e '/^[ 	]*$/d' | while read apps
+cat <<End-of-File >$tmp.control
 # one line per app, alternate items separated by white space
 # first item ending in ? means this item is a guard, if it does not
 # exist silently ignore the rest of the line
@@ -54,6 +166,7 @@ cat <<End-of-File | sed -e 's/#.*//' -e '/^[ 	]*$/d' | while read apps
 #                               (alternates separated by |)
 #	containing ::		test for presence of the associated Perl module
 #	otherwise		test for an executable with which(1)
+#                               (alternates separated by |)
 #
 # text after # is treated as a comment
 # text after [ is treated as annotation
@@ -69,6 +182,7 @@ bison
 gdb
 mktemp
 gawk
+cpan				[(QA optional)]
 # optional executables
 dpkg?	dpkg-buildpackage	[dpkg-dev]
 dpkg?	dh			[debhelper]
@@ -76,20 +190,26 @@ dpkg?	chrpath			[chrpath]
 dpkg?	sysv-rc-conf		[sysv-rc-conf]
 rpm?	rpmbuild		[rpm-build]
 # other build prerequisites
-rpm?	/usr/share/doc/packages/python-ctypes	[python-ctypes]
 dpkg?	/usr/share/doc/pkg-config	[pkg-config]
 dpkg?	/usr/share/doc/python-all-dev	[python-all-dev]
-dpkg?	/usr/include/microhttpd.h	[libmicrohttpd-dev]
-rpm?	/usr/include/microhttpd.h	[libmicrohttpd-devel]
-dpkg?	/usr/include/sasl/sasl.h	[libsasl2-dev]
-rpm?	/usr/include/sasl/sasl.h	[cyrus-sasl-devel]
-rpm?	/usr/include/systemd/sd-daemon.h	[systemd-devel but not for CentOS 5.8]
-dpkg?	/usr/include/infiniband/umad.h	[libibumad-dev]
-rpm?	/usr/include/infiniband/umad.h	[libibumad-devel]
-dpkg?	/usr/include/infiniband/mad.h	[libibmad-dev]
-rpm?	/usr/include/infiniband/mad.h	[libibmad-devel]
-dpkg?	/usr/include/avahi-common	[libavahi-common-dev]
-rpm?	/usr/include/avahi-common	[avahi-devel]
+dpkg?	/usr/include/microhttpd.h	[libmicrohttpd-dev (build optional)]
+rpm?	/usr/include/microhttpd.h	[libmicrohttpd-devel (build optional)]
+dpkg?	/usr/include/cairo/cairo.h	[libcairo2-dev (build optional)]
+rpm?	/usr/include/cairo/cairo.h	[cairo-devel (build optional)]
+dpkg?	/usr/include/sasl/sasl.h	[libsasl2-dev (build optional)]
+rpm?	/usr/include/sasl/sasl.h	[cyrus-sasl-devel (build optional)]
+rpm?	/usr/include/systemd/sd-daemon.h	[systemd-devel (build optional)]
+dpkg?	/usr/include/infiniband/umad.h	[libibumad-dev (build optional)]
+rpm?	/usr/include/infiniband/umad.h	[libibumad-devel (build optional)]
+dpkg?	/usr/include/infiniband/mad.h	[libibmad-dev (build optional)]
+rpm?	/usr/include/infiniband/mad.h	[libibmad-devel (build optional)]
+dpkg?	/usr/include/avahi-common	[libavahi-common-dev (build optional)]
+rpm?	/usr/include/avahi-common	[avahi-devel (build optional)]
+dpkg?	/usr/include/papi.h		[libpapi-dev (build optional)]
+rpm?	/usr/include/papi.h		[papi-devel (build optional)]
+dpkg?	/usr/include/perfmon/pfmlib_perf_event.h	[libpfm4-dev (build optional)]
+rpm?	/usr/include/perfmon/pfmlib_perf_event.h	[libpfm-devel (build optional)]
+rpm?	/usr/include/rpm/header.h	[rpm-devel (build optional)]
 dpkg?	g++				[g++]
 rpm?	g++				[gcc-c++]
 # files
@@ -105,47 +225,82 @@ dpkg?	ExtUtils::MakeMaker	[libextutils-autoinstall-perl]
 rpm?	ExtUtils::MakeMaker	[perl-ExtUtils-MakeMaker]
 dpkg?	XML::TokeParser		[libxml-tokeparser-perl]
 rpm?	XML::TokeParser		[perl-XML-TokeParser]
-Spreadsheet::Read		[libspreadsheet-read-perl(dpkg)]
+rpm?	RRDs::			[rrdtool-perl or perl-rrdtool]
+dpkg?	RRDs::			[librrds-perl]
+dpkg?	Spreadsheet::Read	[libspreadsheet-read-perl (QA optional)]
+rpm?	Spreadsheet::Read	[from cpan (QA optional)]
 dpkg?	Spreadsheet::WriteExcel	[libspreadsheet-writeexcel-perl]
-rpm?	Spreadsheet::WriteExcel	[perl-Spreadsheet-WriteExcel]
-Spreadsheet::ReadSXC		[cpan?]
+rpm?	Spreadsheet::WriteExcel	[perl-Spreadsheet-WriteExcel or cpan]
+rpm?	JSON::			[perl-JSON]
+Spreadsheet::ReadSXC		[from cpan (QA optional)]
+rpm	time			[time]
 # other run-time
 sadf				[sysstat]
 # QA
-bc
-Spreadsheet::XLSX		[libspreadsheet-xlsx-perl(dpkg)]
-dpkg?	Text::CSV_XS		[Text-CSV_XS]
-rpm?	Text::CSV_XS		[perl-Text-CSV_XS]
+bc				[(QA optional)]
+curl				[(QA optional)]
+socat				[(QA optional)]
+dpkg?	Spreadsheet::XLSX	[libspreadsheet-xlsx-perl (QA optional)]
+rpm?	Spreadsheet::XLSX	[from cpan (QA optional)]
+dpkg?	Text::CSV_XS		[Text-CSV_XS (QA optional)]
+rpm?	Text::CSV_XS		[perl-Text-CSV_XS (QA optional)]
 crontab				[from vixie-cron?]
-valgrind
-dpkg?	mail			[bsd-mailx]
-rpm?	mail			[mailx]
+valgrind			[(QA optional)]
+dpkg?	mail			[bsd-mailx (QA optional)]
+rpm?	mail			[mailx (QA optional)]
 host				[bind-utils(redhat)]
-dpkg?	apache2			[apache2]
-rpm?	httpd			[httpd]
-time				[time(redhat)]
+dpkg?	apache2			[apache2 (QA optional)]
+rpm?	httpd			[httpd (QA optional)]
 dpkg?	realpath		[realpath]
+dpkg?	unbound-control		[unbound (QA optional)]
+rpm?	/usr/share/doc/python-requests*	[python-requests (QA optional)]
+dpkg?	/usr/share/doc/python-requests	[python-requests (QA optional)]
 # pcp-gui
-dpkg?	qmake			[qt4-qmake]
-rpm?	qmake			[qt-devel]
-dpkg?	/usr/lib/libQtCore.so|/usr/lib/*/libQtCore.so	[libqt4-dev]
-rpm?	/usr/lib/libQtCore.so	[qt-devel]
-dpkg?	/usr/lib/libQtAssistantClient.so|/usr/lib/*/libQtAssistantClient.so	[libqtassistantclient-dev]
-rpm?	/usr/lib/libQtAssistantClient.so	[qt4-assistant-adp-devel(suse) qt-assistant-adp-devel(fedora)]
+dpkg?	qmake			[qt4-qmake (build optional)]
+rpm?	qmake|/usr/lib64/qt4/bin/qmake|/usr/lib/qt4/bin/qmake		[qt4-devel (build optional)]
+dpkg?	/usr/lib/libSoQt4.so|/usr/lib/*/libSoQt4.so	[libsoqt-dev (build optional)]
+rpm?	/usr/lib/libQtCore.so|/usr/lib*/libQtCore.so|/usr/lib/qt4/lib/libQtCore.so	[qt4-devel (build optional)]
+dpkg?	/usr/include/Inventor/Qt/SoQt.h	[libsoqt-dev-common (build optional)]
+dpkg?	/usr/include/Inventor/SoPath.h	[libcoin60-dev or libcoin80-dev (build optional)]
 # python
-rpm?	/usr/include/python*/Python.h		[python-devel]
-rpm?	/usr/lib*/python*/site-packages/ctypes|/usr/lib*/python*/ctypes	[python-ctypes]
-dpkg?	/usr/include/python*/Python.h		[python-dev]
+rpm?	/usr/include/python*/Python.h	[python-devel]
+dpkg?	/usr/include/python*/Python.h	[python-dev]
+rpm?	/usr/lib*/python*/curses	[python-curses]
 # nss
-dpkg?	/usr/include/nspr/nspr.h	[libnspr4-dev]
-rpm?	/usr/include/nspr4/nspr.h	[nspr-devel]
-dpkg?	/usr/include/nss/nss.h		[libnss3-dev]
-rpm?	/usr/include/nss3/nss.h		[nss-devel]
-dpkg?	certutil			[libnss3-tools]
-rpm?	certutil			[nss-tools]
+dpkg?	/usr/include/nspr/nspr.h	[libnspr4-dev (build optional)]
+rpm?	/usr/include/nspr4/nspr.h	[nspr-devel (build optional)]
+dpkg?	/usr/include/nss/nss.h		[libnss3-dev (build optional)]
+rpm?	/usr/include/nss3/nss.h		[nss-devel (build optional)]
+dpkg?	certutil			[libnss3-tools (build optional)]
+rpm?	certutil			[nss-tools or mozilla-nss-tools (build optional)]
 End-of-File
+
+if which python >/dev/null 2>&1
+then
+    # For python-ctypes, check for python before 2.5 ... expect something like
+    # Python 2.7.3
+    eval `python -V 2>&1 | sed -e 's/Python //' -e 's/^/maj=/' -e 's/\./ min=/' -e 's/\..*//'`
+    if [ -n "$maj" -a -n "$min" ]
+    then
+	rm -f $tmp.need
+	if [ "$maj" -lt 2 ]
+	then
+	    touch $tmp.need
+	elif [ "$maj" -eq 2 -a "$min" -lt 5 ]
+	then
+	    touch $tmp.need
+	fi
+	[ -f $tmp.need ] && \
+	    echo "rpm?	/usr/share/doc/python-ctypes*	[python-ctypes]" >>$tmp.control
+    fi
+fi
+
+cat $tmp.control \
+| sed -e 's/#.*//' -e '/^[ 	]*$/d' \
+| while read apps
 do
     rm -f $tmp.ok
+    rm -f $tmp.echo
     for app in $apps
     do
 	case $app
@@ -179,24 +334,48 @@ do
 		[ -f $tmp.tmp ]
 		ok=$?
 		;;
+	    *::)
+		# special case Perl, no module name
+		echo "use `echo $app | sed -e 's/::$//'`;" | perl >/dev/null 2>&1
+		ok=$?
+		;;
+
 	    *::*)
+		# normal case Perl, with module name
 		echo "use $app;" | perl >/dev/null 2>&1
 		ok=$?
 		;;
 	    *)
-		which $app >/dev/null 2>&1
+		rm -f $tmp.tmp
+		for exec in `echo "$app" | sed -e 's/|/ /g'`
+		do
+		    if which $exec >/dev/null 2>&1
+		    then
+			touch $tmp.tmp
+			break
+		    fi
+		done
+		[ -f $tmp.tmp ]
 		ok=$?
 		;;
 	esac
 	if $verbose
 	then
-	    echo -n " .. $app"
-	    $optional && echo -n "[optional]"
-	    if [ $ok = 0 ]
+	    if [ "$app" = dpkg -o "$app" = rpm ]
 	    then
-		echo -n " yes"
+		# rpm? and dpkg? guards are not really useful to report
+		#
+		:
 	    else
-		echo -n " no"
+		echo -n "$app ... "
+		$optional && echo -n "[optional]"
+		if [ $ok = 0 ]
+		then
+		    echo -n "yes "
+		else
+		    echo -n "no "
+		fi
+		touch $tmp.echo
 	    fi
 	fi
 	if [ $ok = 0 ]
@@ -213,7 +392,7 @@ do
 	    fi
 	fi
     done
-    $verbose && echo
+    [ -f $tmp.echo ] && echo
     if [ ! -f $tmp.ok ]
     then
 	echo "Missing: `echo $apps \
@@ -246,6 +425,84 @@ then
 	    :
 	else
 	    echo "Need # apt-get install $pkg"
+	fi
+    done
+    # There are some version dependencies in the debian/control file
+    # (see Build-Depends and *-Version lines) and some are found in
+    # configure.ac ... both need to be mirrored here
+    #
+    cat <<End-of-File >$tmp.control
+# one line per package
+# pkg-name	relop	version
+# text after # is treated as a comment
+# debian/control
+debhelper	>=	5
+perl		>=	5.6
+python		>=	2.6
+# configure.ac
+libmicrohttpd	>	0.9.9
+libcairo2-dev	>=	1.2
+End-of-File
+    cat $tmp.control \
+    | sed -e 's/#.*//' -e '/^[ 	]*$/d' \
+    | while read pkg relop ctlversion
+    do
+	# dpkg -l lines like ...
+	# ii  debhelper      9.20131227ub all          ...
+	#
+	if grep "ii[ 	][ 	]*$pkg[ 	]" $tmp.tmp >/dev/null 2>&1
+	then
+	    version=`awk <$tmp.tmp '$2 == "'"$pkg"'" { print $3 }'`
+	    if [ -z "$version" ]
+	    then
+		echo "Arrgh ... failed to get version for $pkg from ..."
+		cat $tmp.tmp
+		continue
+	    fi
+	    ( echo $version; echo $ctlversion ) | _compare $relop
+	    if [ $? = 0 ]
+	    then
+		$verbose && echo "$pkg: version installed $version, need $relop $ctlversion, OK"
+	    else
+		echo "Warning: $pkg version installed $version, need $relop $ctlversion"
+	    fi
+	fi
+    done
+fi
+
+if which rpm >/dev/null 2>&1
+then
+    # RPM based, there are some version dependencies in the spec
+    # file (see BuildRequires: lines build/rpm/pcp.spec.in) and some
+    # are found in configure.ac ... both need to be mirrored here
+    #
+    cat <<End-of-File >$tmp.control
+# one line per rpm
+# rpm-name	relop	version
+# text after # is treated as a comment
+# pcp.spec.in
+qt-devel	>=	4.4
+qt4-devel	>=	4.4
+libpfm-devel	>=	4.4
+libibmad-devel	>=	1.1.7
+libibumad-devel	>=	1.1.7
+# configure.ac
+libmicrohttpd	>	0.9.9
+cairo-devel		>=	1.2
+End-of-File
+    cat $tmp.control \
+    | sed -e 's/#.*//' -e '/^[ 	]*$/d' \
+    | while read rpm relop specversion
+    do
+	rpm -q $rpm >$tmp.tmp 2>/dev/null
+	grep 'is not installed' $tmp.tmp >/dev/null 2>&1 && continue
+	version=`sed <$tmp.tmp -e "s/^$rpm-//" -e 's/-.*//'`
+	( echo $version; echo $specversion ) | _compare $relop
+	if [ $? = 0 ]
+	then
+	    $verbose && echo "$rpm: version installed $version, need $relop $specversion, OK"
+	else
+	    echo "Warning: $rpm version installed $version, need $relop $specversion"
 	fi
     done
 fi
@@ -304,3 +561,31 @@ then
 	_check_host $pmhost
     fi
 fi
+
+if [ -f /etc/pcp.conf ]
+then
+    . /etc/pcp.conf
+
+    # need QA access to pmlogger via pmlc from local subnet
+    #
+    network=`_getnetworkaddr`
+    if [ -n "$network" ]
+    then
+	if [ -f $PCP_VAR_DIR/config/pmlogger/config.default ]
+	then
+	    if grep -q "allow $network" $PCP_VAR_DIR/config/pmlogger/config.default
+	    then
+		:
+	    else
+		echo "Missing: \"allow $network : all;\" [access] in $PCP_VAR_DIR/config/pmlogger/config.default"
+		echo "Use \"$ sudo -E .../qa/admin/allow-pmlc-access\" to fix this."
+	    fi
+	else
+	    echo "Warning: \"$PCP_VAR_DIR/config/pcp/pmlogger/config.default\" is missing"
+	fi
+    fi
+else
+    echo "Warning: \"/etc/pcp.conf\" is missing"
+fi
+
+sudo -u pcp [ -x $HOME ] || echo "Error: $HOME is not searchable by user \"pcp\""
diff --git a/src/qa/admin/pcp-daily b/src/qa/admin/pcp-daily
--- a/src/qa/admin/pcp-daily
+++ b/src/qa/admin/pcp-daily
@@ -3,13 +3,6 @@
 # Run test builds on one or more PCP machines
 #
 
-tmp=/var/tmp/$$
-sts=0
-trap "rm -f $tmp.*; exit \$sts" 0 1 2 3 15
-
-list_1="vm03 vm01 vm04 vm07 vm12 vm14 vm16 vm18 vm20 vm22 vm24"
-list_2="fuji grundy vm02 vm00 vm05 vm11 vm15 vm19 vm21 vm23"
-
 _usage()
 {
     echo >&2 "Usage: `basename $0` [options] vm ..."
@@ -17,6 +10,7 @@ _usage()
     echo >&2 "  -a          all except shutdown VM [implies -pmiqh]"
     echo >&2 "  -b branch   pcp branch to checkout [default $pcp_branch]"
     echo >&2 "  -c          check git repositories"
+    echo >&2 "  -d          output debugging diagnostics"
     echo >&2 "  -e file     prerun script"
     echo >&2 "  -f          force shutdown"
     echo >&2 "  -g what     QA tests or groups to run, e.g. -g \"123 -g sanity -x remote\""
@@ -41,268 +35,21 @@ _usage()
     echo >&2 "[both vmlists run in parallel for the default case without -S]"
 }
 
-args="$*"
-pcp_branch=dev
-pcp_tree=pcp
-cflag=false
-fflag=false
-hflag=false
-iflag=false
-mflag=false
-pflag=false
-qflag=false
-rflag=false
-what="-g sanity -g libpcp -g pdu -g pmda -g valgrind -g pmie"
-what=all
-sflag=false
-Sflag=false
-options=false
-work=false
-efile=''
-while getopts "ab:B:ce:fg:himpqrsSt:T:?" c
-do
-    case $c
-    in
-	a)
-	    options=true
-	    work=true
-	    pflag=true
-	    mflag=true
-	    iflag=true
-	    qflag=true
-	    hflag=true
-	    ;;
-	b)
-	    pcp_branch="$OPTARG"
-	    ;;
-	c)
-	    options=true
-	    work=true
-	    cflag=true
-	    ;;
-	e)
-	    efile="$OPTARG"
-	    if [ -f "$efile" ]
-	    then
-		:
-	    else
-		echo "Error: $efile: cannot be found"
-		sts=1
-		exit
-	    fi
-	    ;;
-	f)
-	    fflag=true
-	    ;;
-	g)
-	    what="$OPTARG"
-	    ;;
-	h)
-	    options=true
-	    work=true
-	    hflag=true
-	    ;;
-	i)
-	    options=true
-	    work=true
-	    iflag=true
-	    ;;
-	m)
-	    options=true
-	    work=true
-	    mflag=true
-	    ;;
-	p)
-	    options=true
-	    work=true
-	    pflag=true
-	    ;;
-	q)
-	    options=true
-	    work=true
-	    qflag=true
-	    ;;
-	r)
-	    options=true
-	    work=true
-	    rflag=true
-	    ;;
-	s)
-	    options=true
-	    sflag=true
-	    ;;
-	S)
-	    Sflag=true
-	    ;;
-	t)
-	    pcp_tree="$OPTARG"
-	    ;;
-	?)
-	    _usage
-	    sts=1
-	    exit
-	    ;;
-    esac
-done
-shift `expr $OPTIND - 1`
-
-if [ $# -eq 0 ]
-then
-    if $Sflag
-    then
-	# serial run
-	set -- $list_1 $list_2
-    else
-	# run in parallel
-	set -- $list_1
-	pcp-daily $args $list_2 &
-    fi
-fi
-
-if $options
-then
-    :
-else
-    # defaults
-    #
-    work=true
-    pflag=true
-    mflag=true
-    iflag=true
-    qflag=true
-    hflag=true
-    sflag=true
-fi
-
-today=`date +%Y-%m-%d`
-mkdir -p $HOME/Logs/by-date/$today
-
-rm -f $tmp.domains
-echo "bozo" >>$tmp.domains
-echo "bozo-vm" >>$tmp.domains
-echo "bozo-laptop" >>$tmp.domains
-echo "fuji" >>$tmp.domains
-echo "grundy.sgi.com" >>$tmp.domains
-if which virsh >/dev/null 2>&1
-then
-    virsh list --all \
-    | sed >>$tmp.domains \
-        -e 1d \
-        -e '/-----/d' \
-        -e 's/^  *//' \
-        -e 's/^[0-9][0-9]*[ 	]*//' \
-        -e 's/^-[ 	]*//' \
-	-e 's/[    ].*//' \
-        -e '/^$/d'
-fi
-
-for target
-do
-    grep "^$target" <$tmp.domains >$tmp.domain
-    if [ ! -s $tmp.domain ]
-    then
-	echo "No domain matches \"$target\" ... the domains I have are ..."
-	cat $tmp.domains
-	continue
-    fi
-    count=`wc -l <$tmp.domain | sed -e 's/ //g'`
-    if [ $count != 1 ]
-    then
-	echo "More than one domain matches \"$target\" ... the matches I have are ..."
-	cat $tmp.domain
-	continue
-    fi
-    domain=`cat $tmp.domain`
-    host=`echo $domain | sed -e '/^vm/s/-.*//'`
-    echo "::: $domain :::"
-    # per-host settings
-    # MAKE=gmake for *BSD hosts
-    #
-    MAKE=make
-    case "$domain"
-    in
-	*freebsd*|*netbsd*)
-	    MAKE=gmake
-	    ;;
-    esac
-
-    if which virsh >/dev/null 2>&1
-    then
-	state=`virsh list --all | grep "$domain" | awk '{print $3}'`
-	case "$state"
-	in
-	    shut)
-		if $work
-		then
-		    sudo virsh start $domain
-		    state=running
-		fi
-		;;
-	    running)
-		;;
-	    paused)
-		if $work
-		then
-		    sudo virsh resume $domain
-		    state=running
-		fi
-		;;
-	    '')
-		# probably not a VM, like "fuji"
-		;;
-	    *)
-		echo "No clue what do with virsh state \"$state\""
-		continue
-		;;
-	esac
-    fi
-
-    if $work
-    then
-	log=$HOME/Logs/by-date/$today/$domain
-	touch $log
-	mkdir -p $HOME/Logs/by-vm/$domain
-	if [ ! -L $HOME/Logs/by-vm/$domain/$today ]
-	then
-	    ( cd $HOME/Logs/by-vm/$domain; ln -s ../../by-date/$today/$domain $today )
-	fi
-
-	rm -f $tmp.up
-	wait=0
-	delta=5
-	max_wait=300
-	while [ $wait -lt $max_wait ]
-	do
-	    # if ping -c 1 $host >/dev/null 2>&1
-	    # then
-		if ssh $host true
-		then
-		    #debug# echo host up
-		    touch $tmp.up
-		    break
-		fi
-	    # else
-		#debug# echo host down
-		# :
-	    # fi
-	    sleep $delta
-	    wait=`expr $wait + $delta`
-	done
-	if [ ! -f $tmp.up ]
-	then
-	    echo "Failed to start VM domain $domain after $max_wait secs ... giving up"
-	    continue
-	fi
-
-	cat >$tmp.script <<End-of-File
+_script_header()
+{
+    cat <<End-of-File
 #!/bin/sh
 #
 # PCP Build Script from pcp-daily on `date`
 #
 
 [ -f \$HOME/.dailyrc ] && . \$HOME/.dailyrc
-#debug# echo PATH=\$PATH
-#debug# which ${MAKE:-make}
+if [ $debug = true ]
+then
+    echo PATH=\$PATH
+    echo MAKE=\$MAKE
+    which ${MAKE:-make}
+fi
 
 tmp=/var/tmp/\$\$
 trap "rm -f \$tmp.*; exit 0" 0 1 2 3 15
@@ -318,22 +65,22 @@ in
 	    echo "Info: clone $pcp_tree git tree" | tee -a \$HOME/daily.log
 	fi
 	;;
-    secure-pcp)
-	if [ ! -d src/secure-pcp ]
+    *)
+	if [ ! -d src/$pcp_tree ]
 	then
-	    git clone ssh://bozo/home/kenj/git/${pcp_tree}.git src/secure-pcp
-	    echo "Info: clone $pcp_tree-pcp git tree" | tee -a \$HOME/daily.log
+	    git clone ssh://bozo/home/kenj/src/${pcp_tree} src/$pcp_tree
+	    echo "Info: clone $pcp_tree git tree" | tee -a \$HOME/daily.log
 	fi
 	;;
 esac
 
 cd src/$pcp_tree
 End-of-File
-	if [ -n "$efile" ]
-	then
-	    cat $efile >>$tmp.script
-	fi
-	cat >>$tmp.script <<End-of-File
+}
+
+_script_git()
+{
+    cat <<End-of-File
 git branch -a >\$tmp.branch
 if grep " $pcp_branch\$" <\$tmp.branch >/dev/null
 then
@@ -349,8 +96,11 @@ else
     fi
 fi
 End-of-File
+}
 
-	$cflag && cat >>$tmp.script <<End-of-File
+_script_git_check()
+{
+    cat <<End-of-File
 git status -s | grep 'M ' >\$tmp.status
 if [ -s \$tmp.status ]
 then
@@ -360,14 +110,18 @@ else
     echo "Info: No modified pcp files" | tee -a \$HOME/daily.log
 fi
 End-of-File
+}
 
-	$pflag && cat >>$tmp.script <<End-of-File
+_script_git_pull()
+{
+    cat <<End-of-File
 # need to clean before pulling in case unwanted files no longer removed,
 # e.g. in PCP 3.x -> PCP 4.0 migration of source base
 # not needed any longer - 26 Mar 2013
 #${MAKE:-make} clean >>\$HOME/daily.log 2>&1
 # only VERSION.pcp is expected to be modified, sometimes!
-git checkout -f VERSION.pcp
+rm -f VERSION.pcp
+git checkout -- VERSION.pcp
 if git checkout $pcp_branch >>\$HOME/daily.log 2>&1
 then
     echo "Info: pcp git checkout $pcp_branch" | tee -a \$HOME/daily.log
@@ -383,11 +137,13 @@ else
     exit 1
 fi
 End-of-File
+}
 
-	if $mflag
-	then
-	    echo "${MAKE:-make} clean >>\$HOME/daily.log 2>&1" >>$tmp.script
-	    cat >>$tmp.script <<'End-of-File'
+_script_make()
+{
+    # not needed - 4 Oct 2014
+    # echo "${MAKE:-make} clean >>\$HOME/daily.log 2>&1"
+    cat <<'End-of-File'
 ok=false
 # if needed, bump build number for pcp-daily
 if [ ! -f VERSION.pcp.daily ]
@@ -416,8 +172,8 @@ sudo rm -f /usr/lib*/libpcp[_.]*
 # clean up any build turds
 rm -f qa/qa_outfiles
 End-of-File
-	    echo "if MAKE=$MAKE ./Makepkgs --clean >>\$HOME/daily.log 2>&1" >>$tmp.script
-	    cat >>$tmp.script <<'End-of-File'
+    echo "if MAKE=$MAKE ./Makepkgs --clean >>\$HOME/daily.log 2>&1"
+    cat <<'End-of-File'
 then
     ok=true
 else
@@ -430,12 +186,14 @@ else
     else
 	echo "Error: Makepkgs failed!" | tee -a $HOME/daily.log
 	# restore build number
-	git checkout -f VERSION.pcp
+	rm -f VERSION.pcp
+	git checkout -- VERSION.pcp
 	exit 1
     fi
 fi
 # restore build number
-git checkout -f VERSION.pcp
+rm -f VERSION.pcp
+git checkout -- VERSION.pcp
 # Look for errors/warnings in the build logs ...
 #
 for log in Logs/*
@@ -459,9 +217,11 @@ then
 fi
 $ok && echo "Info: Makepkgs" | tee -a $HOME/daily.log
 End-of-File
-	fi
+}
 
-	$iflag && cat >>$tmp.script <<'End-of-File'
+_script_install()
+{
+    cat <<'End-of-File'
 # extract buildversion
 . ./VERSION.pcp
 if [ -z "$PACKAGE_MAJOR" -o -z "$PACKAGE_MINOR" -o -z "$PACKAGE_REVISION" ]
@@ -472,10 +232,11 @@ then
     exit 1
 fi
 buildversion=$PACKAGE_MAJOR.$PACKAGE_MINOR.$PACKAGE_REVISION
-# find lsm ... in pcp-$buildversion for most build types, but in . for debian
+# find lsm ... in pcp-$buildversion for most build types, but in 
+# build/deb/pcp-$buildversion for debian
 lsm=''
-[ -f pcp.lsm ] && lsm=pcp.lsm
 [ -f pcp-$buildversion/pcp.lsm ] && lsm=pcp-$buildversion/pcp.lsm
+[ -f build/deb/pcp-$buildversion/pcp.lsm ] && lsm=build/deb/pcp-$buildversion/pcp.lsm
 if [ -z "$lsm" ]
 then
     ls -l pcp.lsm* pcp-$buildversion/pcp.lsm* | tee -a $HOME/daily.log
@@ -603,10 +364,12 @@ then
     : pmcd started above
 else
     . /etc/pcp.env
-    if sudo $PCP_RC_DIR/pcp start >>$HOME/daily.log 2>&1
+    if sudo $PCP_RC_DIR/pcp start >$tmp.out 2>&1
     then
+	cat $tmp.out >>$HOME/daily.log
 	echo "Info: pmcd started" | tee -a $HOME/daily.log
     else
+	cat $tmp.out >>$HOME/daily.log
 	echo "Error: pmcd start failed" | tee -a $HOME/daily.log
 	exit 1
     fi
@@ -620,26 +383,14 @@ then
     echo "Error: version mismatch src=$src_version running=$running_version" | tee -a $HOME/daily.log
     exit 1
 fi
+# sample PMDA may have an updated PMNS, so re-install just in case
+( cd $PCP_VAR_DIR/pmdas/sample; sudo ./Install </dev/null ) >>$HOME/daily.log
 End-of-File
+}
 
-	cat >>$tmp.script <<End-of-File
-
-cd qa
-End-of-File
-
-	check_what="$what"
-	[ X"$what" = Xall ] && check_what=''
-	# Need to add
-	# -x remote default for grundy.sgi.com if running all tests
-	#
-	case "$domain"
-	in
-	    *grundy*)
-		[ X"$what" = Xall ] && check_what='$check_what -x remote'
-		;;
-	esac
-
-	$qflag && cat >>$tmp.script <<End-of-File
+_script_qa()
+{
+    cat <<End-of-File
 rm -f *.out.bad
 ./changeversion >/dev/null 2>&1
 if ./check -l $check_what >>\$HOME/daily.log 2>&1
@@ -656,8 +407,11 @@ NF == 0	{ txt = ""; next }
 END	{ print txt }' | tee -a \$HOME/daily.log
 fi
 End-of-File
+}
 
-	$rflag && cat >>$tmp.script <<End-of-File
+_script_qa_rerun()
+{
+    cat <<End-of-File
 if ./recheck >>\$HOME/daily.log 2>&1
 then
     echo "Info: QA recheck" | tee -a \$HOME/daily.log
@@ -665,8 +419,11 @@ else
     echo "Error: QA recheck failed!" | tee -a \$HOME/daily.log
 fi
 End-of-File
+}
 
-	$hflag && cat >>$tmp.script <<End-of-File
+_script_harvest()
+{
+    cat <<End-of-File
 rm -f \$HOME/daily.harvest
 touch \$HOME/daily.harvest
 nbad=0
@@ -687,6 +444,348 @@ done
 [ -s \$HOME/daily.harvest ] && cat \$HOME/daily.harvest >>\$HOME/daily.log
 echo "Info: harvest \$nbad *.bad files, \$nfull *.full files" | tee -a \$HOME/daily.log
 End-of-File
+}
+
+# Mainline starts here ...
+#
+
+tmp=/var/tmp/$$
+sts=0
+trap "rm -f $tmp.*; exit \$sts" 0 1 2 3 15
+
+list_1="vm03 vm01 vm04 vm07 vm12 vm14 vm16 vm18 vm20 vm22 vm24"
+list_2="fuji grundy vm02 vm00 vm05 vm11 vm15 vm19 vm21 vm23"
+
+args="$*"
+pcp_branch=dev
+pcp_tree=pcp
+cflag=false
+fflag=false
+hflag=false
+iflag=false
+mflag=false
+pflag=false
+qflag=false
+rflag=false
+what="-g sanity -g libpcp -g pdu -g pmda -g valgrind -g pmie"
+what=all
+sflag=false
+Sflag=false
+options=false
+work=false
+efile=''
+debug=false
+while getopts "ab:B:cde:fg:himpqrsSt:T:?" c
+do
+    case $c
+    in
+	a)
+	    options=true
+	    work=true
+	    pflag=true
+	    mflag=true
+	    iflag=true
+	    qflag=true
+	    hflag=true
+	    ;;
+	b)
+	    pcp_branch="$OPTARG"
+	    ;;
+	c)
+	    options=true
+	    work=true
+	    cflag=true
+	    ;;
+	d)
+	    debug=true
+	    ;;
+	e)
+	    efile="$OPTARG"
+	    if [ -f "$efile" ]
+	    then
+		:
+	    else
+		echo "Error: $efile: cannot be found"
+		sts=1
+		exit
+	    fi
+	    ;;
+	f)
+	    fflag=true
+	    ;;
+	g)
+	    what="$OPTARG"
+	    ;;
+	h)
+	    options=true
+	    work=true
+	    hflag=true
+	    ;;
+	i)
+	    options=true
+	    work=true
+	    iflag=true
+	    ;;
+	m)
+	    options=true
+	    work=true
+	    mflag=true
+	    ;;
+	p)
+	    options=true
+	    work=true
+	    pflag=true
+	    ;;
+	q)
+	    options=true
+	    work=true
+	    qflag=true
+	    ;;
+	r)
+	    options=true
+	    work=true
+	    rflag=true
+	    ;;
+	s)
+	    options=true
+	    sflag=true
+	    ;;
+	S)
+	    Sflag=true
+	    ;;
+	t)
+	    pcp_tree="$OPTARG"
+	    ;;
+	?)
+	    _usage
+	    sts=1
+	    exit
+	    ;;
+    esac
+done
+shift `expr $OPTIND - 1`
+
+if [ $# -eq 0 ]
+then
+    if $Sflag
+    then
+	# serial run
+	set -- $list_1 $list_2
+    else
+	# run in parallel
+	set -- $list_1
+	pcp-daily $args $list_2 &
+    fi
+fi
+
+if $options
+then
+    :
+else
+    # defaults
+    #
+    work=true
+    pflag=true
+    mflag=true
+    iflag=true
+    qflag=true
+    hflag=true
+    sflag=true
+fi
+
+today=`date +%Y-%m-%d`
+mkdir -p $HOME/Logs/by-date/$today
+
+rm -f $tmp.domains
+
+# some driver host specific things ...
+#
+case `hostname`
+in
+    bozo)
+	echo "bozo" >>$tmp.domains
+	echo "bozo-vm" >>$tmp.domains
+	echo "bozo-laptop" >>$tmp.domains
+	echo "fuji" >>$tmp.domains
+	echo "grundy.sgi.com" >>$tmp.domains
+	# and open up the X server
+	#
+	DISPLAY=localhost:0.0 xhost + >/dev/null
+	;;
+esac
+
+if which virsh >/dev/null 2>&1
+then
+    virsh list --all \
+    | sed >>$tmp.domains \
+        -e 1d \
+        -e '/-----/d' \
+        -e 's/^  *//' \
+        -e 's/^[0-9][0-9]*[ 	]*//' \
+        -e 's/^-[ 	]*//' \
+	-e 's/[    ].*//' \
+        -e '/^$/d'
+fi
+
+for target
+do
+    grep "^$target" <$tmp.domains >$tmp.domain
+    if [ ! -s $tmp.domain ]
+    then
+	echo "No domain matches \"$target\" ... the domains I have are ..."
+	cat $tmp.domains
+	continue
+    fi
+    count=`wc -l <$tmp.domain | sed -e 's/ //g'`
+    if [ $count != 1 ]
+    then
+	echo "Warning: More than one domain matches \"$target\" ... the matches I have are ..."
+	cat $tmp.domain
+	echo "... using the first one."
+    fi
+    domain=`sed -e 1q $tmp.domain`
+    # used to be vmNN-osname&version, but now just vmMM ...
+    # old sed now does nothing
+    #
+    host=`echo $domain | sed -e '/^vm/s/-.*//'`
+    echo "::: $domain :::"
+
+    if which virsh >/dev/null 2>&1
+    then
+	state=`virsh list --all | grep "$domain" | awk '{print $3}'`
+	case "$state"
+	in
+	    shut)
+		if $work
+		then
+		    sudo virsh start $domain
+		    state=running
+		fi
+		;;
+	    running)
+		;;
+	    paused)
+		if $work
+		then
+		    sudo virsh resume $domain
+		    state=running
+		fi
+		;;
+	    '')
+		# probably not a VM, like "fuji"
+		;;
+	    *)
+		echo "No clue what do with virsh state \"$state\""
+		continue
+		;;
+	esac
+    fi
+
+    if $work
+    then
+	log=$HOME/Logs/by-date/$today/$domain
+	touch $log
+	mkdir -p $HOME/Logs/by-vm/$domain
+	if [ ! -L $HOME/Logs/by-vm/$domain/$today ]
+	then
+	    ( cd $HOME/Logs/by-vm/$domain; ln -s ../../by-date/$today/$domain $today )
+	fi
+
+	rm -f $tmp.up
+	wait=0
+	delta=5
+	max_wait=300
+	while [ $wait -lt $max_wait ]
+	do
+	    # if ping -c 1 $host >/dev/null 2>&1
+	    # then
+		if ssh $host true
+		then
+		    $debug && echo host up
+		    touch $tmp.up
+		    break
+		fi
+	    # else
+		$debug && echo host down
+	    # fi
+	    sleep $delta
+	    wait=`expr $wait + $delta`
+	done
+	if [ ! -f $tmp.up ]
+	then
+	    echo "Failed to start VM domain $domain after $max_wait secs ... giving up"
+	    continue
+	fi
+	
+	check=`ssh -t $host uname -sr 2>/dev/null`
+	$debug && echo "check=$check"
+	case "$check"
+	in
+	    FreeBSD\ *)
+	    	osname=freebsd
+		;;
+	    NetBSD\ *)
+	    	osname=netbsd
+		;;
+	    *)
+	    	osname=unknown
+		;;
+	esac
+	$debug && echo "osname=$osname"
+
+	# per-host settings
+	# MAKE=gmake for *BSD hosts
+	#
+	MAKE=make
+	case "$osname"
+	in
+	    freebsd|netbsd)
+		MAKE=gmake
+		;;
+	esac
+	$debug && echo "MAKE=$MAKE"
+
+	_script_header >$tmp.script
+	if [ -n "$efile" ]
+	then
+	    cat $efile >>$tmp.script
+	fi
+	_script_git >>$tmp.script
+	$cflag && _script_git_check >>$tmp.script
+	$pflag && _script_git_pull >>$tmp.script
+
+	if $mflag
+	then
+	    _script_make >>$tmp.script
+	fi
+
+	$iflag && _script_install >>$tmp.script
+
+	cat >>$tmp.script <<End-of-File
+
+cd qa
+End-of-File
+
+	check_what="$what"
+	[ X"$what" = Xall ] && check_what=''
+	case "$domain"
+	in
+	    *grundy*)
+		# Need to add
+		# -x remote default for grundy.sgi.com if running all tests
+		#
+		[ X"$what" = Xall ] && check_what='$check_what -x remote'
+		;;
+	    vm06|vm10)
+		# Only -g sanity at this stage for FreeBSD
+		#
+		[ X"$what" = Xall ] && check_what='-g sanity'
+		;;
+	esac
+
+	$qflag && _script_qa >>$tmp.script
+	$rflag && _script_qa_rerun >>$tmp.script
+	$hflag && _script_harvest >>$tmp.script
 
 	chmod 755 $tmp.script
 	if scp $tmp.script $host:daily.script >$tmp.out 2>&1
@@ -697,11 +796,21 @@ End-of-File
 	    echo "Error: scp failed!"
 	    continue
 	fi
+
+	# actually do the remote work here
+	#
 	ssh -t $host sh -c ./daily.script
+
 	scp -q $host:daily.log $tmp.out
 	echo "=== `date` ===" >>$log
 	cat $tmp.out >>$log
 	echo "=== END ===" >>$log
+
+	if $iflag
+	then
+	    # run whatami on QA host
+	    ssh -t $host src/pcp/qa/admin/whatami >$HOME/Logs/by-vm/$domain/whatami
+	fi
 
 	if $hflag
 	then
diff --git a/src/src/libpcp/src/check-statics b/src/src/libpcp/src/check-statics
--- a/src/src/libpcp/src/check-statics
+++ b/src/src/libpcp/src/check-statics
@@ -95,7 +95,7 @@ AF.o
 auxconnect.o
     canwait			# guarded by __pmLock_libpcp mutex
     first_time			# guarded by __pmLock_libpcp mutex
-    pmcd_port			# guarded by __pmLock_libpcp mutex
+    pmcd_ports			# guarded by __pmLock_libpcp mutex
     pmcd_socket			# guarded by __pmLock_libpcp mutex
 auxserver.o
     nport			# single-threaded server scope
@@ -115,6 +115,7 @@ discovery.o
     szActiveServices		# single-threaded server scope
     activeServices		# single-threaded server scope
     threadedPoll		# single-threaded server scope
+    simplePoll			# single-threaded server scope
     client			# single-threaded server scope
     group			# single-threaded server scope
     done_default		# guarded by __pmLock_libpcp mutex
@@ -132,10 +133,8 @@ connectlocal.o
 connect.o
     global_nports		# guarded by __pmLock_libpcp mutex
     global_portlist		# guarded by __pmLock_libpcp mutex
-    default_portlist		# guarded by __pmLock_libpcp mutex
     first_time			# guarded by __pmLock_libpcp mutex
     proxy			# guarded by __pmLock_libpcp mutex
-    proxy_port			# guarded by __pmLock_libpcp mutex
 context.o
     _mode			# const
     def_backoff			# guarded by __pmLock_libpcp mutex
@@ -184,6 +183,7 @@ events.o
     name_missed			# guarded by __pmLock_libpcp mutex
     pmid_flags			# no unsafe side-effects
     pmid_missed			# no unsafe side-effects
+    ?caller                     # const
 fault.o
 fetchlocal.o
     splitlist			# single-threaded PM_SCOPE_DSO_PMDA
@@ -216,10 +216,8 @@ help.o
 instance.o
 interp.o
     dowrap			# guarded by __pmLock_libpcp mutex
-    round_robin			# guarded by __pmLock_libpcp mutex
     nr				# diag counters, no atomic updates
     nr_cache			# diag counters, no atomic updates
-    cache			# guarded by __pmLock_libpcp mutex
     statestr			# const
 ipc.o
     __pmIPCTable		# guarded by __pmLock_libpcp mutex
@@ -249,16 +247,16 @@ logutil.o
     tbuf			# __pmLogName deprecated by __pmLogName_r
     compress_ctl		# const
     ?ncompress			# const
-    __pmLogReads		# diag counter, no atomic updates
+    ?__pmLogReads		# diag counter, no atomic updates
     pc_hc			# guarded by __pmLock_libpcp mutex
 secureserver.o
     secure_server		# guarded by __pmLock_libpcp mutex
 secureconnect.o
-    ?nsprFds			# guarded by __pmLock_libpcp mutex
     common_callbacks		# const
+    initialized			# single-threaded
 optfetch.o
     optcost			# guarded by __pmLock_libpcp mutex
-p_auth.o
+p_attr.o
 p_creds.o
 p_desc.o
 pdubuf.o
@@ -313,6 +311,7 @@ pmns.o
 p_pmns.o
 p_profile.o
 p_result.o
+probe.o
 profile.o
 p_text.o
 rtime.o
@@ -345,6 +344,11 @@ units.o
     abuf			# pmAtomStr deprecated by pmAtomStr_r
     tbuf			# pmTypeStr deprecated by pmTypeStr_r
     ubuf			# pmUnitsStr deprecated by pmUnitsStr_r
+    count_keywords              # const
+    exponent_keywords           # const
+    space_keywords              # const
+    time_keywords               # const
+    time_scales                 # const
 util.o
     idbuf			# pmIDStr deprecated by pmIDStr_r
     indombuf			# pmInDomStr deprecated by pmInDomStr_r
@@ -377,6 +381,14 @@ End-of-File
 
 for file in *.o
 do
+    case "$file"
+    in
+	'*.o')
+	    echo "Error: no object files!! Need some drive-by make action?"
+	    exit 1
+	    ;;
+    esac
+    
     if grep "^?*$file\$" $tmp/ctl >/dev/null 2>&1
     then
 	:
@@ -391,7 +403,7 @@ skip_file=false
 cat $tmp/ctl \
 | while read line
 do
-    if expr $line : "^.*\.o$" >/dev/null  # .o file
+    if expr $line : '.*\.o$' >/dev/null  # .o file
     then
 	if [ -n "$obj" ]
 	then
@@ -415,6 +427,9 @@ do
 		# + static arrays and some debug (?) symbols appear as
 		#   "s", but the latter have _.NNN appended, or start
 		#   with LC, or have .eh appended, or start with EH_
+                # + __func__ macro expansion results in L___func__.<FName>
+		#   entries
+                # + scoped static could has scope name prepended
 		# + older versions insert get_pc_thunk symbols in all
 		#   object files
 		# for MinGW
@@ -423,6 +438,8 @@ do
 		# + external symbols tend to have "C" lines
 		# for FreeBSD
 		# + strip  r __func__.NNN lines
+		# for NetBSD
+		# + strip  r CSWTCH.NNN lines
 		#
 		skip_file=false
 		nm $line \
@@ -431,6 +448,13 @@ do
 		    -e '/ [sS] .*\.eh$/d' \
 		    -e '/ s .*_\.[0-9][0-9]*$/d' \
 		    -e '/ s LC[0-9][0-9]*$/d' \
+		    -e '/ s L_\.str[0-9][0-9]*$/d' -e '/ s L_\.str$/d' \
+		    -e '/ s L___func__\./d' \
+		    -e '/ s .*\$tlv\$init$/d' \
+		    -e 's/b \([_a-zA-Z][_a-zA-Z0-9]*\)\.b$/b \1/' \
+		    -e 's/b \([_a-zA-Z][_a-zA-Z0-9]*\)\.[0-9]*.[0b]$/b \1/' \
+		    -e 's/\([bds] \).*\.\([_a-zA-Z]\)/\1\2/' \
+		    -e 's/s _glib_relative_date\./s /' \
 		    -e '/ s EH_/d' \
 		    -e '/ b \.bss/d' \
 		    -e '/ d \.data/d' \
@@ -438,6 +462,7 @@ do
 		    -e '/ r \.eh_frame/d' \
 		    -e '/ r __PRETTY_FUNCTION__.[0-9][0-9]*$/d' \
 		    -e '/ r __func__.[0-9][0-9]*$/d' \
+		    -e '/ r CSWTCH.[0-9][0-9]*$/d' \
 		    -e '/ r \.LC[0-9][0-9]*$/d' \
 		    -e '/ C ___pmLogReads/d' \
 		    -e '/ C ___pmNativeConfig/d' \
